.TH MPM 1 "October 2025" "mpm version 2.5-7" "User Commands"
.SH NAME
mpm \- MPV Playlists Manager
.SH SYNOPSIS
.B mpm
[\fIOPTION\fR] [\fIPLAYLIST\fR]
.SH DESCRIPTION
.PP
Mpm is a tool used in a terminal to manage playlists that will be played by mpv and to download
online media files provided for example on YouTube using yt-dlp.
To get started, you will need to collect links from all supported websites listed on the yt-dlp
GitHub repository <https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md> that provide
downloadable media URLs. The yt-dlp extractors handle obtaining and negotiating these links.
Some of these may require cookies.
.PP
To be able to provide cookies the only way is to use the mpmsw script that you will find in
the extra directory (./mpv-playlists-manager/extra/mpmsw), edit options and variables in the
dedicaded section. To use it, first schedule your downloads via mpm by loading a collection
playlist, once selected the LOAD/DOWNLOAD menu appears, then use the Schedule download option.
In a separate terminal run the mpmsw scritp, ensure it is in your $PATH.
.PP
URLs are first stored in two categories (audio or video) and merged in the default list which
will stay even after closing the program, the audio/video temporary lists have to be saved
before that, you will be prompted when trying to exit. Saved playlists are stored in the
collection directory whitch you first have to configure via the mpmrc file.
.PP
Mpm can use optional dependencies: dialog, fzf, less, mediainfo, parallel, and ytfzf.
This will provide better results and different ways of handling things.
This will make the user experience easier. All these tools are configurable in the mpmrc file.
.SH OPTIONS
.TP
.BR \-c ", " \-\-config
Opens ~/.config/mpm/{mpmrc,themerc} configuration files
.TP
.BR \-e ", " \-\-edit " [" \fIPLAYLIST\fR ]
Opens the playlist edition function, with optional playlist name argument, the playlist name has to be exact
.TP
.BR \-h ", " \-\-help
Displays the /usr/local/share/doc/help file (more detailed than this man page)
.TP
.BR \-l ", " \-\-load " [" \fIPLAYLIST\fR ]
Opens the play/download function, with optional playlist name argument, the playlist name has to be exact
.TP
.BR \-f ", " \-\-local
Opens local files or directory function
.TP
.BR \-u ", " \-\-upgrade
Upgrades mpm regardless of update checking settings
.TP
.BR \-v ", " \-\-version
Displays mpm version
.SH DEPENDENCIES
.TP
.B Required:
ffmpeg, jq, mpv, vim/nano, socat, yt-dlp
.TP
.B Optional:
fzf, mpvc, ncmpvc, parallel, ranger, ueberzug, w3m, ytfzf
.SH CONFIGURATION
The configuration file is located at ~/.config/mpm/mpmrc. You can customize:
.TP
.B Themes:
Colors and formatting in ~/.config/mpm/themerc
.TP
.B Default files paths
~/.local/share/mpv-playlists-manager/{playlists,schedules,titles,tmp}
.TP
.B Default downloads paths
~/.local/share/mpv-playlists-manager/mpm_{audios,videos}
.TP
.B Features:
Enable/disable various features like fzf, mpvc, parallel, etc...
.SH MAIN MENU OPTIONS
.TP
.B 1) Create/Add video playlist
Add video links to temporary playlist
.TP
.B 2) Create/Add audio playlist
Add audio links to temporary playlist
.TP
.B 3) Save as/Delete a playlist
Save temporary lists or delete collection playlists
.TP
.B 4) Play/Download playlists
Stream, download or schedule download media from the selected playlist
.TP
.B 5) Load local folder/files
Play media from local directories
.TP
.B 6) View default playlist
View contents of the default playlist
.TP
.B 7) Clear all tmp lists
Remove all temporary playlists (default,video,audio)
.TP
.B 8) Edit a playlist
Modify existing playlists:
Edit URLs/titles, rename the playlist or delete particular titles from the playlist
.TP
.B 9) Edit mpm config files
Modify mpm configuration files (mpmrc,themerc), changes are effectives right after
.SH KEYBOARD SHORTCUTS
.TP
.B Main Menu:
.RS
.TP
.B a
Create/Add links to Audio list
.TP
.B b
Show main window bindings
.TP
.B c
Edit mpm config files
.TP
.B d
Access default playlist
.TP
.B e
Edit collection playlist
.TP
.B f
Load local files
.TP
.B h
Previous song
.TP
.B j
Stop/quit mpv
.TP
.B k
Toggle play/pause
.TP
.B l
Next song
.TP
.B m
Access manuals & help
.TP
.B n
Launch mpv TUI
.TP
.B p
Load/Download collection playlists
.TP
.B q
Quit mpv
.TP
.B r
Refresh main window
.TP
.B s
Save/Remove playlist
.TP
.B t
Display current title
.TP
.B u
Show help screen
.TP
.B v
Create/Add links to Video list
.TP
.B V
Launch pulsemixer or ncpamixer
.TP
.B x
Quit mpm
.TP
.B y
View scheduled downloads
.TP
.B z
Clear temporary lists
.TP
.B Ctrl+B
Change themes
.TP
.B Ctrl+M
Quick view mpmrc
.RE
.SH NATIVE MPV INTERFACE SHORTCUTS
.TP
.B Enter
Play selected item
.TP
.B Left arrow
Seek 30s backward
.TP
.B Right arrow
Seek 30s forward
.TP
.B Ctrl+N
Play next item
.TP
.B Ctrl+P
Play previous item
.TP
.B Ctrl+T
Toggle pause
.TP
.B Ctrl+V
Launch pulsemixer or ncpamixer
.TP
.B Ctrl+R
Reload playlist
.TP
.B Ctrl+X
Quit mpv
.TP
.B Escape
Exit interface
.SH AUDIO CONVERSION
Audio conversion settings can be configured in mpmrc:
.TP
.B automatic_audio_conversion
Enable/disable automatic conversion
.TP
.B default_conversion_format
Set default format (aac|flac|mp3|ogg|wav)
.TP
.B parallel_conversion
Use parallel to speed up audio conversion, useful for non-lossless formats
.SH UPGRADE PROCEDURE
.TP
.B Method 1:
.RS
.nf
git clone https://github.com/archusXIV/mpv-playlists-manager.git
cd ./mpv-playlists-manager
sudo ./install.sh
.fi
.RE
.TP
.B Method 2 (if folder exists):
.RS
.nf
cd ./mpv-playlists-manager
git fetch
git reset --hard HEAD
git merge '@{u}'
sudo ./install.sh
.fi
.RE
.TP
.B Method 3 (using Makefile):
.RS
.nf
sudo make install && make config (first time installation)
sudo make upgrade && make diff-config (upgrade installation)
how to use it?: make help
.fi
.RE
.SH AUTHOR
Barret E <archus@protonmail.com>
.SH SEE ALSO
.BR mpv (1),
.BR yt-dlp (1),
.BR ffmpeg (1)
.SH BUGS
Report bugs at https://github.com/archusXIV/mpv-playlists-manager/issues
.SH COPYRIGHT
Copyright © 2025 Barret E
.SH LINKS
.TP
.B Homepage:
https://github.com/archusXIV/mpv-playlists-manager
.TP
.B YouTube:
https://www.youtube.com/@mpv-playlists-manager-mv8sh/featured
https://www.youtube.com/@linuxinfrench9388/featured
