#!/bin/bash
# ~/.config/mpm/mpmrc

########################################################
#                                                      #
#    ███╗   ███╗██████╗ ███╗   ███╗██████╗  ██████╗    #
#    ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔════╝    #
#    ██╔████╔██║██████╔╝██╔████╔██║██████╔╝██║         #
#    ██║╚██╔╝██║██╔═══╝ ██║╚██╔╝██║██╔══██╗██║         #
#    ██║ ╚═╝ ██║██║     ██║ ╚═╝ ██║██║  ██║╚██████╗    #
#    ╚═╝     ╚═╝╚═╝     ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝    #
#                                                      #
####### MPV-PLAYLISTS-MANAGER CONFIGURATION FILE #######
######### THE PLACE FOR YOUR PERSONAL SETTINGS #########
#~~~~~ change the values, not the variables names ~~~~~#

# shellcheck disable=SC2034,SC2016

## prompts & messages colors
# https://misc.flogisoft.com/bash/tip_colors_and_formatting
nc=$'\e[0m';          # normal text
critical=$'\e[0;31m'; # red (critical)
info=$'\e[0;32m';     # green (info)
task=$'\e[96m';       # cyan (tasks settings)
mtitle=$'\e[33m';     # yellow (menus title)

: "${XDG_DATA_HOME:-$HOME/.local/share}"

## default editor
MPMEDITOR="vim"

## default file manager (can be any terminal file manager)
## used in option 5) Load local dir/files
FILEMANAGER="ranger"

## THESE ARE BY DEFAULT DIRECTORIES USED BY MPM.

# The main directory can be renamed but must be present for mpm to work.
# main_dir="$HOME/Documents/mpv-playlists-manager"
main_dir="$XDG_DATA_HOME/mpv-playlists-manager"

# The default playlist & all the created ones are stored here.
playlists_dir="$main_dir/playlists"

# Be carefull with this one because if you choose to use
# the conversion action, ALL .webm files in that directory will be converted.
audios_dir="$main_dir/audios"

videos_dir="$main_dir/videos"

titles_dir="$main_dir/titles"

tmp_dir="$main_dir/tmp"

## DEFAULT TASKS ANSWERS
# from download tasks (option 4) we are prompted or not to choose formats.
# (will appear in main menu)
direct_download="no"

# some links may be still present in playlist files...
# if value is 'no' you will be prompted.
keep_none_empty_playlist="yes"

# audio files (.webm) conversion.
# (will appear in main menu)
automatic_audio_conversion="no"

# default audio conversion format {mp3,flac,wav,ogg},
# mp3 & ogg in 320k, flac & wav are lossless.
# if value is empty you will be prompted.
# (will appear in main menu)
default_conversion_format="mp3"

# this takes place only after downloading/playing from a collection playlist.
# (will appear in main menu)
quit_after_task="no"

## FFMPEG SPECIFICS (audio conversion)
# !!! You can change ffmpeg audio codec command line settings !!!
function _mp3 {
    find . -iname "*.webm" -exec \
    bash -c 'FILE="$1"; \
        ffmpeg -i "${FILE}" \
        -acodec libmp3lame -ar 48000 -ab 320k \
        -y "${FILE%.webm}.mp3";' _ '{}' \; 2>"$FFOP"
}

function _flac {
    find . -iname "*.webm" -exec \
    bash -c 'FILE="$1"; \
        ffmpeg -i "${FILE}" \
        -af aformat=s32:48000 \
        -y "${FILE%.webm}.flac";' _ '{}' \; 2>"$FFOP"
}

function _wav {
    find . -iname "*.webm" -exec \
    bash -c 'FILE="$1"; \
        ffmpeg -i "${FILE}" \
        -acodec pcm_s32le -ar 48000 \
        -y "${FILE%.webm}.wav";' _ '{}' \; 2>"$FFOP"
}

function _ogg {
    find . -iname "*.webm" -exec \
    bash -c 'FILE="$1"; \
        ffmpeg -i "${FILE}" \
        -acodec libvorbis -ar 48000 -ab 320k \
        -y "${FILE%.webm}.ogg";' _ '{}' \; 2>"$FFOP"
}

## MPV SPECIFICS
# mpv audio playing command line
function _MpvAudioOptions {
    # change mpv audio settings here if needed but do not remove $M3UFILE
    mpv \
    --input-ipc-server='/tmp/mpvsocket' \
    --no-config \
    --term-playing-msg='Title: ${media-title}' \
    --ytdl-format='bestaudio/best' "$M3UFILE"
}

# mpm video playing command line
function _MpvVideoOptions {
    # same as above.
    mpv \
    --input-ipc-server='/tmp/mpvsocket' \
    --cache \
    --no-config \
    --term-playing-msg='Title: ${media-title}' \
    --ytdl-format='299+251/298+251/137+251/136+251/best' "$M3UFILE"
}
