#!/usr/bin/env bash
# ~/.config/mpm/themerc (version 2.5-3)

###########################################################################
#'########:'##::::'##:'########:'##::::'##:'########:'########:::'######::#
#... ##..:: ##:::: ##: ##.....:: ###::'###: ##.....:: ##.... ##:'##... ##:#
#::: ##:::: ##:::: ##: ##::::::: ####'####: ##::::::: ##:::: ##: ##:::..::#
#::: ##:::: #########: ######::: ## ### ##: ######::: ########:: ##:::::::#
#::: ##:::: ##.... ##: ##...:::: ##. #: ##: ##...:::: ##.. ##::: ##:::::::#
#::: ##:::: ##:::: ##: ##::::::: ##:.:: ##: ##::::::: ##::. ##:: ##::: ##:#
#::: ##:::: ##:::: ##: ########: ##:::: ##: ########: ##:::. ##:. ######::#
#:::..:::::..:::::..::........::..:::::..::........::..:::::..:::......:::#
############## MPV-PLAYLISTS-MANAGER THEME CONFIGURATION FILE #############
#~~~~~~~~~~~~~~~ change the values, not the variables names ~~~~~~~~~~~~~~#

# shellcheck disable=SC2034,SC2016,SC2154

################# PROMPTS & MESSAGES COLORS #################
### https://misc.flogisoft.com/bash/tip_colors_and_formatting
### Console_colors (default) will always use your current ~/.Xresources colors,
### or custom rgb/hex colors so you can set your own theme.
### nc=normal text, critical=warnings, info=normal prompt, mtitle=menus title,
### task=infos like: direct download, audio conversion type etc...
### customColors is called from lib/_LittleStars function.

# set your default background color here, it will be used when you quit the app.
default_bg="#1e1f29"
# if you use ~/.Xresources with colors, uncomment the line below.
# default_bg=$(xrdb -query | awk '/background:/{print $NF}')
# if you want to recall variables below, use double quotes.

_NativePlayerColors() {

    case "$1" in
        default)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#87afaf
                --color=fg:#af5faa,fg+:#ffffff,bg:$default_bg,bg+:#2e3944
                --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87
                --color=prompt:#af5fff,spinner:#af5fff,pointer:#af5fff
                --color=border:#554476,label:#5fd7ff,query:#d9d9d9
                --border-label-pos='102:bottom'
                --border-label '| theme: default |'
            "
        ;;
        c64)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#DD8855
                --color=fg:#0088FF,fg+:#ffffff,bg:#0000AA,bg+:#0000AA
                --color=hl:#FF7777,hl+:#AAFF66,info:#AAFFEE
                --color=prompt:#AAFF66,spinner:#880000,pointer:#CC44CC
                --color=border:#BBBBBB,label:#EEEE77,query:#BBBBBB
                --border-label-pos='106:bottom'
                --border-label '| theme: c64 |'
            "
        ;;
        dark)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#87afaf
                --color=fg:#d0d0d0,fg+:#ffffff,bg:#121212,bg+:#262626
                --color=hl:#5f87af,hl+:#5fd7ff,info:#afaf87
                --color=prompt:#d7005f,spinner:#af5fff,pointer:#af5fff
                --color=border:#262626,label:#aeaeae,query:#d9d9d9
                --border-label-pos='105:bottom'
                --border-label '| theme: dark |'
            "
        ;;
        embers)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#576d82
                --color=fg:#998C82,fg+:#787D57,bg:$default_bg,bg+:$default_bg
                --color=hl:#576d82,hl+:#82576d,info:#afaf87
                --color=prompt:#82576d,spinner:#af5fff,pointer:#82576d
                --color=border:#57826d,label:#998C82,query:#d9d9d9
                --border-label-pos='103:bottom'
                --border-label '[ theme: embers ]'
            "
        ;;
        gruvbox)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#928374
                --color=bg+:#3c3836,bg:#32302f,border:#6B6B6B
                --color=spinner:#fb4934,hl:#928374,fg:#ebdbb2
                --color=info:#8ec07c,pointer:#fb4934,fg+:#ebdbb2
                --color=preview-bg:#3c3836,prompt:#fb4934,hl+:#fb4934
                --border-label-pos='102:bottom'
                --border-label '| theme: gruvbox |'
            "
        ;;
        molokai)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#7E8E91
                --color=bg+:#293739,bg:#1B1D1E,border:#808080
                --color=spinner:#E6DB74,hl:#7E8E91,fg:#F8F8F2
                --color=info:#A6E22E,pointer:#A6E22E,fg+:#F8F8F2
                --color=prompt:#F92672,hl+:#F92672
                --border-label-pos='102:bottom'
                --border-label '| theme: molokai |'
            "
        ;;
        nord)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#616E88
                --color=bg+:#3B4252,bg:#2E3440,border:#6B6B6B
                --color=spinner:#81A1C1,hl:#616E88,fg:#D8DEE9
                --color=info:#81A1C1,pointer:#81A1C1,fg+:#D8DEE9
                --color=preview-bg:#3B4252,prompt:#81A1C1,hl+:#81A1C1
                --border-label-pos='105:bottom'
                --border-label '| theme: nord |'
            "
        ;;
        seoul256)
            export FZF_DEFAULT_OPTS="
                --color=header:bold:#719872
                --color=bg+:#3F3F3F,bg:#4B4B4B,border:#6B6B6B
                --color=spinner:#98BC99,hl:#719872,fg:#D9D9D9
                --color=info:#BDBB72,pointer:#E12672,fg+:#D9D9D9
                --color=preview-bg:#3F3F3F,prompt:#98BEDE,hl+:#98BC99
                --border-label-pos='101:bottom'
                --border-label '| theme: seoul256 |'
            "
        ;;
    esac

}

_Theme() {

    case "$1" in
        default)
            bg="$default_bg"
            nc=$'\e[0m';
            critical=$'\e[31m';
            info=$'\e[32m';
            mtitle=$'\e[33m';
            task=$'\e[37m';
        ;;
        blacksea)
            # Using HEX colors for array 'customColors'
            bg="$default_bg"
            nc=$'\e[38;2;118;114;232m';       #7672E8 "0x76 0x72 0xe8"
            critical=$'\e[38;2;160;109;78m';  #A06D4E "0xa0 0x6d 0x4e"
            info=$'\e[38;2;105;176;191m';     #69B0BF "0x69 0xb0 0xbf"
            mtitle=$'\e[38;2;129;124;92m';    #817C5C "0x81 0x7c 0x5c"
            task=$'\e[38;2;248;248;240m';     #f8f8f0 "0xf8 0xf8 0xf0"
            customColors=( "0x76 0x72 0xe8" "0xa0 0x6d 0x4e" "0x69 0xb0 0xbf" \
            "0x81 0x7c 0x5c" "0xf8 0xf8 0xf0" )
        ;;
        dracula)
            bg="#282a36"
            nc=$'\e[38;2;189;147;249m';       #BD93F9 "0xbd 0x93 0xf9"
            critical=$'\e[38;2;255;85;85m';   #FF5555 "0xff 0x55 0x55"
            info=$'\e[38;2;80;250;123m';      #50FA7B "0x50 0xfa 0x7b"
            mtitle=$'\e[38;2;241;250;140m';   #F1FA8C "0xf1 0xfa 0x8c"
            task=$'\e[38;2;191;191;191m';     #BFBFBF "0xbf 0xbf 0xbf"
            customColors=( "0xbd 0x93 0xf9" "0xff 0x55 0x55" "0x50 0xfa 0x7b" \
            "0xf1 0xfa 0x8c" "0xbf 0xbf 0xbf" )
        ;;
        embers)
            bg="$default_bg"
            nc=$'\e[38;2;153;140;130m';       #998C82 "0x99 0x8c 0x82"
            critical=$'\e[38;2;130;87;109m';  #82576d "0x82 0x57 0x6d"
            info=$'\e[38;2;87;130;109m';      #57826d "0x57 0x82 0x6d"
            mtitle=$'\e[38;2;120;125;87m';    #787D57 "0x78 0x7d 0x57"
            task=$'\e[38;2;87;109;130m';      #576d82 "0x57 0x6d 0x82"
            customColors=( "0x99 0x8c 0x82" "0x82 0x57 0x6d" "0x57 0x82 0x6d" \
            "0x78 0x7d 0x57" "0x57 0x6d 0x82" )
        ;;
        gotham)
            bg="#251930"
            nc=$'\e[38;2;25;84;101m';         #195465 "0x19 0x54 0x65"
            critical=$'\e[38;2;210;105;57m';  #d26939 "0xd2 0x69 0x39"
            info=$'\e[38;2;38;169;139m';      #26A98B "0x26 0xa9 0x8b"
            mtitle=$'\e[38;2;237;181;75m';    #EDB54B "0xed 0xb5 0x4b"
            task=$'\e[38;2;89;156;170m';      #599caa "0x59 0x9c 0xaa"
            customColors=( "0x19 0x54 0x65" "0xd2 0x69 0x39" "0x26 0xa9 0x8b" \
            "0xed 0xb5 0x4b" "0x59 0x9c 0xaa" )
        ;;
        gruvbox)
            # Using RGB colors for array 'customColors'
            bg="#32302f"
            nc=$'\e[38;2;69;133;136m';        #458588 "0x45 0x85 0x88"
            critical=$'\e[38;2;204;36;29m';   #CC241D "0xcc 0x24 0x1d"
            info=$'\e[38;2;104;157;106m';     #689d6a "0x68 0x9d 0x6a"
            mtitle=$'\e[38;2;215;153;33m';    #D79921 "0xd7 0x99 0x21"
            task=$'\e[38;2;235;219;178m';     #ebdbb2 "0xeb 0xdb 0xb2"
            # enter the last three numbers of your custom sequence.
                        #   normal text  critical      info          mtitle       task
            customColors=( "69;133;136" "204;36;29" "104;157;106" "215;153;33" "235;219;178" )
        ;;
        jellybeans)
            # Using HEX colors for array 'customColors'
            bg="#121212"
            nc=$'\e[38;2;89;123;197m';        #597bc5 "0x59 0x7b 0xc5"
            critical=$'\e[38;2;207;106;76m';  #cf6a4c "0xcf 0x6a 0x4c"
            info=$'\e[38;2;153;173;106m';     #99ad6a "0x99 0xad 0x6a"
            mtitle=$'\e[38;2;216;173;76m';    #d8ad4c "0xd8 0xad 0x4c"
            task=$'\e[38;2;113;185;248m';     #a9a9a9 "0xa9 0xa9 0xa9"
            customColors=( "0x59 0x7b 0xc5" "0xcf 0x6a 0x4c" "0x99 0xad 0x6a" \
            "0xd8 0xad 0x4c" "0xa9 0xa9 0xa9" )
        ;;
        monokai)
            # Using RGB colors for array 'customColors'
            bg="#2e2e2e"
            nc=$'\e[38;2;102;217;239m';       #66d9ef "0x66 0xd9 0xef"
            critical=$'\e[38;2;249;38;114m';  #F92672 "0xf9 0x26 0x72"
            info=$'\e[38;2;166;226;46m';      #A6E22E "0xa6 0xe2 0x2e"
            mtitle=$'\e[38;2;244;191;171m';   #F4BF75 "0xf4 0xbf 0x75"
            task=$'\e[38;2;248;248;242m';     #F8F8F2 "0xf8 0xf8 0xf2"
            # enter the last three numbers of your custom sequence.
                        #   normal text   critical      info          mtitle       task
            customColors=( "102;217;239" "249;38;114" "166;226;46" "244;191;171" "248;248;242" )
        ;;
        nord)
            # Using RGB colors for array 'customColors'
            bg="#2e3440"
            nc=$'\e[38;2;129;161;193m';       #81a1c1 "0x81 0xa1 0xc1"
            critical=$'\e[38;2;191;97;106m';  #bf616a "0xbf 0x61 0x6a"
            info=$'\e[38;2;163;190;140m';     #a3be8c "0xa3 0xbe 0x8c"
            mtitle=$'\e[38;2;235;203;139m';   #ebcb8b "0xeb 0xcb 0x8b"
            task=$'\e[38;2;136;192;208m';     #88c0d0 "0x88 0xc0 0xd0"
            # enter the last three numbers of your custom sequence.
                        #   normal text   critical      info          mtitle       task
            customColors=( "129;161;193" "191;97;106" "163;190;140" "235;203;139" "136;192;208" )
        ;;
        pistachio)
            bg="#201b1e"
            nc=$'\e[38;2;146;196;113m';       #92C471 "0x92 0xc4 0x71"
            critical=$'\e[38;2;215;95;65m';   #D75F41 "0xd7 0x5f 0x41"
            info=$'\e[38;2;146;196;113m';     #92C471 "0x92 0xc4 0x71"
            mtitle=$'\e[38;2;242;203;87m';    #F2CB57 "0xf2 0xcb 0x57"
            task=$'\e[38;2;249;230;176m';     #F9E6B0 "0xf9 0xe6 0xb0"
            customColors=( "0x92 0xc4 0x71" "0xd7 0x5f 0x41" "0x92 0xc4 0x71" \
            "0xf2 0xcb 0x57" "0xf9 0xe6 0xb0" )
        ;;
        solarized)
            bg="#002b36"
            nc=$'\e[38;2;131;148;150m';       #839496 "0x83 0x94 0x96"
            critical=$'\e[38;2;220;50;47m';   #DC322F "0xdc 0x32 0x2f"
            info=$'\e[38;2;133;153;0m';       #859900 "0x85 0x99 0x00"
            mtitle=$'\e[38;2;181;137;0m';     #B58900 "0xb5 0x89 0x00"
            task=$'\e[38;2;42;161;152m';      #2AA198 "0x2a 0xa1 0x98"
            customColors=( "0x83 0x94 0x96" "0xdc 0x32 0x2f" "0x85 0x99 0x00" \
            "0xb5 0x89 0x00" "0x2a 0xa1 0x98" )
        ;;
        TokyoNight)
            bg="#1f2335"
            nc=$'\e[38;2;169;177;214m';       #A9B1D6 "0xa9 0xb1 0xd6"
            critical=$'\e[38;2;247;118;142m'; #F7768E "0xf7 0x76 0x8e"
            info=$'\e[38;2;158;206;106m';     #9ECE6A "0x9e 0xce 0x6a"
            mtitle=$'\e[38;2;224;175;104m';   #E0AF68 "0xe0 0xaf 0x68"
            task=$'\e[38;2;125;207;255m';     #7DCFFF "0x7d 0xcf 0xff"
            customColors=( "0xa9 0xb1 0xd6" "0xf7 0x76 0x8e" "0x9e 0xce 0x6a" \
            "0xe0 0xaf 0x68" "0x7d 0xcf 0xff" )
        ;;
        vacuous)
            bg="$default_bg"
            nc=$'\e[38;2;116;145;161m';       #7491A1 "0x74 0x91 0xa1"
            critical=$'\e[38;2;209;69;72m';   #D14548 "0xd1 0x45 0x48"
            info=$'\e[38;2;167;183;154m';     #A7B79A "0xa7 0xb7 0x9a"
            mtitle=$'\e[38;2;249;187;128m';   #F9BB80 "0xf9 0xbb 0x80"
            task=$'\e[38;2;15;130;157m';      #0F829D "0x0f 0x82 0x9d"
            customColors=( "0x74 0x91 0xa1" "0xd1 0x45 0x48" "0xa7 0xb7 0x9a" \
            "0xf9 0xbb 0x80" "0x0f 0x82 0x9d" )
        ;;
        zenburn)
            bg="#1f1f1f"
            nc=$'\e[38;2;220;220;204m';       #DCDCCC "0xdc 0xdc 0xcc"
            critical=$'\e[38;2;198;92;92m';   #C65C5C "0xc6 0x5c 0x5c"
            info=$'\e[38;2;96;180;138m';      #60B48A "0x60 0xb4 0x8a"
            mtitle=$'\e[38;2;240;223;175m';   #F0DFAF "0xf0 0xdf 0xaf"
            task=$'\e[38;2;79;122;167m';      #4F7AA7 "0x4f 0x7a 0xa7"
            customColors=( "0xdc 0xdc 0xcc" "0xc6 0x5c 0x5c" "0x60 0xb4 0x8a" \
            "0xf0 0xdf 0xaf" "0x4f 0x7a 0xa7" )
        ;;
    esac

}
