#!/bin/bash
## This is a part of main script: mpm.

_CheckCode() {

    __NestedCheckCode() (
        __
        echo -e " ${g}Verifying media codes from selected file...be patient.${nc}\n"
        # mapfile in addition of a for loop is faster
        # than using while <condition>; do <command_2> done < <(command_1)
        mapfile -t CHECKCODE < <(grep '^https' "$M3UFILE")
        for lines in "${CHECKCODE[@]}"; do
            # checking the last url we added.
            youtube-dl -F --no-warnings $(sed -n '$ p' "$M3UFILE") >"$YTOP"
            if [[ $? -eq 1 ]]; then
                echo -e " ${r}No format code found!\n $lines removed${nc}"
                echo -e " Please visit: https://github.com/ytdl-org/youtube-dl/blob/master/docs/supportedsites.md${nc}\n"
                sed -i '$ d' "$M3UFILE"
                sleep 5
                if (( $(grep -c '^https' "$M3UFILE" ) == 0 )); then
                    _Menu
                else
                    continue
                fi
            fi
            echo " $lines ${g}ok${nc}" | tee -a "$tmp_dir"/CheckCode.txt
            sleep 1
        done
    )

    case "$1" in
        -a) M3UFILE="$AUDIO_INFO"
            __NestedCheckCode ;;
        -v) M3UFILE="$VIDEO_INFO"
            __NestedCheckCode ;;
        -l) M3UFILE="$list"
            __NestedCheckCode ;;
        -q) M3UFILE="$QUEUE"
            __NestedCheckCode ;;
    esac

}
