#!/bin/bash
## This is a part of main script: mpm.

_CheckDependencies() {
    ## softwares, directories and files.
    declare -a deps=( "ffmpeg" "jq" "mpv" "youtube-dl" "yt-dlp" )
    
    for item in "${deps[@]}"; do
        [[ -z $(command -v "$item") ]] && {
            echo " ${red}$item isn 't installed, bye..."
            exit 127
        }
    done
    
    for optional in ranger wmctrl; do
        [[ -z $(command -v "$optional") ]] && {
            echo " ${green}For better experience consider installing $optional.${nocolor}"
            sleep 3
        }
    done
    
    if [[ ! -d $main_dir ]]; then
        mkdir --parents {"$audios_dir","$playlists_dir","$tmp_dir","$videos_dir"}
    else
        [[ ! -d $audios_dir ]] && mkdir "$audios_dir"
        [[ ! -d $playlists_dir ]] && mkdir "$playlists_dir"
        [[ ! -d $tmp_dir ]] && mkdir "$tmp_dir"
        [[ ! -d $videos_dir ]] && mkdir "$videos_dir"
    fi
    
    [[ ! -f $QUEUE ]] && echo "#EXTM3U" > "$QUEUE"
    
    _Menu

}
