#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2076,SC2034
_CheckParallelDownloads() {
    clear

    [[ $use_parallel_downloads == yes ]] && {

        [[ $(grep -c -v '^https://www.youtube.com' "$M3UFILE") -gt 1 ]] && {
            __
            printf '%s\n' \
            " ${critical}There is at least two or more none Youtube links in ${M3UFILE##*/}" \
            " and use_parallel_downloads is set to ${task}'yes'." \
            " ${critical}Some platforms do not support this feature..." \
            " ${info}(answering NO will download files one by one)."
            __
            _Prompt -n " Continue with parallel downloads?${nc}" || {
                use_parallel_downloads="no"
            }
        }
    }
}
