#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2076,SC2034
_CheckParallelDownloads() {
    clear;__

    [[ $use_parallel_downloads = yes ]] && {

        while read -r line; do
            if [[ $line =~ 'youtube.com' ]]; then
                continue
            else
                echo "$line" >> "$tmp_dir"/none_youtube
            fi
        done < <(grep '^https' "$M3UFILE")

        unset line

        [[ $(grep "" -c "$tmp_dir"/none_youtube) -gt 1 ]] && {
            rm "$tmp_dir"/none_youtube
            printf '%s\n' \
            " ${critical}There is at least two or more none Youtube links in ${M3UFILE##*/}" \
            " and use_parallel_downloads is set to ${task}'yes'." \
            " ${critical}Some platforms do not support this feature..." \
            " ${info}(answering NO will download files one by one)."
            _Prompt -n " Continue with parallel downloads?${nc}" || {
                use_parallel_downloads="no"
            }
        }
    }
}