#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2076,SC2154,SC2034,SC2015
_ChooseDirectVideoDownload() {

    local counter animationTitles
    clear
    cd "$playlists_dir" || exit 1
    _TitlesListCompare -l
    _GetRange

    clear
    cp -f "$list" "$list"_origin
    cp -f "$SELECTED_TITLES" "$SELECTED_TITLES"_orgin
    mkdir --parents "$mediaDir" && cd "$mediaDir"|| {
        printf '%s\n' \
        " ${critical}Failed to access ${mediaDir##*/} directory.${nc}"
        sleep 4
        _Menu
    }

    M3UFILE="$SELECTED_URLS1"
    counter=$(grep "" -c "$SELECTED_URLS1")
    animationTitles="$SELECTED_TITLES"

    if _TestParallelCommand; then
        _ParallelDownloadCmd --choose-video
        _DownloadMessages --choose-video
        _ParallelAnimation
    elif _TestXargsCommand; then
        _DownloadMessages --choose-video
        _ParallelAnimation &
        _ParallelXargsCmd --choose-video
    else
        while read -r url; do
            _DownloadMessages --choose-video
            if [[ $url =~ 'youtube.com' ]]; then
                yt-dlp --output "$(_GetLinkTitle -s).%(ext)s" \
                "${ytdlPreset_X[@]}" "$url"
            else
                yt-dlp --output "$(_GetLinkTitle -s).%(ext)s" \
                "${ytdlPreset_NC[@]}" "$url"
            fi

            sed -i '1d' "$SELECTED_TITLES"
            ((counter--))
            clear
        done < "$SELECTED_URLS1"
    fi

    unset url
    _RemoveAudioVideoIds
    _UpdateSelected -u
    echo " ${info}All done${nc}"
    sleep 2
    clear
    _DownloadCompleted

}
