#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2076,SC2154,SC2164
_ChooseDirectVideoDownload() {

    local counter
    clear
    cd "$playlists_dir" || exit 1
    _TitlesListCompare -l
    _GetRange
    
    clear
    cp -f "$list" "$list"_origin
    cp -f "$SELECTEDTITLES" "$SELECTEDTITLES"_orgin
    mkdir --parents "$videos_dir"/"${list%.*}" \
    && cd "$videos_dir"/"${list%.*}"
    
    readarray -t DIRECT < "$CHOOSE1"
    counter="${#DIRECT[@]}"
    
    for line in "${DIRECT[@]}"; do

        if [[ $direct_download = yes ]]; then
            printf '%s\n' " ${task}Direct download enabled.${nc}"
        else
            printf '%s\n' " ${task}Download method = direct.${nc}"
        fi
        __
        printf '%s\n' " ${info}$counter file(s) left to downloads." \
        " Downloading: $(_GetLinkTitle -s)${nc}"

        if [[ $line =~ 'youtube.com' && $(_GetLinkTitle -s) =~ '/' ]]; then
            # downloader presets described in ~/.config/mpm/mpmrc
            youtube-dl "${ytdlPreset_FS[@]}" \
            "${ytdlPreset_X[@]}" "$line"
        elif [[ $line =~ 'youtube.com' ]]; then
            youtube-dl \
            --output "$(_GetLinkTitle -s).%(ext)s" \
            "${ytdlPreset_X[@]}" "$line"
        else
            youtube-dl \
            --output "$(_GetLinkTitle -s).%(ext)s" \
            "${ytdlPreset_NC[@]}" "$line"
        fi

        sed -i '1d' "$SELECTEDTITLES"
        ((counter--))
        clear
    done

    unset IFS
    echo " ${info}All done${nc}"
    sleep 2

}