#!/bin/bash
## This is a part of main script: mpm.

# shellcheck source=/dev/null
# shellcheck disable=SC2154
_ChooseTheme() {

    clear
    _BlankLine
    read -rsn 1 \
    -p " ${info}Change [M]ain or [N]ative player theme, [${mtitle}C${info}]ancel: ${nc}" change

    case "$change" in
        m|M)
            clear
            echo -e "\n ${info}Current main theme: ${task}$THEME${nc}\n"
            sed -i "s/THEME=\"${THEME}\"/THEME=${THEME}/" "$MPMRC"
            PS3=""$'\n'" ${info}Please choose a theme, [${mtitle}C${info}]ancel: ${nc}"
            select main in "${mainThemes[@]}"; do
                [[ $REPLY =~ [a-zA-Z] ]] && {
                    printf '\n%s\n' " ${critical}Selection aborted...${nc}"
                    sleep 2
                    break
                }
                sed -i "s/THEME=${THEME}/THEME=${main}/" "$MPMRC"
                . "$MPMRC"
                _Theme "$main"
                break
            done
        ;;
        n|N)
            clear
            local ntc="$native_tui_colors"
            echo -e "\n ${info}Current native player theme: ${task}$ntc${nc}\n"
            sed -i "s/native_tui_colors=\"${ntc}\"/native_tui_colors=${ntc}/" "$MPMRC"
            PS3=""$'\n'" ${info}Please choose a theme, [${mtitle}C${info}]ancel: ${nc}"
            select native in "${nativeThemes[@]}"; do
                [[ $REPLY =~ [a-zA-Z] ]] && {
                    printf '\n%s\n' " ${critical}Selection aborted...${nc}"
                    sleep 2
                    break
                }
                sed -i "s/native_tui_colors=${ntc}/native_tui_colors=${native}/" "$MPMRC"
                . "$MPMRC"
                break
            done
        ;;
        *) _Menu ;;
    esac

}
