#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ChooseFromPlay() {
    
    clear
    _TitlesListCompare -l

    read -rsn 1 \
    -p " ${info}[${mtitle}C${info}]ancel, Play all items as [A]udio, [V]ideo or ${b}[S]elect:${nb} ${nc}" \
    chooseFromPlayOptions

    case "$chooseFromPlayOptions" in
        a|A) _LoadAudioVideo -la ;;
        c|C) _LoadPlaylistMenu ;;
        v|V) _LoadAudioVideo -lv ;;
        s|S)
            __
            rm "$SELECTED_URLS1" 2>/dev/null
            _GetRange
            rm "$SELECTED_TITLES" 2>/dev/null
            [[ $range =~ [a-zA-Z] ]] && _LoadPlaylistMenu
            __
            read -rsn 1 -p "${info}"' load [A]udio, [V]ideo: '"${nc}" load
            case "$load" in
                a|A) _LoadAudioVideo -sa ;;
                v|V)
                    clear
                    _LoadAudioVideo -sv
                ;;
                *)
                    _WrongOption "$load"
                    _LoadPlaylistMenu
                ;;
            esac
        ;;
        *)
            _WrongOption "$chooseFromPlayOptions"
            _LoadPlaylistMenu
        ;;
    esac
    _Menu
}
