#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2013,SC2154,SC2143,SC2076,SC2164
_ChooseDownloadAudio() {

    local counter
    cd "$playlists_dir" || exit 1
    clear
    _TitlesListCompare
    _GetRange

    clear
    cp -f "$list" "$list"_origin
    mkdir --parents "$audios_dir"/"${list%.*}" \
    && cd "$audios_dir"/"${list%.*}"
    
    readarray -t SELECTEDAUDIO < "$CHOOSE1"
    counter="${#SELECTEDAUDIO[@]}"
    
    __ChooseDownloadAudioMessage() (
        printf '%s\n' " ${info}$counter file(s) left to downloads." \
        " Downloading: $(_GetLinkTitle -s)${nc}"
    )
    
    for url in "${SELECTEDAUDIO[@]}"; do

        if [[ $direct_download = yes ]] && \
            [[ $(youtube-dl -F "${ytdlPreset_DW[@]}" "$url" \
            | grep '^251') ]]; then

            printf '%s\n' " ${task}Direct download enabled.${nc}"
            __
            __ChooseDownloadAudioMessage
            youtube-dl --output "$(_GetLinkTitle -s).%(ext)s" \
            --format 251 "${ytdlPreset_NC[@]}" "$url"

        elif [[ $direct_download = no ]] && [[ $url =~ 'youtube.com' ]]; then
            __
            printf '%s\n' " ${task}Direct download disabled.${nc}"
            __
            youtube-dl -F "${ytdlPreset_DW[@]}" "$url" \
            | awk '/audio only|PROTO|^[-]/ {sub("^[sb*]",""); print $0}'
            __
            printf '%s\n' " ${info}Choose a format code for: $(_GetLinkTitle -s)${nc}"
            read -r code
            clear
            __
            __ChooseDownloadAudioMessage
            
            youtube-dl --output "$(_GetLinkTitle -s).%(ext)s" \
            --format "$code" "${ytdlPreset_NC[@]}" "$url"

        else

            youtube-dl -F "${ytdlPreset_DW[@]}" "$url"
            printf '%s\n' " ${info}Choose a format code for: $(_GetLinkTitle -s)${nc}"
            read -r code
            clear
            __
            __ChooseDownloadAudioMessage
            sleep 0.5
            youtube-dl --output "$(_GetLinkTitle -s).%(ext)s" \
            --format "$code" "${ytdlPreset_NC[@]}" "$url"

        fi

        sed -i '1d' "$SELECTEDTITLES"
        ((counter--))
        clear

    done

    _UpdateSelected

    # if we don't unset IFS other functions will be messed up!
    unset IFS

    clear
    echo -e " ${info}Done${nc}\n"
    clear

    if [[ -n $(find "$audios_dir"/"${list%.*}" -iname "*.webm") ]]; then
        echo " ${critical}ADVISORY: if you choose conversion, all downloaded webm"
        echo -e " files will be converted in the chosen format.${nc}\n"
        find "$audios_dir"/"${list%.*}" -iname "*.webm" | sed 's,.*/,,' | sort | cat -n

        if [[ $automatic_audio_conversion = yes ]]; then
            __
            printf '%s\n' " ${task}Automatic audio conversion enabled.${nc}"
            sleep 2
            _ConvertAudio && _DownloadCompleted
        else
            __
            _Prompt " ${info}Proceed with conversion?: ${nc}" || {
                _DownloadCompleted
            }
            _ConvertAudio && _DownloadCompleted
        fi

    else
        _DownloadCompleted
    fi

}
