#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2076,SC2154,SC2164
_ChooseDirectVideoDownload() {

    local counter
    clear
    cd "$playlists_dir" || exit 1
    _TitlesListCompare -l
    _GetRange
    
    clear
    cp -f "$list" "$list"_origin
    cp -f "$SELECTEDTITLES" "$SELECTEDTITLES"_orgin
    mkdir --parents "$videos_dir"/"${list%.*}" \
    && cd "$videos_dir"/"${list%.*}"
    
    counter=$(grep "" -c "$CHOOSE1")
    
    while read -r url; do
        [[ $direct_download = yes ]] && \
            printf '%s\n' " ${task}Direct download enabled.${nc}" || \
            printf '%s\n' " ${task}Download method = direct.${nc}"
        __
        printf '%s\n' " ${info}$counter file(s) left to downloads." \
        " Downloading: $(_GetLinkTitle -s)${nc}"

        if [[ $url =~ 'youtube.com' && $(_GetLinkTitle -s) =~ '/' ]]; then
            # downloader presets described in ~/.config/mpm/mpmrc
            youtube-dl "${ytdlPreset_BF[@]}" "${ytdlPreset_X[@]}" "$url"
        elif [[ $url =~ 'youtube.com' ]]; then
            youtube-dl --output "$(_GetLinkTitle -s).%(ext)s" \
            "${ytdlPreset_X[@]}" "$url"
        else
            youtube-dl --output "$(_GetLinkTitle -s).%(ext)s" \
            "${ytdlPreset_NC[@]}" "$url"
        fi

        sed -i '1d' "$SELECTEDTITLES"
        ((counter--))
        clear
    done < "$CHOOSE1"

    unset url
    echo " ${info}All done${nc}"
    sleep 2

}