#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ChooseFromPlay() {
    
    clear
    _TitlesListCompare -l

    read -rsn 1 \
    -p "${info}"" [${mtitle}C${info}]ancel, Play all items as [A]udio, [V]ideo or ${b}[S]elect:${nb} ""${nc}" choice
    
    case "$choice" in
        a|A) _LoadAudioVideo -la ;;
        c|C) _LoadPlaylistMenu ;;
        v|V) _LoadAudioVideo -lv ;;
        s|S)
            __
            [[ -f $CHOOSE1 ]] && rm "$CHOOSE1"
            _GetRange
            rm "$SELECTEDTITLES" 2>/dev/null
            [[ $range =~ [a-zA-Z] ]] && _LoadPlaylistMenu
            __
            read -rsn 1 -p "${info}"' load [A]udio, [V]ideo: '"${nc}" load
            case "$load" in
                a|A) _LoadAudioVideo -ca ;;
                v|V)
                    clear
                    _LoadAudioVideo -cv
                ;;
                *)
                    _WrongOption "$load"
                    _LoadPlaylistMenu
                ;;
            esac
        ;;
        *)
            _WrongOption "$choice"
            _LoadPlaylistMenu
        ;;
    esac
    _Menu
}
