#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2013,SC2076,SC2154
_ChooseDownloadVideo() {

    cd "$playlists_dir" || exit 1
    clear
    _TitlesListCompare

    cp -f "$list" "$list"_origin 2>/dev/null
    mkdir -p "$videos_dir"/"${list%.*}"

    IFS=","; read -ra array \
    -p " ${info}Enter links numbers separeted by comma, eg: 3,1,5: ${nc}"

    clear

    local chooseVideoCounter="${#array[*]}"

    if [[ $direct_download = yes ]]; then
        _ChooseDirectVideoDownload
    else
        __
        printf '%s\n' " ${info}Tip: direct download will always pick the best format," \
        " on Youtube webm may be the best one but we'll merge files in mp4." \
        " Choose [S]pecific codes or [D]irect download?:\n${nc}"
        sleep 0.5 && read -rsn 1 choice
    fi

    case "$choice" in
        d|D)
            _ChooseDirectVideoDownload
        ;;
        s|S)
            _GetSelected
            cd "$videos_dir"/"${list%.*}" || exit 1
            
            mapfile -t < <(grep '^https' "$CHOOSE1")
            
            for url in "${MAPFILE[@]}"; do

                if [[ $url =~ 'youtube.com' ]]; then
                    __
                    youtube-dl -F --no-warnings "$url" \
                    | sed '1,5d;/^[sb]/d;/^\s*$/d;s/-//g;/^\s*$/d'
                else
                    youtube-dl -F --no-warnings "$url"
                fi
                
                __
                printf '%s\n' " ${info}Choose a format code." \
                " eg: 137+251 for merging, hls-1080p, 22 for single:${nc}"
                read -r code
                sleep 0.5
                clear
                printf '%s\n' " ${info}Total downloads: $chooseVideoCounter${nc}"
                
                if [[ $code =~ '+' ]]; then
                    youtube-dl -f "$code" \
                    --no-warnings \
                    --merge-output-format mp4 \
                    --progress "$url"
                else
                    youtube-dl -f "$code" \
                    --no-warnings --progress "$url"
                fi
                
                ((chooseVideoCounter--))
                clear
            
            done
       
            echo " ${info}All done${nc}"
            sleep 2
        ;;
    esac

    _UpdateSelected

    # if we don't unset IFS other functions will be messed up!
    unset IFS

    clear
    _DownloadCompleted

}
