#!/bin/bash
## This is a part of main script: mpm.

_ChooseFromPlay() {
    cd "$playlists_dir"

    _TitlesListCompare

    [[ -f $CHOOSE1 ]] && rm "$CHOOSE1"

    read -sn 1 -p ${g}" Play all items as [A]udio, [V]ideo or ${b}[S]elect:${nb} "${nc} choice
    case "$choice" in
        a|A)
            _LoadAudio -l
        ;;
        v|V)
            _LoadVideo -l
        ;;
        s|S)
            __
            IFS=","; read -a array -p ${g}" Enter links separeted by comma, eg: 3,1,5: "${nc}

            for i in "${array[@]}"; do
                let "i++"
                sed -n "${i}p" "$list" >> "$CHOOSE1"
            done

            # if we don't unset IFS all other functions will be messed up!
            unset IFS
            __
            read -rsn 1 -p ${g}' load [A]udio, [V]ideo: '${nc} load
            case "$load" in
                a|A)
                    _LoadAudio -c
                ;;
                v|V)
                    clear
                    _LoadVideo -c
                ;;
            esac
            _Menu
        ;;
    esac
    _Menu
}
