#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ClearAllTmpLists() {

    cd "$tmp_dir" || exit 1

    declare -a tmps=(
        "$DEFAULT_TITLES" "1"
        "$AUDIO_URLS" "$AUDIO_TITLES"
        "$VIDEO_URLS" "$VIDEO_TITLES"
    )

    declare -a fileExists=()

    for tmp in "${tmps[@]}"; do
        [[ -f $tmp ]] && fileExists+=("$tmp")
    done

    ((${#fileExists[@]} > 0)) && {
        _Prompt -n " ${critical}Clear all temporary playlists? ${nc}" && {
            rm "${fileExists[@]}"
            echo "#EXTM3U" > "$DEFAULT_LIST"
            unset file tmp
            printf '\n%s\n' \
                " ${critical}All Temporary lists cleared.${nc}"
            sleep 2
            return
        }
        return
    }

    printf '%s\n' " ${critical}No temporary file found${nc}"
    sleep 2

}
