#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
# This function is called multiple times across this program,
# but let's ensure temporary files are removed before we exit out. 
_CleanTmpDir() {
    [[ -s "$DEFAULTITLES" ]] && {
    if [[ $(_GetLinesList -q) -eq $(grep "" -c "$DEFAULTITLES") ]] ; then
        cp -f "$DEFAULTITLES" "$DEFAULTM3UTITLES"
    else
        printf '%s\n' " ${task}${b}Updating Default list titles...${nb}${nc}"
        sleep 1
        _GetMediaTitle -q > "$DEFAULTM3UTITLES"
    fi
    }
    rm -f \
    {"$tmp_dir"/*,"$playlists_dir"/{1_Back_to_menu,*_tmp}} 2>/dev/null
}
