#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
# This function is called multiple times across this program,
# but let's ensure temporary files are removed before we exit out. 
_CleanTmpDir() {
    if [[ $(_GetLinesList -q) -gt 0 ]]; then
        cp "$DEFAULTITLES" "$DEFAULTM3UTITLES"
    else
        rm -f "$DEFAULTM3UTITLES" 2>/dev/null
    fi
    rm -f {"$tmp_dir"/*,"$playlists_dir"/{1_Back_to_menu,*_tmp}} 2>/dev/null
}
