#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ConvertAudio_ogg() {
    mapfile -t webmFiles < <(find "$audios_dir" -maxdepth 2 -iname "*.webm")
    for o in "${webmFiles[@]}"; do
        ffmpeg -i "${o}" \
        "${ffmpegOggCodecOptions[@]}" \
        -y "${o%.webm}.ogg" 2>"$FFOP"
    done
}
