#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ConvertAudio_flac() {
    mapfile -t webmFiles < <(find "$audios_dir" -maxdepth 2 -iname "*.webm")
    for f in "${webmFiles[@]}"; do
        ffmpeg -i "${f}" \
        "${ffmpegFlacCodecOptions[@]}" \
        -y "${f%.webm}.flac" 2>"$FFOP"
    done
}