#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ConvertAudio_mp3() {
    for m in "${webmFiles[@]}"; do
        ffmpeg -i "${m}" \
        "${ffmpegMp3CodecOptions[@]}" \
        -y "${m%.webm}.mp3" 2>"$FFOP"
    done
}
