#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ConvertAudio_ogg() {
    for o in "${webmFiles[@]}"; do
        ffmpeg -i "${o}" \
        "${ffmpegOggCodecOptions[@]}" \
        -y "${o%.webm}.ogg" 2>"$FFOP"
    done
}