#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ConvertAudio_aac() {
    for a in "${webmFiles[@]}"; do
        ffmpeg -i "${a}" \
        "${ffmpegAacCodecOptions[@]}" \
        -y "${a%.webm}.aac" 2>"$FFOP"
    done
}
