#!/bin/bash
## This is a part of main script: mpm.

_ConvertAudio() {

    cd "$audios_dir" || exit 1

    __mp3() (
        echo " ${g}Converting files in ${c}${b}mp3${nb}${nc}...${nc}"
        find . -iname "*.webm" -exec \
        bash -c 'FILE="$1"; \
            ffmpeg -i "${FILE}" \
            -vn -ab 320k -ar 48000 \
            -y "${FILE%.webm}.mp3";' _ '{}' \; 2>"$FFOP"
    )

    __flac() (
        echo " ${g}Converting files in ${c}${b}flac${nb}${nc}...${nc}"
            find . -iname "*.webm" -exec \
            bash -c 'FILE="$1"; \
                ffmpeg -i "${FILE}" \
                -af aformat=s32:48000 \
                -y "${FILE%.webm}.flac";' _ '{}' \; 2>"$FFOP"
    )

    __wav() (
        echo " ${g}Converting files in ${c}${b}wav${nb}${nc}...${nc}"
            find . -iname "*.webm" -exec \
            bash -c 'FILE="$1"; \
                ffmpeg -i "${FILE}" \
                -acodec pcm_s32le -ar 48000 \
                -y "${FILE%.webm}.wav";' _ '{}' \; 2>"$FFOP"
    )

    __ogg() (
        echo " ${g}Converting files in ${c}${b}ogg${nb}${nc}...${nc}"
            find . -iname "*.webm" -exec \
            bash -c 'FILE="$1"; \
                ffmpeg -i "${FILE}" \
                -acodec libvorbis -ar 48000 -ab 320k \
                -y "${FILE%.webm}.ogg";' _ '{}' \; 2>"$FFOP"
    )

    __FormatSelection() {
        read -rn1 -p "${g}"' Select an output format [1 = mp3] [2 = flac] [3 = wav] [4 = ogg]: '"${nc}" conv
        __
        case "$conv" in
            1)
                __mp3 ;;
            2)
                __flac ;;
            3)
                __wav ;;
            4)
                __ogg ;;
            *)
                echo " ${r}UNKNOWN FORMAT !!! Try again.${nc}"
                sleep 3s
                clear
                _Menu
            ;;
        esac
    }

    declare -a FORMATS=( "flac" "mp3" "ogg" "wav" )

    [[ -z $default_conversion_format ]] && {
        printf '%s\n' " ${c}Default format is empty.${nc}"
        __
        __FormatSelection
    }

    # testing if format is set and if it is part of array FORMATS
    # if so we use it for conversion.
    [[ -n $default_conversion_format ]] && \
    [[ $(echo "${FORMATS[@]}") =~ $default_conversion_format ]] && {
        __
        printf '%s\n' " ${c}Default format set to $default_conversion_format.${nc}"
        __
        __"$default_conversion_format"
    } || printf '%s\n' " ${r}Format $default_conversion_format not supported.${nc}" \
        && __ \
        && __FormatSelection

    rm ./*.webm
    echo " ${g}Conversion done.${nc}"
    sleep 2

}
