#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ConvertAudio_flac() {
    for f in "${webmFiles[@]}"; do
        ffmpeg -hide_banner -loglevel quiet -i "${f}" \
        "${ffmpegFlacCodecOptions[@]}" \
        -y "${f%.webm}.flac" 2>"$FFOP"
    done
}