#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_CopyMediaUrl() {

    local mediaUrl clipUrls urlTest
    clipUrls="$tmp_dir/clipboardUrls.txt"
    urlTest="$tmp_dir/urltest"

    rm {"$urlTest","$clipUrls"} 2>/dev/null
    # to start, the clipboard must be cleared
    echo -n | xclip -selection primary || wl-copy --clear

    # Get URL from clipboard or user input
    if __clipboardCmdTest; then
        _UrlsCollector
    else
        echo -e "\n Paste an url to fill the ${info}${Type}${nc} playlist:\n"
        read -r mediaUrl
        echo "$mediaUrl" >> "$clipUrls"
    fi

    _AnalyzeUrls
    _RemoveCrap
    _IfDuplicatesUrls
    _IfDuplicatesFiles
    _CreateAddPlaylist "$arg"

}
