#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_CopyAudio() {

    [[ -f $tmp_dir/1 ]] && rm "$tmp_dir"/1

    while (( $(grep "" -c "$QUEUE") > 0 )); do
        __CopyAudioLinks() {
            __
            echo -e " Paste an url to fill the ${info}audio${nc} playlist:\n"
            read -r audiourl

            if [[ $audiourl =~ 'playlist?list=' ]]; then
                __
                AudioPlaylistTitle=$(youtube-dl -J --flat-playlist "$audiourl" | jq -r .title)
                printf '%s\n' " ${info}Getting titles & links from playlist: $AudioPlaylistTitle..." \
                "${b} Please be patient.${nb}${nc}"
                youtube-dl --get-title --no-warnings "$audiourl" >> "$AUDIO_TITLE"
                _GetYoutubePlaylistUrls -a
                _RemoveCrap
            else
                echo "$audiourl" >> "$AUDIO_INFO"
                __
                echo " ${info}Testing url...${nc}"
                _RemoveCrap
                audiourl=$(sed -n '$p' "$AUDIO_INFO")
                youtube-dl -F --no-warnings "$audiourl" > "$YTOP"
                if [[ $? -eq 1 ]]; then
                    __
                    echo -e " ${critical}${b}No format code found!${nb}\n$audiourl will be removed."
                    echo " ${info}Please visit: $supportedsites${nc}"
                    sed -i '$d' "$AUDIO_INFO"
                    _RemoveCrap
                    sleep 7
                    [[ $(_GetLinesList -a) -eq 0 ]] && _Menu
                else
                    sed -n '$p' "$AUDIO_INFO" >> "$QUEUE"
                    echo -e " ${info}Getting audio title...${nc}\n"
                    youtube-dl --get-title --no-warnings \
                    "$audiourl" >> "$AUDIO_TITLE"
                    _RemoveCrap
                fi
            fi
        }

        while (( $(grep "" -c "$QUEUE") > 0 )); do
            _ResizeWindow
            clear
            __
            [[ -f $AUDIO_INFO ]] && (($(_GetLinesList -a) > 0)) && \
            echo " ${info}Audio list:   $(_GetLinesList -a) url(s)${nc}"
            __
            echo -e "                                                    ${mtitle}::audio options::${nc}"
            echo -e "                              ┌─────────────────────────────────────────────────────────────┐"
            echo -e "                              │     1) Add audio links            4) Play current list      │"
            echo -e "                              │     2) Download current list      5) View current list      │"
            echo -e "                              │     3) Save playlist as           6) Back to main menu      │"
            echo -e "                              └─────────────────────────────────────────────────────────────┘"
            echo -e "                                                     ${info}${b}Select an item${nb}${nc}"
            __
            read -rsn 1 options
            case "$options" in
                1)  __CopyAudioLinks
                    __ ;;
                2)  _AudioDownload -a
                    __ ;;
                3)  _Save -a
                    __ ;;
                4)  _LoadAudio -a
                    __ ;;
                5)  _ViewUrlInfo -a
                    __ ;;
                6)  _Menu
                    __ ;;
            esac
        done


    done
}
