#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015,SC2034
_CreateAddPlaylist() {

    local Type TITLES URLS menuTitleType arg mediaUrl supportedSites file
    supportedSites="https://github.com/ytdl-org/yt-dlp/blob/master/docs/supportedsites.md"
    
    case "$1" in
        -a)
            Type=Audio
            TITLES="$AUDIO_TITLES"
            URLS="$AUDIO_URLS"
            menuTitleType=AUDIO
            arg="-a"
        ;;
        -v)
            Type=Video
            TITLES="$VIDEO_TITLES"
            URLS="$VIDEO_URLS"
            menuTitleType=VIDEO
            arg="-v"
        ;;
    esac

    file="${URLS##*/}" file="${file%%.*}"

    __clipboardCmdTest() {
        [[ -n $(command -v "${clipboardCmd[0]}") && -n "${clipboardCmd[*]}" ]]
    }

    while true; do
        _ResizeWindow
        clear
        
        test -s "$YTSEARCH" && _GetYoutubePlaylistUrls -s
        __
        test -s "$URLS"  && \
        echo -e " ${info}${Type} list: $(_GetLinesList $arg) url(s)${nc}\n"
        __clipboardCmdTest && printf '%s\n' "                                  ${info}${clipboardCmd[0]} is installed, first copy a link then press 1)${nc}"
        __
        echo -e "                                                  ${mtitle}::${menuTitleType} OPTIONS::${nc}"
        echo -e "                               ┌──────────────────────────────────────────────────────┐"
        echo -e "                               │   1) Add ${Type} links         5) Play current list    │"
        echo -e "                               │   2) Search online links     6) View current list    │"
        echo -e "                               │   3) Download current list   7) Clear current list   │"
        echo -e "                               │   4) Save/Add current list   8) Back to main menu    │"
        echo -e "                               └──────────────────────────────────────────────────────┘"
        test -s "$URLS"  \
        && echo -e "                                                   ${info}Select an item${nc}" \
        || echo -e "                                                   ${info}${b}Select an item${nb}${nc}"
        __
        read -rsn 1 createAddPlaylistOptions
        case "$createAddPlaylistOptions" in
            1)  _CopyMediaUrl
                __ ;;
            2)
                if [[ $use_fzf = yes ]]; then
                    clear
                    _SearchOnline
                elif [[ $use_fzf = no ]]; then
                    __
                    printf '%s\n' \
                        " ${critical}use_fzf is set to NO in your mpmrc file..." \
                        " no way to search online!${nc}"
                    sleep 5
                else
                    __
                    printf '%s\n' " ${critical}use_fzf is not set in your mpmrc..." \
                    " no way to search online!${nc}"
                    sleep 5
                fi
            ;;
            3)
                _MpvOwnsTmpList --list || \
                [[ $arg = '-a' ]] && _GetAudio -a || _GetVideo -v
                __ ;;
            4)
                _MpvOwnsTmpList --list || _Save $arg
                __ ;;
            5)
                _MpvOwnsTmpList --list || _LoadAudioVideo $arg
                __ ;;
            6)  _ViewAudioVideoUrlsInfo $arg
                __ ;;
            7)
                _MpvOwnsTmpList --list || _Remove $arg
                __ ;;
            8)  _Menu
                __ ;;
            *)
                _WrongOption "$createAddPlaylistOptions" && continue
            ;;
        esac
        
    done

}