#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_CreateAddPlaylistActions() {

    case "$1" in
        --download)
            if [[ -f $pidofMpv || $downloadTmpList == list ]]; then
                if [[ $arg = '-a' ]]; then _GetAudio -a; else _GetVideo -v; fi
            else
                _MpvOwnsTmpList --list || \
                if [[ $arg == '-a' ]]; then _GetAudio -a; else _GetVideo -v; fi
            fi
        ;;
        --play)
            _MpvOwnsTmpList --list || _LoadAudioVideo "$arg"
        ;;
        --remove)
            if [[ -f $pidofMpv ]]; then
                _Remove "$arg"
            else
                _MpvOwnsTmpList --list || _Remove "$arg"
            fi
        ;;
        --save)
            if [[ -f $pidofMpv ]]; then
                _Save "$arg"
            else
                _MpvOwnsTmpList --list || _Save "$arg"
            fi
        ;;
    esac
    
}