#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_DeleteUrls() {

    cd "$tmp_dir" || exit 1
    
    declare -a tmps=(
        "$AUDIO_URLS" "$AUDIO_TITLES"
        "$VIDEO_URLS" "$VIDEO_TITLES"
        "$FFOP" "$YTOP" "$DEFAULTITLES"
        "$NOWPLAYING" "$tmp_dir/1" "$CHOOSE1"
        "Audio" "Video" "default" "temporarySelection"
    )

    [[ -s "${tmps[0]}" || -s "${tmps[2]}" || -s "${tmps[6]}" ]] && {
        _Prompt -n " ${critical}Clear all temporary playlists?${nc}" && {
            if [[ -f $NOWPLAYING ]]; then

                for w in "${tmps[@]:10:13}"; do
                    if [[ $(awk -F"/" '{print $NF}' "$NOWPLAYING") =~ $w ]]; then
                        [[ $w = "${tmps[10]}" ]] && {
                            unset {tmps[0],tmps[1],tmps[7],tmps[10]}
                            sed -i '/^[[:alpha:]]/d' "$QUEUE"
                        }
                        [[ $w = "${tmps[11]}" ]] && {
                            unset {tmps[2],tmps[3],tmps[7],tmps[11]}
                            sed -i '/^[[:alpha:]]/d' "$QUEUE"
                        }
                        [[ $w = "${tmps[12]}" ]] && unset {tmps[6],tmps[7],tmps[12]}
                        [[ $w = "${tmps[13]}" ]] && {
                            unset {tmps[7],tmps[9],tmps[13]}
                            sed -i '/^[[:alpha:]]/d' "$QUEUE"
                        }
                    fi
                done

                if [[ -f $NOWPLAYING && $(find . -name "*.m3u" | wc -l) -ge 2 ]]; then
                    __
                    printf '%s\n' " ${critical}All Temporary lists cleared," \
                    " except $(awk -F"/" '{print $NF}' "$NOWPLAYING").${nc}"
                    sleep 4
                else
                    __
                    printf '%s\n' " ${critical}No Temporary lists found," \
                    " except $(awk -F"/" '{print $NF}' "$NOWPLAYING")." \
                    " First quit mpv then try again.${nc}"
                    sleep 5
                fi
                rm "${tmps[@]}" 2>/dev/null

            else
                sed -i '/^[[:alpha:]]/d' "$QUEUE"
                rm "${tmps[@]}" 2>/dev/null
                printf '%s\n' " ${critical}All Temporary lists cleared.${nc}"
                sleep 2
            fi
        }
        return
    }
    printf '%s\n' " ${critical}No Temporary lists found..."
    sleep 2
}
