#!/bin/bash
## This is a part of main script: mpm.

_DeleteUrl() {

    if (( $(_GetLinesList -q) == 0 )); then
        if [[ -n $(find "$tmp_dir" -name "*.m3u") ]]; then
            _CleanTmpDir
            echo " ${critical}All tmp lists removed.${nc}"
            sleep 3
        else
            echo " ${critical}There is nothing to do, no existing tmp lists...${nc}"
            sleep 3
            _Menu
        fi
    else
        __
        sed -i '/^https/d' "$QUEUE"
        _CleanTmpDir
        echo " ${critical}All lists cleared...${nc}"
        sleep 3
        _Menu
    fi
}
