#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_DeleteUrl() {

    if (( $(_GetLinesList -q) == 0 )); then

        [[ -s "$DEFAULTITLES" ]] && rm "$DEFAULTITLES"

        if [[ -n $(find "$tmp_dir" -name "*.m3u") ]]; then
            _CleanTmpDir
            echo " ${critical}All temporary lists cleared.${nc}"
            sleep 3
        else
            rm "$DEFAULTM3UTITLES" 2>/dev/null
            echo " ${critical}There is nothing to do, no existing temporary lists...${nc}"
            sleep 3
            _Menu
        fi

    else
        __
        [[ -s "$DEFAULTITLES" ]] && rm "$DEFAULTITLES"
        sed -i '/^[[:alpha:]]/d' "$QUEUE"
        _CleanTmpDir
        echo " ${critical}All temporary lists cleared...${nc}"
        sleep 3
        _Menu
    fi

}
