#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2076,SC2015
_DirectVideoDownload() {

    mkdir -p "$videos_dir"/"${list%.*}"
    __
    printf '%s\n' " ${task}Direct download enabled.${nc}"
    __
    mapfile -t DIRECT < <(grep '^https' "$list")

    cd "$videos_dir"/"${list%.*}" || return

    for line in "${DIRECT[@]}"; do

        printf '%s\n' " ${info}$downloadVideoCounter file(s) left to download." \
        " Downloading: $(_GetLinkTitle -l)${nc}"
        
        if [[ $line =~ 'youtube.com' && $(_GetLinkTitle -l) =~ '/' ]]; then
            youtube-dl "${ytdlPreset_FS[@]}" \
            "${ytdlPreset_X[@]}" "$line"
        elif [[ $line =~ 'youtube.com' ]]; then
            youtube-dl \
            --output "$(_GetLinkTitle -l).%(ext)s" \
            "${ytdlPreset_X[@]}" "$line"
        else
            youtube-dl \
            --output "$(_GetLinkTitle -l).%(ext)s" \
            "${ytdlPreset_NC[@]}" "$line"
        fi

        ((downloadVideoCounter--))

        sed -i '2d' "$playlists_dir"/"$list"
        sed -i '1d' "$titles_dir"/"$list".titles
        clear

    done

}
