#!/bin/bash
## This is a part of main script: mpm.

_DownloadVideo() {
    cd "$playlists_dir" || exit 1
    local counter
    counter=$(grep -v -c '#EXTM3U' "$list")
    clear
    cp -f "$list" "$list"_origin 2>/dev/null
    
    __DirectVideoDownload() (
        __
        printf '%s\n' " ${c}Direct download enabled.${nc}"
        __
        mapfile -t DIRECT < <(grep -v '#EXTM3U' "$list")

        for line in "${DIRECT[@]}"; do
            cd "$videos_dir" || exit 1
            printf '%s\n' " ${g}Downloading $counter file(s).${nc}" \
            " Downloading $(_GetLinkTitle -l):${nc}"
            [[ $line =~ 'youtube.com' ]] && {
                youtube-dl --no-warnings --merge-output-format mp4 "$line"
                clear
            } || youtube-dl --no-warnings "$line" && clear
            ((counter--))
            sed -i '2d' "$playlists_dir"/"$list"
            sed -i '1d' "$titles_dir"/"$list".titles
        done
    )
    
    if [[ $direct_download = yes ]]; then
        __DirectVideoDownload
    else
        __
        echo " ${g}Tip: direct download will always pick the best format,"
        echo -e " on Youtube webm may be the best one but we'll merge files in mp4.\n"
        echo -e " Choose [S]pecific codes or [D]irect download?:\n${nc}"
        sleep 0.5 && read -rsn 1 choice
    fi

    case "$choice" in
        d|D)
            __DirectVideoDownload
        ;;
        s|S)
            for downvideourl in $(grep -v '#EXTM3U' "$list"); do
                clear
                cd "$videos_dir" || exit 1
                if [[ $downvideourl =~ 'youtube.com' ]]; then
                    __
                    echo " ${g}Codes for $(_GetLinkTitle -l):${nc}"
                    youtube-dl -F --no-warnings "$downvideourl" \
                    | sed '1,5d;/^[sb]/d;/^\s*$/d;s/-//g;/^\s*$/d'
                else
                    youtube-dl -F --no-warnings "$downvideourl"
                fi

                __
                printf '%s\n' " ${g}Choose a format code." \
                " eg: 137+251 for merging, hls-1080p, 22 for single:${nc}"
                read -r code
                sleep 0.5
                clear

                if [[ "$code" =~ '+' ]]; then
                    printf '%s\n' " ${g}Downloading $counter file(s).${nc}"
                    youtube-dl -f "$code" --no-warnings \
                    --merge-output-format mp4 --progress "$downvideourl"
                else
                    printf '%s\n' " ${g}Downloading $counter file(s).${nc}"
                    youtube-dl -f "$code" --no-warnings --progress "$downvideourl"
                fi

                sed -i '2d' "$playlists_dir"/"$list"
                sed -i '1d' "$titles_dir"/"$list".titles
                ((counter--))
                clear

            done

        ;;
    esac
    
    echo " ${g}All done${nc}"
    sleep 2
    _DownloadCompleted

}
