#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2076,SC2164
_DownloadVideoList() {

    _TitlesListCompare -l

    local counter mediaDir
    
    mediaDir="$videos_dir/${list%.*}"
    mkdir --parents "$mediaDir"
    cd "$mediaDir" || {
        printf '\n%s\n' \
        " ${critical}Failed to access ${mediaDir##*/} directory.${nc}"
        sleep 4
        _Menu
    }

    if [[ $direct_download = yes ]]; then
        clear
        _DirectVideoDownload
    else
        clear
        _DownloadMessages --choice
        read -rsn 1 downloadVideoListOptions

        case "$downloadVideoListOptions" in
            b|B) clear; _LoadPlaylistMenu ;;
            d|D) clear; _DirectVideoDownload ;;
            s|S)
                clear
                cp -f "$playlists_dir"/"$list" "$playlists_dir"/"$list"_origin
                cp -f "$titles_dir"/"$list".titles "$titles_dir"/"$list".titles_origin

                mapfile -t SELECTED_CODES < <(grep '^https' "$playlists_dir"/"$list")
                counter="${#SELECTED_CODES[@]}"

                for url in "${SELECTED_CODES[@]}"; do

                    clear
                    _BlankLine
                    yt-dlp -F "${ytdlPreset_DW[@]}" "$url" \
                    | awk '$0 !~ /sb|youtube|info/{print $0}'
                    _DownloadMessages --m3u8

                    read -r code
                    clear
                    _DownloadMessages --direct-video

                    if [[ "$code" =~ '+' ]]; then
                        yt-dlp --format "$code" \
                        --output "$(_GetLinkTitle -l).%(ext)s" \
                        "${ytdlPreset_X[@]}" "$url"
                    else
                        yt-dlp --format "$code" \
                        --output "$(_GetLinkTitle -l).%(ext)s" \
                        "${ytdlPreset_NC[@]}" "$url"
                    fi

                    sed -i '2d' "$playlists_dir"/"$list"
                    sed -i '1d' "$titles_dir"/"$list".titles
                    ((counter--))
                    clear

                done
                unset url
            ;;
            *)
                _WrongOption "$downloadVideoListOptions"
                _LoadPlaylistMenu
            ;;
        esac
        _RemoveAudioVideoIds
    fi

    _DownloadCompleted

}
