#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2013,SC2154,SC2076,SC2031,SC2030
_DownloadVideoList() {
    cd "$playlists_dir" || exit 1

    local downloadvideocounter
    downloadvideocounter=$(grep -v -c '#EXTM3U' "$list")

    clear
    cp -f "$list" "$list"_origin 2>/dev/null
    mkdir -p "$videos_dir"/"${list%.*}"

    if [[ $direct_download = yes ]]; then
        _DirectVideoDownload
    else
        __
        echo " ${info}Tip: direct download will always pick the best format,"
        echo -e " on Youtube webm may be the best one but we'll merge files in mp4.\n"
        echo -e " Choose [S]pecific codes or [D]irect download?:\n${nc}"
        sleep 0.5 && read -rsn 1 choice
    fi

    case "$choice" in
        d|D) _DirectVideoDownload ;;
        s|S)
            cd "$videos_dir"/"${list%.*}" || return
            for downvideourl in $(grep -v '#EXTM3U' "$list"); do

                clear
                __
                echo " ${info}Codes for: $(_GetLinkTitle -l)${nc}"
                youtube-dl -F --no-warnings "$downvideourl"
                __
                printf '%s\n' " ${info}Choose a format code." \
                " eg: 137+251 for merging, hls-1080p, 22 for single:${nc}"
                read -r code
                sleep 0.5
                clear

                if [[ "$code" =~ '+' ]]; then

                    printf '%s\n' " ${info}Downloading $downloadvideocounter file(s).${nc}"
                    youtube-dl \
                    -o "$(_GetLinkTitle -l)".mp4 \
                    -f "$code" --no-warnings \
                    --merge-output-format mp4 \
                    --progress "$downvideourl"

                else

                    printf '%s\n' " ${info}Downloading $downloadvideocounter file(s).${nc}"
                    youtube-dl \
                    -o "$(_GetLinkTitle -l)".mp4 \
                    -f "$code" --no-warnings \
                    --progress "$downvideourl"

                fi

                sed -i '2d' "$playlists_dir"/"$list"
                sed -i '1d' "$titles_dir"/"$list".titles
                ((downloadvideocounter--))
                clear

            done

        ;;
    esac

    echo " ${info}All done${nc}"
    sleep 2
    _DownloadCompleted

}
