#!/bin/bash
## This is a part of main script: mpm.

_DownloadAudio() {

    cd "$audios_dir"
    clear
    cp -f "$list" "$list"_origin 2>/dev/null
    _CheckCode -l

    for url in $(grep '^https' "$list"); do
        # We compare if the content of $list is less than 3 because:
        # 1) we have expression #EXTM3U at the top.
        # 2) the uniq url we've enter...if that's the case.
        if (( $(_GetLinesList -l) < 3 )); then
            echo ""
            echo " ${green}There is $(_GetLinesList -l) audio file left to download.${nocolor}"
        else
            echo ""
            echo " ${green}There are $(_GetLinesList -l) audio files left to download.${nocolor}"
        fi

        echo ""
        echo -e " ${green}Codes for: $(_GetLinkTitle -d).${nocolor}\n"
        youtube-dl -F "$url" | sed -n '6,7p;/audio only/p'
        echo ""
        echo " ${green}Choose a format code: ${nocolor}"
        read -r code
        clear
        echo " ${green}Downloading ${red}$(_GetLinkTitle -d)...${nocolor}"
        youtube-dl -f "$code" --progress "$url"
        sed -i '2d' "$list"; sed -i '1d' "$tmp_dir"/download.txt
        clear

    done

    echo -e " ${green}Done${nocolor}\n"

    if [[ -n $(find . -iname "*.webm") ]]; then
        echo -e " ${red}Advisory: IF YOU CHOOSE CONVERSION, ALL FILES WILL BE IN THE CHOSEN FORMAT.${nocolor}\n"
        find . -iname "*.webm" | sed 's,.*/,,'
        echo ""
        echo -e " ${green}Do you wish to convert them? [Y/n]: ${nocolor}\n"
        read -rsn 1 answer

        case "$answer" in
            Y|y)    _ConvertAudio ;;
            n|N)    _DownloadCompleted ;;
        esac
        _DownloadCompleted
    else
        _DownloadCompleted
    fi

}
