#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015,SC2034
_DownloadCompleted() {
    cd "$playlists_dir" || exit 1

    if [[ -n $(find {"$audios_dir","$videos_dir"} -name "*.part") ]]; then
        _IfPartsExist -l
    else
        FILES=( "$list" "$list"_origin "$titles_dir"/"$list".titles \
                "$titles_dir"/"$list".titles_origin "$CHOOSE1" "$CHOOSE2" )

        if [[ $(_GetLinesList -l) -gt 0 ]]; then
            if [[ $keep_none_empty_playlist = yes ]]; then
                unset {FILES[0],FILES[2]}
                rm -f "${FILES[@]}" 2>/dev/null
            else
                echo -e " ${critical}keep_none_empty_playlist is set to 'no'.${nc}\n"
                _Prompt \
                " ${info}Downloads completed but $list is not empty, do you want to KEEP it?:${nc}" || {
                    rm -f "${FILES[@]}" 2>/dev/null
                    printf '%s\n' " ${critical}$list removed...${nc}"
                    sleep 3
                }
                unset {FILES[0],FILES[2]}
                rm -f "${FILES[@]}" 2>/dev/null
            fi
        else
            printf '%s\n' " ${info}Downloads completed," \
            " ${critical}$list is empty... $list removed.${nc}"
            sleep 3
            rm -f "${FILES[@]}" 2>/dev/null
        fi
        
        _IfQuitAfterTask
    fi
}
