#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015
_DownloadCompleted() {
    cd "$playlists_dir" || exit 1
    
    if [[ -n $(find "$audios_dir" "$videos_dir" -name "*.part") ]]; then
        _IfPartsExist -l
    else
        FILES=( "$list" "$list"_origin "$titles_dir"/"$list".titles \
        "$titles_dir"/"$list".titles_origin "$CHOOSE1" "$CHOOSE2" )

        __KeepItOrNot() (
            if [[ $keep_none_empty_playlist = yes ]]; then
                unset {FILES[0],FILES[2]}
                rm -f "${FILES[@]}" 2>/dev/null
            else
                _Prompt \
                " ${info}Downloads completed but $list is not empty, do you want to KEEP it?: ${nc}" || {
                    rm -f "${FILES[@]}" 2>/dev/null
                }
                unset {FILES[0],FILES[2]}
                rm -f "${FILES[@]}" 2>/dev/null
            fi
        )
    
        if grep -wq '^https' "$list" && \
        [[ $(awk '$0 !~ /^https|#EXTM3U/{print $0}' "$list") ]] ; then
            __KeepItOrNot
        elif grep -wq '^https' "$list"; then
            __KeepItOrNot
        else
            echo " ${info}Downloads completed, ${critical}$list is empty... $list removed.${nc}"
            sleep 5
            rm -f "${FILES[@]}" 2>/dev/null
        fi
        [[ $quit_after_task = yes ]] && exit || _Menu
    fi
}
