#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_DownloadMessages() {
    case "$1" in
        --choice)
            __
            printf '%s\n' " ${critical}Tip: In this section you will have to enter specific ID codes" \
            " for all urls, direct download will always pick the best format," \
            " on Youtube webm may be the best one but we'll merge files in ${ytdlPreset_MF[1]}.${nc}"
            [[ $(_GetLinesList -l) -gt 10 ]] && {
                __
                printf '%s\n' \
                " ${critical}This playlist contains more than ${task}10 urls," \
                " ${critical}you might want to choose ${task}[D]irect download?"
            }
            __
            printf '%s\n' " ${info}Make a choice: " \
            " [B]ack to download options, choose [S]pecific codes or [D]irect download?: ${nc}"
        ;;
        --choose-audio|--choose-video)
            if [[ $use_parallel_downloads == yes ]]; then
                __
                printf '%s\n' " ${task}Parallel downloads enabled," \
                " ${info}$counter file(s) left to downloads, please be patient${b}...${nb}${nc}"
            else
                __
                printf '%s\n' " ${info}$counter file(s) left to downloads." \
                " Downloading: $(_GetLinkTitle -s)${nc}"
            fi
        ;;
        --direct-video)
            if [[ $use_parallel_downloads == yes ]]; then
                __
                printf '%s\n' " ${task}Parallel downloads enabled," \
                " ${info}$counter video file(s) left to downloads, please be patient${b}...${nb}${nc}"
            else
                __
                printf '%s\n' " ${info}$counter video file(s) left to downloads." \
                " Downloading: $(_GetLinkTitle -l)${nc}"
            fi
        ;;
        --m3u8)
            __
            printf '%s\n' \
            " ${critical}If you pick a format from a none m3u8 protocol, download will fail " \
            " if ffmpeg is set as yt-dlp downloader in your configuration file." \
            " ${info}Choose a format code for: $(_GetLinkTitle -s)" \
            " eg: 137+251 for merging, hls-1080p, 22 for single:${nc}"
        ;;
        --menu)
            [[ $direct_download == no ]] && {
                printf '\n%s\n' " ${critical}${b}Direct download disabled.${nb}${nc}"
            }
            [[ $direct_download == yes ]] && {
                printf '\n%s\n' " ${task}Direct download enabled.${nc}"
            }
        ;;
    esac
}

