#!/bin/bash
## This is a part of main script: mpm.

_DownloadAudio() {
    cd "$playlists_dir"
    
    clear
    cp -f "$list" "$list"_origin 2>/dev/null
    
    for url in $(grep -v '#EXTM3U' "$list"); do
        clear
        echo " ${g}$(_GetLinesList -l) video(s) file(s) left to download.${nc}"
        echo -e " ${g}Codes for: $(_GetLinkTitle -l).${nc}\n"
        youtube-dl -F --no-warnings "$url" | sed -n \
        '1,4d;5,6p;/audio only/p' | sed '/sb2/d' 2>/dev/null
        __
        echo " ${g}Choose a format code: ${nc}"
        read -r code
        clear
        cd "$audios_dir"
        echo -e " ${g}Downloading ${r}$(_GetLinkTitle -l)...${nc}\n"
        youtube-dl -f "$code" --no-warnings --progress "$url"
        sed -i '2d' "$playlists_dir"/"$list"
        sed -i '1d' "$titles_dir"/"$list".titles
        clear

    done

    echo -e " ${g}Done${nc}\n"

    if [[ -n $(find . -iname "*.webm") ]]; then
        echo -e " ${r}Advisory: IF YOU CHOOSE CONVERSION, ALL FILES WILL BE IN THE CHOSEN FORMAT.${nc}\n"
        find . -iname "*.webm" | sed 's,.*/,,'
        __
        _Prompt " ${g}Do you wish to convert them?: ${nc}" || {
            _DownloadCompleted
        }
        _ConvertAudio && _DownloadCompleted
    else
        _DownloadCompleted
    fi

}

