#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_EditPlaylist() {
    while true; do
        clear
        cd "$playlists_dir" || exit 1
        __
        PS3=""$'\n'"${info}Choose a playlist to edit:${nc} "

        select list in $(find . -not -name "default.m3u" -name "*.m3u" \
            -o -name "*.m3u_origin" | sort -d | sed 's,.*/,,'); do
            __
            $MPMEDITOR "$list"
            echo -e " ${info}$list saved${nc}\n"

            [[ $(grep "" -c "$titles_dir/$list.titles") \
                -ne $(_GetLinesList -l) ]] && _TitlesListCompare

            read -rsn 1 \
            -p "${info}"' [C]ontinue editing, [B]ack to menu or [Q]uit.'"${nc}" edit
            case "$edit" in
                c|C)
                    break
                ;;
                b|B)
                    _Menu
                ;;
                q|Q)
                    __;__
                    if [[ -s "$AUDIO_URLS" || -s "$VIDEO_URLS" ]]; then
                        _SaveOnExit
                    else
                        nc=$'\e[0m';
                        echo "${nc}"
                        clear
                        exit 0
                    fi
                ;;
            esac
        done
    done
}