#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_EditMyPlaylist() {

    cd "$playlists_dir" || exit 1
    printf '\n%s\n' " ${info}$list edition:${nc}"
    __
    read -rsn 1 -p \
    "${info}"' [E]dit urls manually, re[N]ame playlist, [R]emove titles: '"${nc}" \
    editMyPlaylistOptions
    __
    case "$editMyPlaylistOptions" in
        e|E)
            "$MPMEDITOR" "$list"
            printf '\n%s\n' " ${info}$list saved${nc}"
            [[ $(grep "" -c "$titles_dir/$list.titles") \
            -ne $(_GetLinesList -l) ]] && _TitlesListCompare -l
        ;;
        n|N)
            __
            read -r -p " ${info}Enter a new name for $list: ${nc}" newname
            mv "$list" "$newname".m3u
            mv "$titles_dir/$list.titles" "$titles_dir/$newname.m3u.titles"
            _ReplaceSpaces -s
            printf '\n%s\n' " ${critical}${list%%.*} renamed as $newname.${nc}"
            sleep 2
        ;;
        r|R)
            clear
            _TitlesListCompare -l
            _GetRange
            _UpdateSelected -e
        ;;
        *)  _WrongOption "$editMyPlaylistOptions" ;;
    esac

    _LaunchMpm "${@}"

}