#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_EditPlaylistOptions() {

    __renameList() {
        mv -f "$list" "$newname".m3u
        mv -f "$titles_dir/$list.titles" "$titles_dir/$newname.m3u.titles"
        _ReplaceSpaces -s
        printf '\n%s\n' " ${critical}${list%%.*} renamed as $newname.${nc}"
        sleep 2
    }

    declare -a editPlaylistOptionsPrompt=(
        "[U]rls edition,"
        "[T]itles edition,"
        "re[N]ame the playlist,"
        "[R]emove titles,"
        "[${mtitle}C${info}]ancel:"
    )

    printf '\n%s\n' " ${info}Choose an option for ${task}$list:${nc}"
    _BlankLine
    read -rsn 1 -p \
    "${info} ${editPlaylistOptionsPrompt[*]} ${nc}" editPlaylistOptions

    case "$editPlaylistOptions" in
        [cC])
            if [[ $editoption == yes ]]; then
                editoption=no
                clear
                _LaunchMpm "${@}"
            else
                _Menu
            fi
        ;;
        [nN])
            _BlankLine
            read -r -p " ${info}Enter a new name for ${list%%.*}: ${nc}" newname
            [[ -f $list ]] && {
                printf '\n%s\n' " ${critical}File $list already exists."
                _Prompt -n " ${info}Do you want to replace it?: ${nc}" && {
                    __renameList
                }
                _Menu
            }
            __renameList
        ;;
        [rR])
            clear
            _MpvOwnsTmpList --collection || \
            if _TestFzfCommand; then
                local removeCollectionTitles
                removeCollectionTitles="yes"
                _TitlesListCompare --fzf
            else
                _TitlesListCompare --list
                _GetRange
                _UpdateSelected --edit
            fi
        ;;
        [tT])
            TITLES="$titles_dir"/"$list".titles
            _BlankLine
            _EditListTitles && {
                clear
                printf '\n%s\n' " ${info}$list.titles saved${nc}"
                sleep 2
            }
        ;;
        [uU])
            "$MPMEDITOR" "$list"
            mapfile -t listCount < "$list"
            clear
            if (( ${#listCount[@]} <= 1 )); then
                _BlankLine
                printf '%s\n' " ${critical}${list##*/} is empty...${list##*/} removed.${nc}"
                rm {"$list","$titles_dir"/"$list".titles}
                sleep 2
            else
                printf '\n%s\n' " ${info}$list saved${nc}"
                sleep 2
                _TitlesListCompare --list
            fi
        ;;
        *)  _WrongOption "$editPlaylistOptions" ;;
    esac

}
