#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
# shellcheck source=/dev/null
_EditMpmConf() {

    local theme

    _BlankLine
    read -rsn 1 -p \
    " ${info}[${mtitle}C${info}]ancel, Edit [M]pmrc or [T]hemerc?: ${nc}" editConfig

    case "$editConfig" in
        [cC]) return ;;
        [mM]) editConfig=mpmrc; $MPMEDITOR "$MPMRC"; ;;
        [tT]) editConfig=themerc; $MPMEDITOR "$THEMERC"; ;;
        *   ) _WrongOption "$editConfig"; return ;;
    esac

    clear
    if [[ -z $THEME ]]; then
        theme="default"; nc=$'\e[0m'; critical=$'\e[31m';
        info=$'\e[32m'; mtitle=$'\e[33m'; task=$'\e[37m';
        . "$THEMERC"
    else
        . "$MPMRC"; . "$THEMERC"
        _Theme "$THEME"
    fi

    _BlankLine
    printf '%s\n' " ${info}$editConfig saved! New changes actives.${nc}"
    sleep 2

    case "$1" in
        -m) return ;;
        * )  _Menu ;;
    esac

}
