#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
# shellcheck source=/dev/null
_EditMpmConf() {

    : "${XDG_CONFIG_HOME:-$HOME/.config}"

    $MPMEDITOR "$XDG_CONFIG_HOME/mpm/mpmrc"
    printf '%s\n' " ${info}mpm config saved! New changes active.${nc}"
    source "$XDG_CONFIG_HOME"/mpm/mpmrc
    sleep 3
    clear
    _Menu

}

