#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_EditTmpListTitles() {

    cp "$TITLES" "$tmp_dir"/tmp_titles
    "$MPMEDITOR" "$TITLES"

    if [[ $(grep "" -c "$TITLES") -ne $(grep "" -c "$tmp_dir"/tmp_titles) ]]; then
        mv -f "$tmp_dir"/tmp_titles "$TITLES"
        _BlankLine
        printf '%s\n' " ${critical}Deleting titles isn't considered editing..." \
        " you should better [R]emove links instead.${nc}"
        sleep 7
    else
        rm "$tmp_dir"/tmp_titles
    fi
}
