#!/bin/bash
## This is a part of main script: mpm.

_EditMpvConf() {

    local mpvconf="$XDG_CONFIG_HOME/mpv/mpv.conf"
    
    if [[ -f $mpvconf ]]; then
        $EDITOR "$mpvconf"
        echo " ${green}mpv.conf saved.${nocolor}"
        sleep 2
        clear
        _Menu
    else
        echo " ${red}$mpvconf doesn't exist...${nocolor}"
        sleep 3
        clear
        _Menu
    fi

}
