#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_EditPlaylist() {
    while true; do
        clear
        cd "$playlists_dir" || exit 1
        __
        PS3=""$'\n'"${info}Choose a playlist to edit:${nc} "

        select playlist in $(find . -name "*.m3u" -o -name "*.m3u_origin" \
            | sort -d | sed 's,.*/,,'); do
                __
                $MPMEDITOR "$playlist"
                echo -e " ${info}$playlist saved${nc}\n"
                read -rsn 1 \
                -p "${info}"' [C]ontinue editing, [B]ack to menu or [Q]uit.'"${nc}" edit
                
                case "$edit" in
                    c|C) break ;;
                    b|B) _Menu ;;
                    q|Q) clear && exit ;;
                esac
                
        done

    done
}

