#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_EditPlaylistOptions() {

    declare -a editPlaylistOptionsPrompt=(
        "edit [U]rls,"
        "edit [T]itles,"
        "re[N]ame the playlist,"
        "[R]emove titles,"
    )

    printf '\n%s\n' " ${info}Choose an option for ${task}$list:${nc}"; __
    read -rsn 1 -p \
    "${info} ${editPlaylistOptionsPrompt[*]} [${mtitle}C${info}]ancel:${nc}" \
    editPlaylistOptions

    case "$editPlaylistOptions" in
        c|C)
            if [[ $editoption == yes ]]; then
                editoption=no
                clear
                _LaunchMpm "${@}"
            else
                _Menu
            fi
        ;;
        n|N)
            __
            read -r -p " ${info}Enter a new name for ${list%%.*}: ${nc}" newname
            mv "$list" "$newname".m3u
            mv "$titles_dir/$list.titles" "$titles_dir/$newname.m3u.titles"
            _ReplaceSpaces -s
            printf '\n%s\n' " ${critical}${list%%.*} renamed as $newname.${nc}"
            sleep 2
        ;;
        r|R)
            clear
            _TitlesListCompare -l
            _GetRange
            _UpdateSelected -e
        ;;
        t|T)
            "$MPMEDITOR" "$titles_dir"/"$list".titles
        ;;
        u|U)
            "$MPMEDITOR" "$list"
            printf '\n%s\n' " ${info}$list saved${nc}"
            [[ $(grep "" -c "$titles_dir/$list.titles") \
            -ne $(_GetLinesList -l) ]] && _TitlesListCompare -l
        ;;
        *)  _WrongOption "$editPlaylistOptions" ;;
    esac

}