#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ExitOrHelp() {

    read -rsn 1 -p "${info}"' Get [H]elp or [Q]uit: '"${nc}" ExitOrHelpOptions
    case "$ExitOrHelpOptions" in
        h|H)
            less "$HELP"
        ;;
        q|Q)
            __;__
            if [[ -s "$AUDIO_URLS" || -s "$VIDEO_URLS" ]]; then
                _SaveOnExit
            else
                nc=$'\e[0m';
                echo "${nc}"
                clear
                exit 0
            fi
        ;;
    esac
    
}