#!/bin/bash
## This is a part of main script: mpm.

# shellcheck source=/dev/null
# shellcheck disable=SC2154,SC2317
_FzfPlayer() {

    cd "$tmp_dir" || exit 1

    local colorscheme

    . "$MPMRC"; . "$THEMERC"
    colorscheme=$(awk -F= '/native_tui_colors/{gsub(/"/,""); print $2}' "$MPMRC")

    # fixed window size
    echo -ne '\e[8;32;124t'

    __passPlaylistIndexToMpv() (
        local index lenght
        index=$(awk '{print $1}' playerSelectedFile)
        lenght="${#index}"

        if [[ $lenght -eq 1 ]]; then
            index="${index:0:1}"
        elif [[ $lenght -eq 2 ]]; then
            index="${index:0:2}"
        else
            index="${index:0:3}"
        fi
        echo playlist-play-index "$index" | socat - "${MPVSOCKET}"
    )

    export -f __passPlaylistIndexToMpv

    # this function is in ~/.config/mpm/themerc
    _NativePlayerColors "$colorscheme"

    while [[ -s playerSelectedFile ]]; do
        fzf \
        --cycle \
        --reverse \
        --no-multi \
        --pointer '|>' \
        --scroll-off=5 \
        --no-scrollbar \
        --border rounded \
        --prompt='Search: ' \
        --preview-window=down:1 \
        --preview="(_MpvSocketCommands --title)" \
        --header-first \
        --header '  Enter:play, Left:-30s, Right:+30s, ^N:next, ^P:prev, ^T:toggle pause, ^R:reload, ESC:quit player, ^X:quit mpv:
  ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
        ' \
        --bind "enter:become(echo {} > playerSelectedFile; __passPlaylistIndexToMpv)" \
        --bind "ctrl-n:become(_MpvSocketCommands --next)" \
        --bind "ctrl-p:become(_MpvSocketCommands --prev)" \
        --bind "ctrl-t:become(_MpvSocketCommands --pause)" \
        --bind "ctrl-r:become(_MpvSocketCommands --begin)" \
        --bind "left:become(_MpvSocketCommands --backward)" \
        --bind "right:become(_MpvSocketCommands --forward)" \
        --bind "ctrl-x:become(_MpvSocketCommands --stop; rm ./playerSelectedFile)" \
        --bind "esc:become(sed -i '1d' ./playerSelectedFile)" < playerIndexesList
    done

    export FZF_DEFAULT_OPTS=

}
