#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_FzfEnqueueOptions() {

    read -rsn 1 -p " ${info}[A]dd more files, [N]o thanks: ${nc}" enqueueOptions
    clear
    sed -i "s/^/${localDirPath}\//" fzfEnqueue.m3u
    case "$enqueueOptions" in
        a|A)
            if [[ -f "$FZFENQUEUE" ]]; then
                cat "$FZFENQUEUE" fzfEnqueue.m3u > ./tmpfile
                mv -f ./tmpfile "$FZFENQUEUE"
                rm fzfEnqueue.m3u
                _SelectLocalDir -f
            else
                mv -f fzfEnqueue.m3u "$FZFENQUEUE"
                _SelectLocalDir -f
            fi
        ;;
        n|N)
            use_mpvc_locally="yes"
            localPlaylist=yes

            if [[ -f "$FZFENQUEUE" ]]; then

                cat "$FZFENQUEUE" fzfEnqueue.m3u > ./tmpfile
                rm fzfEnqueue.m3u
                mv -f ./tmpfile "$FZFENQUEUE"
                
                if [[ $localMediaType == audio ]]; then
                    _LoadAudioVideo -fa
                elif [[ $localMediaType == video ]]; then
                    _LoadAudioVideo -fv
                else
                    m3uFile="$FZFENQUEUE"
                    ln -sfr "$m3uFile" "$NOWPLAYING"
                    _MakeMpvPlaylist --fzf
                fi
                
            else
                if [[ $localMediaType == audio ]]; then
                    mv -f ./fzfEnqueue.m3u "$FZFENQUEUE"
                    _LoadAudioVideo -fa
                elif [[ $localMediaType == video ]]; then
                    mv -f ./fzfEnqueue.m3u "$FZFENQUEUE"
                    _LoadAudioVideo -fv
                else
                    m3uFile="$localDir/$dir/fzfEnqueue.m3u"
                    ln -sfr "$m3uFile" "$NOWPLAYING"
                    _MakeMpvPlaylist --fzf
                fi
            fi
        ;;
        *)
            rm {fzfEnqueue.m3u,"$FZFENQUEUE"} 2>/dev/null
            _WrongOption "$enqueueOptions"; return
        ;;
    esac

}