#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034,SC2128
_FzfEnqueue() {

    cd "$localDir"/"$dir" || return
    _ResizeWindow
    rm ./fzfEnqueue.m3u 2>/dev/null

    ! command -v "$fzf_preview" && fzf_preview=(file -N -i --)
    
    command ls "$localDir"/"$dir" | sed '/fzfEnqueue.m3u/d' \
    | fzf \
    --multi \
    --reverse \
    --pointer '<>' \
    --scroll-off=5 \
    --no-scrollbar \
    --border rounded \
    --border-label "| ${PWD##*/} |" \
    --prompt='Search: ' \
    --header "${info}${b}"'Press Tab to select, Enter to confirm, Escape to cancel: '"${nb}${nc}" \
    --preview-window="$fzf_preview_layout:$fzf_preview_size" \
    --preview="$fzf_preview {}" >> fzfEnqueue.m3u

    [[ ! -s ./fzfEnqueue.m3u ]] && {
        rm ./fzfEnqueue.m3u
        return
    }

    use_mpvc_locally="yes"
    mpv --no-terminal "${mpvGenOptions_SK[@]}" \
    "${mpvGenOptions_ID[@]}" fzfEnqueue.m3u &
    ln -sr ./fzfEnqueue.m3u "$NOWPLAYING"

}