#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_FzfPlaylistActions() {

    cd "$titles_dir" || exit 1

    _TestIfPlaylistsHaveTitltes

    titleList=$(find . -name "*.titles" | sort -d | sed 's,.*/,,')
    titleList=$(
        printf '%s\n' "${titleList//.titles}" | \
        fzf \
        --cycle \
        --reverse \
        --no-multi \
        --header-first \
        --scroll-off=5 \
        --pointer '<>' \
        --border rounded \
        --prompt='Search: ' \
        --border-label "| $action a playlist |" \
        --preview-window="$fzf_preview_layout:$fzf_preview_size" \
        --header="${info}${b}"'Press Enter to select, Escape to cancel:'"${nb}${nc}" \
        --preview='(cat {}.titles)' >> "$FZFSELTITLES"
    )

    if [[ ! -s $FZFSELTITLES ]]; then
        rm "$FZFSELTITLES"
        _Menu
    else
        list=$(cat "$FZFSELTITLES")
        cd "$playlists_dir" || exit 1
        list=${list//.titles/}
        rm "$FZFSELTITLES"
        case "$1" in
            --edit)
                _EditPlaylistOptions
            ;;
            --load)
                _LoadPlaylistMenu
            ;;
            --remove)
                clear
                _MpvOwnsTmpList --collection || {
                    _BlankLine
                    _Prompt -n \
                    " ${critical}Are you sure you want to remove $list?:${nc}" && {
                        rm {"$playlists_dir"/"$list","$titles_dir"/"$list".titles}
                        echo -e "\n ${critical}$list removed.${nc}"
                        sleep 3
                        _Menu
                    }
                    echo -e "\n ${info}$list preserved"
                    sleep 2
                    _Menu
                }
            ;;
        esac
    fi

}
