#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_FzfLoadMultiplePlaylists() {

    cd "$titles_dir" || exit 1
    local playerTitlesList m3uFile list lst cmd temp_m3u temp_titles
    temp_m3u="$tmp_dir/loadMultiplePlaylists.m3u"
    temp_titles="$tmp_dir/multipleFilesTitles"
    rm {"$temp_m3u","$temp_titles"} 2>/dev/null

    titleList=$(find . -name "*.titles" -printf '%f\n' | sort -d)

    printf '%s\n' "${titleList//.titles}" | \
    fzf \
    --cycle \
    --reverse \
    --multi \
    --header-first \
    --scroll-off=5 \
    --pointer '<>' \
    --border rounded \
    --prompt='Search: ' \
    --border-label "| $action multiple playlists |" \
    --preview-window="$fzf_preview_layout:$fzf_preview_size" \
    --header="${info}${b}"'Press Tab to select, Escape to cancel:'"${nb}${nc}" \
    --preview='(cat {}.titles)' | tee "$FZFSELTITLES"

    if [[ ! -s $FZFSELTITLES ]]; then
        rm "$FZFSELTITLES"
        _Menu
    else

        list=$(cat "$FZFSELTITLES")
        cd "$playlists_dir" || exit 1
        list=${list//.titles/}
        mapfile -t lstCount < "$FZFSELTITLES"
        rm "$FZFSELTITLES"
        mapfile -t all_lists <<< "$list"
        clear

        declare -a loadMultiplePlaylistsOptions=(
            "${info}[D]ownload,"
            "[P]lay selected playlists or"
            "[${mtitle}C${info}]ancel?: ${nc}"
        )

        echo -e "\n ${info}${#lstCount[@]} playlists selected.${nc}\n"
        read -rsn 1 -p " ${loadMultiplePlaylistsOptions[*]}" options

        declare -a removables=()
        __makeCombinedLists() {
            for lst in "${all_lists[@]}"; do
                "${cmd}" "$lst" "$tmp_dir/$lst"
                "${cmd}" "$titles_dir/$lst.titles" "$tmp_dir/$lst.titles"
                sed -i '/#EXTM3U/d' "$tmp_dir/$lst"
                cat "$tmp_dir/$lst" >> "$temp_m3u"
                cat "$tmp_dir/$lst.titles" >> "$temp_titles"
                removables+=("$tmp_dir/$lst")
                removables+=("$tmp_dir/$lst.titles")
            done
            sed -i '1s/^/#EXTM3U\n/' "$temp_m3u"
        }

        case "$options" in
            [pP])
                cmd="cp"
                __makeCombinedLists
                playerTitlesList="$temp_titles"
                m3uFile="$temp_m3u"
                _BlankLine
                read -rsn 1 -p " ${info}Play [A]udio or [V]ideo?: ${nc}" play
                case "$play" in
                    [aA])
                        rm "${removables[@]}"
                        _MpvOwnsTmpList --multiple || _MpvcTest -a && _Menu
                    ;;
                    [vV])
                        rm "${removables[@]}"
                        _MpvOwnsTmpList --multiple || _MpvcTest -v && _Menu
                    ;;
                    *)
                        rm {"$temp_m3u","$temp_titles"}
                        rm "${removables[@]}"
                        unset playerTitlesList m3uFile
                        _WrongOption "$play"
                        _Menu
                    ;;
                esac
            ;;
            [dD])
                cmd="mv"
                __makeCombinedLists
                _BlankLine
                read -rsn 1 -p " ${info}Download [A]udio or [V]ideo?: ${nc}" download
                case "$download" in
                    [aA])
                        rm "${removables[@]}"
                        _CheckParallelDownloads --before
                        _GetAudio -m
                    ;;
                    [vV])
                        list="loadMultiplePlaylists.m3u"
                        rm "${removables[@]}"
                        "${cmd}" -f "$temp_m3u" "$playlists_dir/$list"
                        "${cmd}" -f "$temp_titles" "$titles_dir/$list.titles"
                        _CheckParallelDownloads --before
                        _DownloadVideoList
                    ;;
                    *)
                        for file in "${removables[@]}"; do
                            if [[ $file =~ .titles ]]; then
                                "${cmd}" "$file" "$titles_dir/"
                            else
                                "${cmd}" "$file" "$playlists_dir/"
                            fi
                        done
                        unset file playerTitlesList
                        rm {"$temp_m3u","$temp_titles"}
                        _WrongOption "$download"
                        _Menu
                    ;;
                esac
            ;;
            *) _Menu ;;
        esac
    fi

}
