#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_FzfPlaylistActions() {

    cd "$titles_dir" || exit 1

    local fst
    fst="$tmp_dir"/fzfSelectedTitle

    titleList=$(find . -type f | sort -d | sed 's,.*/,,')
    titleList=$(
        printf '%s\n' "${titleList//.titles}" | \
        fzf \
        --cycle \
        --reverse \
        --no-multi \
        --scroll-off=5 \
        --pointer '<>' \
        --border rounded \
        --prompt='Search: ' \
        --border-label "| $action a playlist |" \
        --preview-window="$fzf_preview_layout:$fzf_preview_size" \
        --header="${info}${b}"'Press Enter to select, Escape to cancel:'"${nb}${nc}" \
        --preview="cat {}.titles" >> "$fst"
    )

    if [[ ! -s $fst ]]; then
        rm "$fst"
        _Menu
    else
        list=$(cat "$fst")
        cd "$playlists_dir" || exit 1
        list=${list//.titles/}
        rm "$fst"
        case "$1" in
            --edit) _EditPlaylistOptions ;;
            --load) _LoadPlaylistMenu ;;
            --remove)
                clear
                _BlankLine
                _Prompt -n \
                " ${critical}Are you sure you want to remove $list?:${nc}" && {
                    rm {"$list","$titles_dir"/"$list".titles}
                    echo -e "\n ${critical}$list removed.${nc}"
                    sleep 3
                    _Menu
                }
                echo -e "\n ${info}$list preserved"
                sleep 2
                _Menu
            ;;
        esac
    fi
}
