#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_FzfChooseTitles() {

    local fzfHeader labelAction
    fzfHeader="Tab:select items, Ctrl+A:select ALL, Enter:confirm, ESC:cancel:"

    if [[ $removeCollectionTitles == yes ]]; then
        labelAction="${critical}Remove${nc}"
    else
        labelAction="Choose"
    fi

    nl "$titlesFile" | sed 's/\s*//;s/\t/  /' | fzf \
        --cycle \
        --multi \
        --reverse \
        --header-first \
        --scroll-off=5 \
        --pointer '<>' \
        --border rounded \
        --prompt='Search: ' \
        --bind ctrl-a:select-all \
        --border-label "| $labelAction titles from: ${LIST} |" \
        --header "${info}${fzfHeader}${nc}" | awk '{print $1}' > "$FZFSELTITLES"

    if [[ ! -s $FZFSELTITLES ]]; then
        unset removeCollectionTitles
        rm "$FZFSELTITLES"
        printf '\n%s\n' " ${critical}Selection aborted.${nc}"
        sleep 2
        _Menu
    else
        rm {"$SELECTED_URLS1","$SELECTED_TITLES"} 2>/dev/null
        if [[ $removeCollectionTitles == yes ]]; then
            _GetRange
            _UpdateSelected --edit
            rm {"$SELECTED_URLS1","$SELECTED_TITLES","$tmp_dir"/list_tmp}
            unset removeCollectionTitles
        else
            _GetRange
        fi
    fi

}
