#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_FzfEnqueueOptions() {

    read -rsn 1 -p " ${info}[A]dd more files, [N]o thanks: ${nc}" fzfEnqueueOptions
    clear
    sed -i "s/^/${localDirPath}\//" fzfEnqueue.m3u

    case "$fzfEnqueueOptions" in
        a|A)
            if [[ ! -f "$FZFENQUEUE" ]]; then
                mv -f fzfEnqueue.m3u "$FZFENQUEUE"
                _SelectLocalDir -f
            else
                cat "$FZFENQUEUE" fzfEnqueue.m3u > ./tmpfile
                mv -f ./tmpfile "$FZFENQUEUE"
                rm fzfEnqueue.m3u
                _SelectLocalDir -f
            fi
        ;;
        n|N)
            use_mpvc_locally=yes
            localPlaylist=yes
            if [[ ! -f "$FZFENQUEUE" ]]; then
                if [[ $localDir == "$radios_dir" ]]; then
                    m3uFile="$radios_dir/fzfEnqueue.m3u"
                    ln -sfr "$m3uFile" "$NOWPLAYING"
                    playerTitlesList="$m3uFile"
                    _MakeMpvPlaylistIndexes
                else
                    m3uFile="$localDir/$dir/fzfEnqueue.m3u"
                    ln -sfr "$m3uFile" "$NOWPLAYING"
                fi
                _MakeMpvPlaylist --fzf
            else
                cat "$FZFENQUEUE" fzfEnqueue.m3u > ./tmpfile
                mv -f ./tmpfile "$FZFENQUEUE"
                rm fzfEnqueue.m3u
                m3uFile="$FZFENQUEUE"
                ln -sfr "$m3uFile" "$NOWPLAYING"
                if [[ $localDir == "$radios_dir" ]]; then
                    playerTitlesList="$m3uFile"
                    _MakeMpvPlaylistIndexes
                fi
                _MakeMpvPlaylist --fzf
            fi
        ;;
        *)
            rm {fzfEnqueue.m3u,"$FZFENQUEUE"} 2>/dev/null
            _WrongOption "$fzfEnqueueOptions"; return
        ;;
    esac

}
