#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_FzfPlaylistActions() {

    cd "$titles_dir" || exit 1

    titleList=$(find . -name "*.titles" -printf '%f\n' | sort -d)
    titleList=$(
        printf '%s\n' "${titleList//.titles}" | \
        fzf \
        --cycle \
        --reverse \
        --no-multi \
        --header-first \
        --scroll-off=5 \
        --pointer '<>' \
        --border rounded \
        --prompt='Search: ' \
        --border-label "| $action a playlist |" \
        --preview-window="$fzf_preview_layout:$fzf_preview_size" \
        --header="${info}${b}"'Press Enter to select, Escape to cancel:'"${nb}${nc}" \
        --preview='(cat {}.titles)' | tee "$FZFSELTITLES"
    )

    if [[ ! -s $FZFSELTITLES ]]; then
        rm "$FZFSELTITLES"
        _Menu
    else
        list=$(cat "$FZFSELTITLES")
        cd "$playlists_dir" || exit 1
        list=${list//.titles/}
        rm "$FZFSELTITLES"
        _TitlesListCompare
        case "$1" in
            --edit)
                _EditPlaylistOptions
            ;;
            --load)
                _LoadPlaylistMenu
            ;;
            --remove)
                clear
                _MpvOwnsTmpList --collection || {
                    _BlankLine
                    _Prompt -n \
                    " ${critical}Are you sure you want to remove $list?:${nc}" && {
                        rm {"$playlists_dir"/"$list","$titles_dir"/"$list".titles}
                        printf '\n%s\n' " ${critical}$list removed.${nc}"
                        _PolybarIpc
                        sleep 3
                        _Menu
                    }
                    printf '\n%s\n' " ${info}$list preserved.${nc}"
                    sleep 2
                    _Menu
                }
            ;;
        esac
    fi

}
