#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034,SC2128
_FzfEnqueue() {

    if [[ $localDir == "$radios_dir" ]]; then
        cd "$radios_dir" || return
    else
        cd "$localDir"/"$dir" || return
    fi

    local localDirPath

    localDirPath=$(pwd | sed 's,/,\\/,g')
    _ResizeWindow -m
    rm ./fzfEnqueue.m3u 2>/dev/null

    _Has "$fzf_preview" || fzf_preview=(file -N -i --)
    find . -type f | sort -d | sed 's,.*/,,;/fzfEnqueue.m3u/d' | \
    fzf \
    --multi \
    --cycle \
    --reverse \
    --pointer '<>' \
    --scroll-off=5 \
    --no-scrollbar \
    --header-first \
    --border rounded \
    --prompt='Search: ' \
    --border-label "| ${PWD##*/} |" \
    --header "${info}${b}"'Press Tab to select, Enter to confirm, Escape to cancel:'"${nb}${nc}" \
    --preview-window="$fzf_preview_layout:$fzf_preview_size" \
    --preview="$fzf_preview {}" >> fzfEnqueue.m3u

    if [[ ! -s ./fzfEnqueue.m3u ]]; then
        rm ./fzfEnqueue.m3u
        return
    else
        clear; _BlankLine
        _FzfEnqueueOptions
    fi

}
