#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetMediaTitle() {

    case "$1" in
        -a) LIST="$AUDIO_INFO" ;;
        -l) LIST="$playlists_dir"/"$list" ;;
        -q) LIST="$QUEUE" ;;
        -v) LIST="$VIDEO_INFO" ;;
    esac

    mapfile -t title < <(grep '^https' "$LIST")

    for line in "${title[@]}"; do
        youtube-dl \
        --skip-download \
        --get-title \
        --no-warnings "$line" 2>/dev/null
    done

}

