#!/bin/bash
## This is a part of main script: mpm.

_GetLinkTitle() {
    case "$1" in
        -a)
            sed -n '1p' "$AUDIO_TITLE"
        ;;
        -q)
            sed -n '1p' "$tmp_dir"/DefaultAudio 2>/dev/null \
            || sed -n '1p' "$tmp_dir"/DefaultVideo 2>/dev/null
        ;;
        -v)
            sed -n '1p' "$VIDEO_TITLE"
        ;;
    esac
}
