#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetYoutubePlaylistUrls() {
    __
    case "$1" in
        -a) URLS_INFO="$AUDIO_URLS"
            url="$copyAudioUrl"
        ;;
        -v) URLS_INFO="$VIDEO_URLS"
            url="$copyVideoUrl"
        ;;
    esac

    youtube-dl "${ytdlPreset_DW[@]}" -j "$url" \
    | jq '(.webpage_url)' | sed 's/"//g' \
    | tee -a "$QUEUE" >> "$URLS_INFO"
    sed -i '/playlist/d' {"$QUEUE","$URLS_INFO"}

}