#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_GetVideoDownload() {

    mkdir --parents "$mediaDir"
    cd "$mediaDir" && {

        local animationTitles type
        animationTitles="$TITLES"
        type="video"

        __testTitles() {
            if [[ $TITLES == "$DEFAULT_TITLES" ]]; then
                yt-dlp --format "$code" --output "$(_GetLinkTitle -d).%(ext)s" \
                "${ytdlPreset_X[@]}" "$url"
            else
                yt-dlp --format "$code" --output "$(_GetLinkTitle -v).%(ext)s" \
                "${ytdlPreset_X[@]}" "$url"
            fi
        }

        if _TestParallelCommand; then
            _GetAudioVideoDownloadMessages --parallel
            _ParallelDownloadCmd parallel --get-video
            _ParallelAnimation
        elif _TestXargsCommand; then
            _GetAudioVideoDownloadMessages --xargs
            _ParallelAnimation &
            _ParallelDownloadCmd xargs --get-video
        else
            mapfile -t -s 1 VIDEOLINKS < "$M3UFILE"
            [[ $M3UFILE == "$VIDEO_URLS" ]] && mapfile -t VIDEOLINKS < "$M3UFILE"
            for url in "${VIDEOLINKS[@]}"; do
                echo -e "\n ${info}Getting formats...${nc}\n"
                yt-dlp -F "${ytdlPreset_DW[@]}" "$url" \
                | awk '$0 !~ /sb|youtube|info/{print $0}'
                _BlankLine
                __chooseFormatMessages
                read -r code
                clear
                _GetAudioVideoDownloadMessages --onebyone
                # it seems that only youtube uses merging options
                if [[ "$url" =~ 'youtube' ]]; then
                    __testTitles
                else
                    yt-dlp --format "$code" "${ytdlPreset_NC[@]}" "$url"
                fi

                if [[ $M3UFILE == "$VIDEO_URLS" ]]; then
                    sed -i '1d' {"$M3UFILE","$TITLES"}
                else
                    sed -i '2d' "$M3UFILE"
                    sed -i '1d' "$TITLES"
                fi

                clear

            done
            unset url
        fi
    }

    _RemoveAudioVideoIds
    _GetCompleted

}
