#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetMediaTitle() {

    case "$1" in
        -a) LIST="$AUDIO_URLS" ;;
        -l) LIST="$playlists_dir"/"$list" ;;
        -q) LIST="$QUEUE" ;;
        -v) LIST="$VIDEO_URLS" ;;
    esac
    
    while read -r line; do
        _YtdlGetTitle "$line" 2>/dev/null
    done < <(grep '^https' "$LIST")

}
