#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetVideoDownloadMessages() {

    case "$1" in
        --parallel)
            [[ $TITLES == "$DEFAULT_TITLES" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -d) video file(s) left to download."
                printf '%s\n' " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
            }
            [[ $TITLES == "$VIDEO_TITLES" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -v) video file(s) left to download."
                printf '%s\n' " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
            }
        ;;
        --onebyone)
            [[ $TITLES == "$DEFAULT_TITLES" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -d) video file(s) left to download." \
                " Downloading:  $(sed -n '1p' "$TITLES")${nc}"
            }
            [[ $TITLES == "$VIDEO_TITLES" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -v) video file(s) left to download." \
                " Downloading:  $(sed -n '1p' "$TITLES")${nc}"
            }
        ;;
        --xargs)
            [[ $TITLES == "$DEFAULT_TITLES" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -d) video file(s) left to download."
                printf '%s\n' " ${task}Parallel downloads using xargs, ${info}please be patient${b}...${nb}${nc}"
            }
            [[ $TITLES == "$VIDEO_TITLES" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -v) video file(s) left to download."
                printf '%s\n' " ${task}Parallel downloads using xargs, ${info}please be patient${b}...${nb}${nc}"
            }
        ;;
    esac

}
