#!/bin/bash
## This is a part of main script: mpm.

_GetYoutubePlaylistUrls() {
    __
    case "$1" in
        -a) URLS_INFO="$AUDIO_INFO"
        ;;
        -v) URLS_INFO="$VIDEO_INFO"
        ;;
    esac

    youtube-dl --no-warnings -j "$url" \
    | jq '(.webpage_url)' | sed 's/"//g' \
    | tee -a "$QUEUE" >> "$URLS_INFO"
    sed -i '/playlist/d' "$QUEUE" "$URLS_INFO"

}
