#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetPlaylistUrls() {

    local playlist

    __getPlaylistUrlsInfo() (
        playlistName=$(yt-dlp "${ytdlPreset_DW[@]}" -J \
        --flat-playlist "$playlist" | jq --raw-output .title)
        _BlankLine
        printf '%s\n' \
        " ${info}Please be patient while extracting urls/titles from:" \
        " $playlistName playlist...${nc}"
    )

    # It turns out that the native method is now faster than the parallel method,
    # so let's disable parallel for now and we'll see
    case "$1" in
        -a|-v)
            playlist="$mediaUrl"
            _GetPlaylistUrlsMethods --native
        ;;
        -s)
            mapfile -t ytSearchList < "$YTSEARCH"
            # there might be several playlists urls selected in
            # _SearchOnlineWithYtfzf function so we enter in a loop.
            for url in "${ytSearchList[@]}"; do
                playlist="$url"
                __getPlaylistUrlsInfo
                _GetPlaylistUrlsMethods --native
            done

            unset url
            clear
        ;;
    esac

    rm {"$YTSEARCH","$YTFZFJSON","$tmp_dir"/playlist.{m3u,titles,txt}} 2>/dev/null
    return

}
