#!/bin/bash
## This is a part of main script: mpm.

_GetDefaultVideo() {
    __
    echo " ${g}Getting titles...${nc}"
    _GetMediaTitle -q > "$tmp_dir"/DefaultVideo
    
    cd "$videos_dir"
    cp -f "$QUEUE" "$QUEUE"_origin 2>/dev/null
    cp -f "$tmp_dir"/DefaultVideo "$tmp_dir"/DefaultVideo_origin
    [[ -f $tmp_dir/1 ]] && rm "$tmp_dir"/1
    
    for url in $(grep -v '#EXTM3U' "$QUEUE"); do
        __
        echo -e " ${g}Codes for: $(sed -n '1p' "$tmp_dir"/DefaultVideo).${nc}\n"
        
        if [[ "$url" =~ 'youtube.com' ]]; then
            youtube-dl -F --no-warnings "$url" | sed '1,4d;/^[sb]/d'
        else
            youtube-dl -F --no-warnings "$url"
        fi
        
        __
        echo -e " ${g}Choose a format code.\n eg: 137+251 (video+audio), hls-1080p, 22 for single:${nc}"
        read -r code
        
        clear
        
        __
        echo " ${g}$(_GetLinesList -q) video file(s) left to download.${nc}"
        
        if [[ "$code" =~ '+' ]]; then
            echo " ${g}Please be patient while downloading and merging formats for:"
            echo -e " ${r}$(sed -n '1p' "$tmp_dir"/DefaultVideo).${nc}\n"
            youtube-dl \
            -f "$code" \
            --no-warnings \
            --merge-output-format mp4 \
            --progress "$url"
        else
            echo " ${g}Please be patient while downloading:"
            echo -e " ${r}$(sed -n '1p' "$tmp_dir"/DefaultVideo).${nc}\n"
            youtube-dl -f "$code" --no-warnings --progress "$url"
        fi
        sed -i '2d' "$QUEUE"; sed -i '1d' "$tmp_dir"/DefaultVideo
        clear
        
    done
    
    echo -e " ${g}Done.\n${nc}"
    sleep 2
    _GetCompleted -v

}

