#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_GetCompleted() {

    cd "$main_dir" || exit 1

    if [[ -n $(find {"$audios_dir","$videos_dir"} -name "*.part") ]]; then
        _IfPartsExist -t
    else
        __
        if [[ $downloadTmpList =~ default|list ]]; then
            printf '%s\n' " ${info}Temporary list preserved...${nc}"
            sleep 2
            _RenameTmpFiles
            [[ $(awk -F= '/use_parallel_downloads/{gsub(/"/,""); print $2}' "$MPMRC") = yes ]] \
                && use_parallel_downloads="yes"
            downloadTmpList=downloaded
            _Menu
        else
            _Prompt -n " ${info}Downloads completed, KEEP playlist?:${nc}" && {
                __
                echo " ${critical}It was a temporary list, don't forget to save it.${nc}"
                sleep 3
                _RenameTmpFiles
                [[ $(awk -F= '/use_parallel_downloads/{gsub(/"/,""); print $2}' "$MPMRC") = yes ]] \
                    && use_parallel_downloads="yes"
                downloadTmpList=downloaded
                _Menu
            }
        
            if [[ -f "$DEFAULT_LIST"_origin ]]; then
                _Remove -q
            elif [[ -f "$AUDIO_URLS"_origin ]]; then
                _Remove -a
            else
                _Remove -v
            fi
        fi
    fi

}
