#!/bin/bash
## This is a part of main script: mpm.

_GetQualityCodes() {
    
    __NestedGetQualityCodes() (
        # enter highest codes first
        declare -i quality=(299 137 22 135)

        while read -r line; do
            youtube-dl --no-warnings -F $line > "$YTOP"
            if grep -q -w ${quality[0]} "$YTOP"; then
                echo $line >> "$HIGHEST"
            elif grep -q -w ${quality[1]} "$YTOP"; then
                echo $line >> "$HIGH"
            elif grep -q -w ${quality[2]} "$YTOP"; then
                echo $line >> "$MEDIUM"
            elif grep -q -w ${quality[3]} "$YTOP"; then
                echo $line >> "$LOW"
            else
                echo $line >> "$ELSE"
            fi
        done < <(grep '^https' "$M3UFILE")

        sed -i -n \
        'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P' \
        "$HIGHEST" "$HIGH" "$MEDIUM" "$LOW" "$ELSE" >/dev/null 2>&1
    )

    case "$1" in
        -v) M3UFILE="$VIDEO_INFO"
            __NestedGetQualityCodes
            _LoadVideo ;;
        -q) M3UFILE="$QUEUE"
            __NestedGetQualityCodes
            _LoadVideo ;;
        -l) M3UFILE="$list"
            __NestedGetQualityCodes
            _LoadVideo ;;
        -c) M3UFILE="$CHOOSE1"
            __NestedGetQualityCodes
            _LoadVideo ;;
    esac

}
