#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetLinesList() {

    local minusOne

    case "$1" in
        -a) FILE="$AUDIO_URLS" ;;
        -l) FILE="$playlists_dir"/"$list"; minusOne=yes ;;
        -d) FILE="$DEFAULT_LIST"; minusOne=yes ;;
        -m) FILE="$tmp_dir/loadMultiplePlaylists.m3u"; minusOne=yes ;;
        -v) FILE="$VIDEO_URLS" ;;
    esac

    [[ ! -s $FILE ]] && return

    if [[ $minusOne == "yes" ]]; then
        mapfile -t -s 1 linesCount < "$FILE"
        echo "${#linesCount[@]}"
    else
        mapfile -t linesCount < "$FILE"
        echo "${#linesCount[@]}"
    fi

}
