#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetYoutubePlaylistUrls() {

    local playlist

    __getYoutubePlaylistUrlsInfo() (
        playlistName=$(yt-dlp "${ytdlPreset_DW[@]}" -J \
        --flat-playlist "$playlist" | jq --raw-output .title)
        __
        printf '%s\n' \
        " ${info}Please be patient while extracting urls/titles from:" \
        " $playlistName playlist...${nc}"
    )

    case "$1" in
        -a|-v)
            playlist="$mediaUrl"
            if [[ -n $(command -v ytfzf) && $use_fzf == yes ]]; then
                _GetYoutubePlaylistUrlsMethods --ytfzf
            elif [[ -n $(command -v parallel) && $use_parallel == yes ]]; then
                _GetYoutubePlaylistUrlsMethods --parallel
            else
                _GetYoutubePlaylistUrlsMethods --native
            fi
        ;;
        -s)
            mapfile -t ytSearchList < <(grep '^https' "$YTSEARCH")
            # there might be several playlists urls selected in
            # _SearchYoutubeWithFzf function so we enter in a loop.
            for url in "${ytSearchList[@]}"; do
                playlist="$url"
                if [[ -n $(command -v ytfzf) && $use_fzf == yes ]]; then
                    _GetYoutubePlaylistUrlsMethods --ytfzf
                elif [[ -n $(command -v parallel) && $use_parallel == yes ]]; then
                    __getYoutubePlaylistUrlsInfo
                    _GetYoutubePlaylistUrlsMethods --parallel
                else
                    __getYoutubePlaylistUrlsInfo
                    _GetYoutubePlaylistUrlsMethods --native
                fi
            done

            unset url
            clear
        ;;
    esac

    _RemoveCrap
    rm {"$YTSEARCH","$YTFZFJSON","$tmp_dir"/playlist_titlesurls,playlist.{m3u,titles,txt}}
    rm -rf "$HOME"/.parallel

} 2>/dev/null
