#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetAudioVideoDownloadMessages() {

    [[ $M3UFILE == "$AUDIO_URLS" ]] && flag='-a'
    [[ $M3UFILE == "$VIDEO_URLS" ]] && { flag='-v'; sed=yes; }
    [[ $M3UFILE == "$playlists_dir"/"$list" ]] && flag='-l'
    [[ -f "$tmp_dir/multipleFilesTitles" ]] && flag='-m'
    [[ $M3UFILE == "$DEFAULT_LIST" || $TITLES == "$DEFAULT_TITLES" ]] && { flag='-d'; sed=yes; }
    _BlankLine
    case "$1" in
        --parallel)
            printf '%s\n' " ${info}$(_GetLinesList "$flag") ${type} file(s) left to download." \
            " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
        ;;
        --onebyone)
            if [[ $sed == "yes" ]]; then
                printf '%s\n' " ${info}$(_GetLinesList "$flag") ${type} file(s) left to download." \
                " Downloading:  $(sed -n '1p' "$TITLES")${nc}"
            else
                printf '%s\n' " ${info}$(_GetLinesList "$flag") ${type} file(s) left to download." \
                " Downloading:  $(_GetLinkTitle "$flag")" \
                " ${task}Searching for webm format...${nc}"
            fi
        ;;
        --xargs)
            printf '%s\n' " ${info}$(_GetLinesList "$flag") ${type} file(s) left to download." \
            " ${task}Parallel downloads using xargs, ${info}please be patient${b}...${nb}${nc}"
        ;;
    esac

}
