#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetLinesList() {
    case "$1" in
        -a) FILE="$AUDIO_URLS" ;;
        -l) FILE="$playlists_dir"/"$list" ;;
        -d) FILE="$DEFAULT_LIST" ;;
        -v) FILE="$VIDEO_URLS" ;;
    esac
    [[ -s $FILE ]] && grep -c '^https' "$FILE"
}
