#!/bin/bash
## This is a part of main script: mpm.
# [[ $use_parallel = yes && $use_parallel_downloads = yes ]]
# shellcheck disable=SC2154,SC2181
_GetAudioDownloadMessages() {

    _ParallelDownloadCmd --download

        if [[ $? = 0 ]]; then
            [[ $M3UFILE = "$AUDIO_URLS" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -a) audio file(s) left to download." \
                " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
            }
            [[ $M3UFILE = "$playlists_dir"/"$list" ]] && {
                __
            printf '%s\n' " ${info}$(_GetLinesList -l) audio file(s) left to download." \
            " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
            }
            [[ $M3UFILE = "$QUEUE" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -q) audio file(s) left to download." \
                " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
            }
        else
            [[ $M3UFILE = "$AUDIO_URLS" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -a) audio file(s) left to download." \
                " Downloading:  $(_GetLinkTitle -a)" \
                " ${task}Searching for webm format...${nc}"
            }
            [[ $M3UFILE = "$playlists_dir"/"$list" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -l) audio file(s) left to download." \
                " Downloading:  $(_GetLinkTitle -l)" \
                " ${task}Searching for webm format...${nc}"
            }
            [[ $M3UFILE = "$QUEUE" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -q) audio file(s) left to download." \
                " Downloading:  $(_GetLinkTitle -q)" \
                " ${task}Searching for webm format...${nc}"
            }
        fi

}

