#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetRange() {

    # we are listening/watching selected items from another playlist,
    # and we want to download selected items from the current one...
    # so we have to rename files processed in the future download function.
    [[ -f $SELECTED_TITLES ]] && {
        SELECTED_TITLES="$tmp_dir/selected.titles2"
        SELECTED_URLS1="$tmp_dir/temporarySelection3.m3u"
    }

    # remove #EXTM3U header from playlist
    IFS=$'\n'
    mapfile -t -s 1 playlist_array < "$playlists_dir"/"$list"
    echo "${playlist_array[*]}" > "$tmp_dir"/list_tmp

    IFS=", ";
    if [[ -s $FZFSELTITLES ]]; then
        mapfile -t array < "$FZFSELTITLES"
    else
        # use_fzf=no
        read -ra array -p "$RANGEPROMPT"
    fi

    for range in "${array[@]}"; do
        IFS="-"; read -r start end <<< "$range"

        [[ $range =~ [a-zA-Z] ]] && {
            rm "$tmp_dir"/list_tmp
            unset IFS range
            printf '\n%s\n' " ${critical}Selection aborted.${nc}"
            sleep 2
            if [[ $editoption == yes ]]; then
                editoption=no
                _LaunchMpm "${@}"
            else
                _Menu
            fi
        }

        [[ -z $start ]] && continue
        [[ -z $end ]] && end="$start"

        for ((i=start;i<=end;i++)); do
            sed -n "${i}p" "$tmp_dir"/list_tmp >> "$SELECTED_URLS1"
            sed -n "${i}p" "$titles_dir"/"$list.titles" >> "$SELECTED_TITLES"
        done

    done

    unset IFS range
    rm {"$FZFSELTITLES","$tmp_dir"/list_tmp} 2>/dev/null

}
