#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetMpvPlaylistInfos() {
	case "$1" in
		--title)
			echo '{ "command": ["get_property", "media-title"] }' \
        	| socat - "${MPVSOCKET}" \
        	| awk -F'"' '{ print "\033[32m"" Now playing: " "\033[33m"$4 }'
		;;
		--playlist)
			sleep 0.5
        	echo '{ "command": ["get_property", "playlist"] }' \
        	| socat - "$MPVSOCKET" \
        	| jq --raw-output '.data | .[] | .filename' > "$playerTitlesList"
		;;
	esac
}
# needed for fzf
export -f _GetMpvPlaylistInfos