#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_GetAudioDownloadMessages() {

    case "$1" in
        --parallel)
            [[ $M3UFILE = "$AUDIO_URLS" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -a) audio file(s) left to download." \
                " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
            }
            [[ $M3UFILE = "$playlists_dir"/"$list" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -l) audio file(s) left to download." \
                " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
            }
            [[ $M3UFILE = "$QUEUE" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -q) audio file(s) left to download." \
                " ${task}Parallel downloads enabled, ${info}please be patient${b}...${nb}${nc}"
            }
        ;;
        --onebyone)
            [[ $M3UFILE = "$AUDIO_URLS" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -a) audio file(s) left to download." \
                " Downloading:  $(_GetLinkTitle -a)" \
                " ${task}Searching for webm format...${nc}"
            }
            [[ $M3UFILE = "$playlists_dir"/"$list" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -l) audio file(s) left to download." \
                " Downloading:  $(_GetLinkTitle -l)" \
                " ${task}Searching for webm format...${nc}"
            }
            [[ $M3UFILE = "$QUEUE" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -q) audio file(s) left to download." \
                " Downloading:  $(_GetLinkTitle -q)" \
                " ${task}Searching for webm format...${nc}"
            }
        ;;
        --xargs)
            [[ $M3UFILE = "$AUDIO_URLS" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -a) audio file(s) left to download." \
                " ${task}Parallel downloads using xargs, ${info}please be patient${b}...${nb}${nc}"
            }
            [[ $M3UFILE = "$playlists_dir"/"$list" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -l) audio file(s) left to download." \
                " ${task}Parallel downloads using xargs, ${info}please be patient${b}...${nb}${nc}"
            }
            [[ $M3UFILE = "$QUEUE" ]] && {
                __
                printf '%s\n' " ${info}$(_GetLinesList -q) audio file(s) left to download." \
                " ${task}Parallel downloads using xargs, ${info}please be patient${b}...${nb}${nc}"
            }
        ;;
    esac

}

