#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2048,SC2154
_GetSelected() {
    # we don't quote here because yd-dlp will fail.
    for i in ${array[*]}; do
        ((i++))
        sed -n "${i}p" "$playlists_dir"/"$list" \
        >> "$CHOOSE1"
    done
    unset i
    
    for t in "${array[@]}"; do
        sed -n "${t}p" "$titles_dir"/"$list.titles" \
        >> "$SELECTEDTITLES"
    done
    unset t
}

