#!/bin/bash
## This is a part of main script: mpm.

_GetLinkTitle() {
    case "$1" in
        -a) cat "$AUDIO_TITLE" | sed -n '1p' ;;
        -v) cat "$VIDEO_TITLE" | sed -n '1p' ;;
        -d) cat "$tmp_dir"/download.txt | sed -n '1p' ;;
        -q) cat "$QUEUE" | sed -n '2p' ;;
    esac
}
