#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_GetAudioDownload() {

    mkdir --parents "$mediaDir"
    cd "$mediaDir" && {

        cp -f "$M3UFILE" "$M3UFILE"_origin
        cp -f "$TITLES" "$TITLES"_origin

        local animationTitles type
        animationTitles="$TITLES"
        type=audio

        __testTitles() {
            if [[ $TITLES == "$DEFAULT_TITLES" ]]; then
                yt-dlp --output "$(_GetLinkTitle -d).%(ext)s" \
                --format bestaudio/best "${ytdlPreset_NC[@]}" "$url"
            elif [[ $TITLES == "$AUDIO_TITLES" ]]; then
                yt-dlp --output "$(_GetLinkTitle -a).%(ext)s" \
                --format bestaudio/best "${ytdlPreset_NC[@]}" "$url"
            elif [[ $TITLES == "$tmp_dir/multipleFilesTitles" ]]; then
                yt-dlp --output "$(_GetLinkTitle -m).%(ext)s" \
                --format bestaudio/best "${ytdlPreset_NC[@]}" "$url"
            else
                yt-dlp --output "$(_GetLinkTitle -l).%(ext)s" \
                --format bestaudio/best "${ytdlPreset_NC[@]}" "$url"
            fi
        }

        if _TestParallelCommand; then
            _GetAudioVideoDownloadMessages --parallel
            _ParallelDownloadCmd parallel --get-audio
            _ParallelAnimation
        elif _TestXargsCommand; then
            _GetAudioVideoDownloadMessages --xargs
            _ParallelAnimation &
            _ParallelDownloadCmd xargs --get-audio
        else
            # default.m3u/collection playlist contains '#EXTM3U' header, but not temporaryAudioUrls.m3u
            mapfile -t -s 1 AUDIOLINKS < "$M3UFILE"
            [[ $M3UFILE == "$AUDIO_URLS" ]] && mapfile -t AUDIOLINKS < "$M3UFILE"
            for url in "${AUDIOLINKS[@]}"; do

                _GetAudioVideoDownloadMessages --onebyone

                if [[ "$url" =~ 'youtube' ]]; then
                    _BlankLine
                    __testTitles
                else
                    echo -e "\n ${info}Getting formats...${nc}\n"
                    yt-dlp -F "${ytdlPreset_DW[@]}" "$url" \
                    | awk '$0 !~/sb|youtube|info|^[-]/ {print $0}'
                    printf '\n%s\n' " ${info}Choose a format code: ${nc}"
                    read -r code
                    clear
                    _BlankLine
                    yt-dlp --format "$code" "${ytdlPreset_NC[@]}" "$url"
                fi

                if [[ $M3UFILE == "$AUDIO_URLS" ]]; then
                    sed -i '1d' {"$M3UFILE","$TITLES"}
                else
                    sed -i '2d' "$M3UFILE"
                    sed -i '1d' "$TITLES"
                fi

                clear

            done
            unset url
        fi
    }

    echo -e " ${info}Done\n${nc}"
    sleep 2
    _IfWebmFiles

}
