#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2143,SC2034
_GetAudioDownload() {
    
    local animationTitles
    animationTitles="$TITLES"

    if [[ -n $(command -v parallel) \
        && $use_parallel = yes \
        && $use_parallel_downloads = yes ]]; then

        _GetAudioDownloadMessages --parallel
        _ParallelDownloadCmd --get-audio
        _ParallelAnimation
        
    elif [[ -n $(command -v xargs) && $use_parallel_downloads = yes ]]; then

        _GetAudioDownloadMessages --xargs
        _ParallelAnimation &
        _ParallelXargsCmd --get-audio

    else
        mapfile -t AUDIOLINKS < <(grep '^https' "$M3UFILE")
        for url in "${AUDIOLINKS[@]}"; do

            _GetAudioDownloadMessages --onebyone

            if [[ $(yt-dlp -F "${ytdlPreset_DW[@]}" "$url" \
                | grep '^251') ]]; then
                __
                if [[ $(sed -n '1p' "$TITLES") =~ '/' ]]; then
                    yt-dlp --format bestaudio/best \
                    "${ytdlPreset_NC[@]}" "$url"
                else
                    yt-dlp --output "$(sed -n '1p' "$TITLES").%(ext)s" \
                    --format bestaudio/best "${ytdlPreset_NC[@]}" "$url"
                fi
            else
                yt-dlp -F "${ytdlPreset_DW[@]}" "$url" \
                | awk '/audio only|PROTO|^[-]/ {sub("^[sb*]",""); print $0}'
                __
                printf '%s\n' " ${info}Choose a format code: ${nc}"
                read -r code
                clear
                __
                if [[ $(sed -n '1p' "$TITLES") =~ '/' ]]; then
                    yt-dlp --format "$code" "${ytdlPreset_FS[@]}" \
                    "${ytdlPreset_NC[@]}" "$url"
                else
                    yt-dlp --output "$(sed -n '1p' "$TITLES").%(ext)s" \
                    --format "$code" "${ytdlPreset_NC[@]}" "$url"
                fi
            fi

            if [[ $M3UFILE = "$AUDIO_URLS" ]]; then
                sed -i '1d' {"$M3UFILE","$TITLES"}
            else
                sed -i '2d' "$M3UFILE"
                sed -i '1d' "$TITLES"
            fi

            clear

        done
    fi

    unset url
    
    echo -e " ${info}Done\n${nc}"
    sleep 2
    _IfWebmFiles
    
}
