#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_IfDuplicatesFiles() {

    cd "$addPlaylistDir" || return 1

    local ef ef_count titles_count linenumbers attr match
    ef="$tmp_dir/existingFiles"

    # Removing the '.extension', to compare
    # "$ef" file against the list of titles,
    # that do not contains extensions itself.
    command ls -N | sed -r "s/${EXTENSIONS}//" > "$ef"
    [[ ! -s $ef ]] && { rm "$ef"; return; }

    _ResizeWindow --main
    clear

    declare -i linenumbers
    attr=0
    match=0
    _BlankLine

    while read -r line; do
        if grep -q -Fx "$line" "$TITLES"; then
            echo \
            " ${task}$line ${critical}already exist in ${addPlaylistDir##*/}.${nc}"
            ((match++))
        fi
    done < "$ef"
    unset line

    mapfile -t ef_list < "$ef"
    rm "$ef"
    mapfile -t titles_list < "$TITLES"

    if ((match > 0)); then
        if ((${#titles_list[@]} == match)) \
        && ((${#ef_list[@]} > ${#titles_list[@]})); then
            # All playlist items have been downloaded already and
            # there are ALSO other files in the destination folder.
            _IfDuplicatesFilesMessages --if
            _IfDuplicatesFilesActions --if
        elif ((${#titles_list[@]} == match)); then
            # All playlist items have been downloaded already and
            # there are NO other files in the destination folder.
            _IfDuplicatesFilesMessages --elif
            _IfDuplicatesFilesActions --elif
        else
            # Some of the titles match the filenames in the destination folder.
            # _IfDuplicatesFilesMessages --else, is called from the function below.
            _IfDuplicatesFilesActions --else
        fi
    else
        return
    fi

}
