#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_IfDuplicatesFilesActions() {

    case "$1" in
        --if)
            for ((i=1;i<="${match}";i++)); do
                sed -i '$d' {"$DEFAULT_LIST","$DEFAULT_TITLES","$TITLES","$URLS"}
            done
            [[ ! -s $DEFAULT_TITLES ]] && rm "$DEFAULT_TITLES"
            [[ ! -s $TITLES ]] && rm {"$TITLES","$URLS","$ef"}
        ;;
        --elif)
            for ((i=1;i<="${match}";i++)); do
                sed -i '$d' {"$DEFAULT_LIST","$DEFAULT_TITLES"}
            done
            [[ ! -s $DEFAULT_TITLES ]] && rm "$DEFAULT_TITLES"
            rm {"$TITLES","$URLS","$ef"}
        ;;
        --else)
            while read -r line; do
                ((attr++))
                if grep -q -Fx "$line" "$ef"; then
                    linenumbers+=("$attr")
                fi
            done < "$TITLES"

            rm "$ef"; unset line
            _IfDuplicatesFilesMessages --else
            _CreateAddPlaylistActions --remove

            [[ -s "$URLS" ]] && {
                cat "$URLS" >> "$DEFAULT_LIST"
                cat "$TITLES" >> "$DEFAULT_TITLES"
                _RemoveCrap
            }
        ;;
    esac

}
