#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_IfDuplicatesFiles() {

    cd "$addPlaylistDir" || return 1

    local ef efCount titlesCount linenumbers attr match
    ef="$tmp_dir/existingFiles"

    # Removing the '.extension', to compare
    # "$ef" file against the list of titles,
    # that do not contains extensions themself.
    command ls -N | sed -r "s/${EXTENSIONS}//" > "$ef"
    [[ ! -s $ef ]] && { rm "$ef"; return; }

    _ResizeWindow --main
    clear

    declare -i linenumbers
    attr=0
    match=0
    _BlankLine

    while read -r line; do
        if grep -q -Fx "$line" "$TITLES"; then
            echo \
            " ${task}$line ${critical}already exist in ${addPlaylistDir##*/}.${nc}"
            ((match++))
        fi
    done < "$ef"

    unset line

    mapfile -t efList < "$ef"
    rm "$ef"
    efCount="${#efList[@]}"
    mapfile -t titlesList < "$TITLES"
    titlesCount="${#titlesList[@]}"

    if ((match > 0)); then
        if ((titlesCount == match)) && ((efCount > titlesCount)); then
            # All playlist items have been downloaded already and
            # there are ALSO other files in the destination folder.
            _IfDuplicatesFilesMessages --if
            _IfDuplicatesFilesActions --if
        elif ((titlesCount == match)); then
            # All playlist items have been downloaded already and
            # there are NO other files in the destination folder.
            _IfDuplicatesFilesMessages --elif
            _IfDuplicatesFilesActions --elif
        else
            # Some of the titles match the filenames in the destination folder.
            # _IfDuplicatesFilesMessages --else,
            # is called from _IfDuplicatesFilesActions --else.
            _IfDuplicatesFilesActions --else
        fi
    else
        return
    fi

}
