#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_IfDuplicatesUrls() {

    [[ ! -s $URLS ]] && return

    local pl pls linenum
    declare -a collection=()
    pls=("$playlists_dir"/*.m3u)

    for pl in "${pls[@]}"; do
        if [[ $pl =~ default.m3u ]]; then
            continue
        else
            collection+=("$pl")
        fi
    done

    mapfile -t list_links < "$URLS"
    linenum=1
    declare -a lines_to_delete=()

    for line in "${list_links[@]}"; do
        for pls in "${collection[@]}"; do
            grep -qx "$line" "$pls" && {
                clear; _BlankLine
                printf '%s\n' \
                    " ${critical}The below URL is already present in your collection:" \
                    " Found in playlist: ${task}$(basename "${pls}")" \
                    " Removing: ${nc}$line"
                sleep 2
                lines_to_delete+=("$linenum")
                break
            }
        done
        ((linenum++))
    done

    # Delete lines in reverse order because of potential already existing lines.
    (( ${#lines_to_delete[@]} > 0 )) && {
        for ((idx=${#lines_to_delete[@]}-1; idx>=0; idx--)); do
            sed -i "${lines_to_delete[idx]}d" {"$TITLES","$URLS"}
        done
        printf '\n%s\n' " ${task}Removed ${#lines_to_delete[@]} duplicate URLs.${nc}"
        sleep 2
    }
    [[ ! -s $TITLES && ! -s $URLS ]] && rm {"$TITLES","$URLS"}

    unset pl pls line linenum collection lines_to_delete

}
