#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2001
_IfDuplicatesFilesMessages() {

    if ((titlesCount > 1)); then
        it="them"; link="links"
    else
        it="it"; link="link"
    fi

    case "$1" in
        --if)
            _BlankLine
            printf '%s\n' \
            " ${info}At least ${titlesCount} ${link} seem to have been downloaded already," \
            " (this means that there are also other files in ${addPlaylistDir##*/})."
            _Prompt " do you want to remove ${it} from the ${Type} list?${nc}" || {
                printf '\n%s\n' " ${info}Downloading duplicates is useless...${nc}"
                sleep 3; _CreateAddPlaylist "$arg"
            }
        ;;
        --elif)
            printf '\n%s\n' " ${info}All ${link} seem to have been downloaded already,"
            _Prompt " do you want to remove ${it} from the ${Type} list?${nc}" || {
                printf '\n%s\n' " ${info}Downloading duplicates is useless...${nc}"
                sleep 3; _CreateAddPlaylist "$arg"
            }
        ;;
        --else)
            _BlankLine
            printf '%s\n' \
            " ${info}${#linenumbers[@]} ${link} seem to have been downloaded already," \
            " if you want to remove ${it} from the current $Type list," \
            " copy this sequence: $(echo "${linenumbers[@]}" | sed 's/\s/,/g')" \
            " and paste it using the [R]emove links option in the next prompt ."
            unset linenumbers
            _BlankLine
            _Prompt " Do you want to remove ${it} from the ${Type} list?${nc}" || {
                printf '\n%s\n' " ${info}Downloading duplicates is useless...${nc}"
                sleep 3; _CreateAddPlaylist "$arg"
            }
        ;;
    esac

}
