#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_IfPartsExist() {

    __IfPartsExistInfo() (
        clear
        echo -e " ${critical}Incomplete files in audio/video directories:\n${nc}"
        find {"$audios_dir","$videos_dir"} -name "*.part" 2>/dev/null \
        | sort -d | sed 's,.*/,,' | cat -n
        __
        echo " ${info}Try again now or later, choose an option.${nc}"
        __
        return
    )

    case "$1" in
        -l)
            mv "$playlists_dir"/"$list"_origin \
            "$playlists_dir"/"$list"
            mv "$titles_dir"/"$list".titles_origin \
            "$titles_dir"/"$list".titles
            __IfPartsExistInfo
        ;;
        -t)
            tempFiles=( "$QUEUE" "$AUDIO_URLS" "$AUDIO_TITLES" \
                        "$VIDEO_URLS" "$VIDEO_TITLES" "$DEFAULTITLES" )

            for f in "${tempFiles[@]}"; do
                mv -f "$f"_origin "$f"
            done 2>/dev/null

            __IfPartsExistInfo
        ;;
    esac

}
