#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_IfPartsExist() {

    __ifPartsExistInfo() (
        clear
        echo -e " ${critical}Incomplete files in audio/video directories:\n${nc}"
        find "$mediaDir" -name "*.part" 2>/dev/null \
        | sort -d | sed 's,.*/,,' | nl
        echo -e "\n ${info}Try again now or later, choose an option.${nc}"
        sleep 3
        _BlankLine
        return
    )

    case "$1" in
        -l)
            mv "$playlists_dir"/"$list"_origin \
            "$playlists_dir"/"$list"
            mv "$titles_dir"/"$list".titles_origin \
            "$titles_dir"/"$list".titles
            __ifPartsExistInfo
        ;;
        -t)
            _RenameTmpFiles
            __ifPartsExistInfo
        ;;
    esac

}
