#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_IfPartsExist() {

    __IfPartsExistInfo() (
        echo -e " Incomplete files in audio/video directories:\n${nc}"
        find "$audios_dir"/"${list%.*}" "$videos_dir"/"${list%.*}" \
        -name "*.part" -name "*.part" 2>/dev/null \
        | sort -d | sed 's,.*/,,' | cat -n
        __
        echo " ${info}Keep them in if you want to resume downloads,"
        echo " and try again in this session or later.${nc}"
        sleep 10
        _Menu
    )
    
    case "$1" in
        -l)
            mv "$playlists_dir"/"$list"_origin \
            "$playlists_dir"/"$list"
            mv "$titles_dir"/"$list".titles_origin \
            "$titles_dir"/"$list".titles
            __IfPartsExistInfo
        ;;
        -t)
            tempfiles=( "$QUEUE" "$AUDIO_URLS" "$AUDIO_TITLES" \
                        "$VIDEO_URLS" "$VIDEO_TITLES" "$DEFAULTITLES" )
            
            for f in "${tempfiles[@]}"; do
                mv -f "$f"_origin "$f"
            done 2>/dev/null
            
            __IfPartsExistInfo
        ;;
    esac

}