#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_IfQuitAfterTask() {
    case "$1" in
        -d)
            if [[ $quit_after_task = yes ]]; then
                __
                if [[ -s "$AUDIO_URLS" || -s "$VIDEO_URLS" ]]; then
                    _SaveOnExit
                else
                    nc=$'\e[0m';
                    echo "${nc}"
                    clear
                    exit 0
                fi
            elif [[ $(awk -F= '/use_parallel_downloads/{gsub(/"/,""); print $2}' "$MPMRC") = yes ]]; then
                use_parallel_downloads="yes"
            fi
            _Menu
        ;;
        -x)
            __
            if [[ -s "$AUDIO_URLS" || -s "$VIDEO_URLS" ]]; then
                _SaveOnExit
            else
                nc=$'\e[0m';
                echo "${nc}"
                clear
                exit 0
            fi
        ;;
    esac
}
