#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_IfQuitAfterTask() {

    local quit
    case "$1" in
        -d)
            if [[ $quit_after_task == yes ]]; then
                _BlankLine
                if [[ -s "$AUDIO_URLS" || -s "$VIDEO_URLS" ]]; then
                    _SaveOnExit
                else
                    nc=$'\e[0m';
                    echo "${nc}"
                    clear
                    exit 0
                fi
            else
                _CheckParallelDownloads --after
                _Menu
            fi
        ;;
        -x)
            if [[ -s "$AUDIO_URLS" || -s "$VIDEO_URLS" ]]; then
                _SaveOnExit
            else
                nc=$'\e[0m';
                echo "${nc}"
                clear
                exit 0
            fi
        ;;
    esac

}
