#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_IfWebmFiles() {

    if [[ -n $(find "$mediaDir" -iname "*.webm") ]]; then

        _RemoveAudioVideoIds; _ResizeWindow -m; clear
        echo -e "\n ${critical}ADVISORY: if you choose conversion, all downloaded files (.webm)"
        echo -e " will be converted in the chosen format.${nc}\n"
        find "$mediaDir" -iname "*.webm" | sed 's,.*/,,' | sort | nl

        if [[ $automatic_audio_conversion = yes ]]; then
            printf '\n%s\n' " ${task}Automatic audio conversion enabled.${nc}"
            sleep 2
            [[ $M3UFILE == "$AUDIO_URLS" ]] || [[ $M3UFILE == "$DEFAULT_LIST" ]] \
            && _ConvertAudio && _GetCompleted
            [[ $M3UFILE == "$playlists_dir"/"$list" ]] || [[ $M3UFILE == "$SELECTED_URLS1" ]] \
            && _ConvertAudio && _DownloadCompleted
        else
            _BlankLine
            _Prompt " ${info}Proceed with conversion?:${nc}" || {
                mv ./*.webm "$MUSIC_DIR"
                printf '\n%s\n' " ${critical}All .webm files have been moved in $MUSIC_DIR.${nc}"
                sleep 1
                _BlankLine
                [[ $M3UFILE == "$AUDIO_URLS" ]] || [[ $M3UFILE == "$DEFAULT_LIST" ]] \
                && _GetCompleted
                [[ $M3UFILE = "$playlists_dir"/"$list" ]] || [[ $M3UFILE = "$SELECTED_URLS1" ]] \
                && _DownloadCompleted
            }
            [[ $M3UFILE == "$AUDIO_URLS" ]] || [[ $M3UFILE == "$DEFAULT_LIST" ]] \
            && _ConvertAudio && _GetCompleted
            [[ $M3UFILE == "$playlists_dir"/"$list" ]] || [[ $M3UFILE == "$SELECTED_URLS1" ]] \
            && _ConvertAudio && _DownloadCompleted
        fi

    else
        [[ $M3UFILE == "$AUDIO_URLS" ]] || [[ $M3UFILE == "$DEFAULT_LIST" ]] \
        && _GetCompleted
        [[ $M3UFILE == "$playlists_dir"/"$list" ]] || [[ $M3UFILE == "$SELECTED_URLS1" ]] \
        && _DownloadCompleted
    fi

}
