#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_IsMpmAlreadyRunning() {

    echo $$ >> "$MPM_PIDS"
    mapfile -t pids < "$MPM_PIDS"

    __killPids() {
        case "$1" in
            greaterThanOne)
                rm "$MPM_PIDS"
                kill -KILL "${pids[0]}"
            ;;
            greaterThanTwo)
                _KillMpv && _RemoveMpvTmp
                for ((i=0;i<=2;i++)); do
                    kill -KILL "${pids[${i}]}"
                done
            ;;
        esac
        # exit
    }

    __killPrompt() (
        # If the received string is 'n' or 'enter' then relaunching mpm will be aborded,
        # if the received string is 'y' then we kill mpm.
        # Same thing if we've launched mpv from mpm.
        printf '\n%s\n' " ${critical}${0##*/} is already running..."
        _Prompt -n " Do you want to kill ${0##*/}?${nc}"
    )

    # We only want ONE mpm running instance.
    if [[ -e $NOWPLAYING ]] && ((${#pids[@]} >= 3)); then
        # This test means that mpm is running, it also launched an mpv process
        # and the _WhileMpvIsRunning function which is in the background so we get
        # the right main menu options access.
        __killPrompt && {
            if ((${#pids[@]} > 2)); then
                _Prompt -n " ${critical}Mpv is also running, stop mpv?${nc}" \
                && rm "$MPM_PIDS" && __killPids greaterThanTwo
            fi
        }
        sed -i '$d' "$MPM_PIDS" 2>/dev/null
        exit
    elif [[ ! -e $NOWPLAYING ]] && ((${#pids[@]} == 2)); then
        # This test means that a mpm instance is running
        # and we're trying to launch another one, which we don't want to.
        __killPrompt && __killPids greaterThanOne
        sed -i '$d' "$MPM_PIDS" 2>/dev/null
        exit
    fi

}
