#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_LaunchMpm() {

    _BlankLine
    _Prompt " Launch ${0##*/}?" || {
        clear
        exit
    }

    editoption=no; _StartUp

}
