#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ListsCount() {

    __col() (
        if [[ -z $(find "$playlists_dir" -not -name "default.m3u" -name "*.m3u") ]]; then
           echo "0"
        else
            echo "${info}$(find "$playlists_dir" -not -name "default.m3u" \
            -iname "*.m3u" -printf '.' | wc -c)${nc}"
        fi
    )
    
    __def() (
        if [[ -f $tmp_dir/1 ]]; then
            echo "${critical}${b}$(_GetLinesList -q)${nb}${nc}"
        elif [[ $(_GetLinesList -q) -gt 0 ]]; then
            echo "${info}$(_GetLinesList -q)${nc}"
        else
            echo "0"
        fi
    )
    
    __aud() (
        if [[ -s $AUDIO_URLS ]]; then
            echo "${info}$(_GetLinesList -a)${nc}"
        else
            echo "0"
        fi
    )
    
    __vid() (
        if [[ -s $VIDEO_URLS ]]; then
            echo "${info}$(_GetLinesList -v)${nc}"
        else
            echo "0"
        fi
    )
    
    echo -e "                  ┌─────────────────────────────────────────────────────────────────────────────────────┐"
    echo -e "                           Collection: $(__col) * Default list: $(__def) * Audio list: $(__aud) * Video list: $(__vid)"
    echo -e "                  └─────────────────────────────────────────────────────────────────────────────────────┘"

}