#!/bin/bash
## This is a part of main script: mpm.

_ListsCount() {
    echo ""
    echo " ${green}Default list: $(_GetLinesList -q) url(s).${nocolor}"
    [[ -f "$AUDIO_INFO" ]] && \
        echo " ${green}Audio list:   $(_GetLinesList -a) url(s).${nocolor}"
    [[ -f "$VIDEO_INFO" ]] && \
        echo " ${green}Video list:   $(_GetLinesList -v) url(s).${nocolor}"
}
