#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ListsCount() {

    __
    echo " ${info}Collection:"  \
    "  $(find "$playlists_dir" -not -name "default.m3u" \
    -iname "*.m3u" -printf '.' | wc -c) playist(s)${nc}"

    if [[ -f $tmp_dir/1 ]]; then
        __
        echo " ${info}Default list: ${b}$(_GetLinesList -q)${nb} url(s).${nc}"
    elif (($(_GetLinesList -q) > 0)); then
        __
        echo " ${info}Default list: $(_GetLinesList -q) url(s).${nc}"
    fi

    [[ -f $AUDIO_INFO ]] && (($(_GetLinesList -a) > 0)) && \
        echo " ${info}Audio list:   $(_GetLinesList -a) url(s).${nc}"
    [[ -f $VIDEO_INFO ]] && (($(_GetLinesList -v) > 0)) && \
        echo -e " ${info}Video list:   $(_GetLinesList -v) url(s).${nc}\n"

}

