#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_LoadAudioVideo() {

    local m3uFile

    pidof mpv >/dev/null && {
        kill -SIGTERM "$(pidof mpv)"
        rm {"$(readlink -f "$NOWPLAYING")","$NOWPLAYING"} 2>/dev/null
        sleep 0.5
    }

    case "$1" in
        -a)
            if [[ -s $AUDIO_URLS ]]; then
                m3uFile="$AUDIO_URLS"
                _MpvcTest -a
            else
                echo " ${critical}No links in the $Type list${nc}"
                sleep 2 && return
            fi
        ;;
        -ca)
            m3uFile="$CHOOSE1"
            _MpvcTest -a
        ;;
        -cv)
            m3uFile="$CHOOSE1"
            _MpvcTest -v
        ;;
        -la)
            m3uFile="$playlists_dir/$list"
            _MpvcTest -a
        ;;
        -lv)
            m3uFile="$playlists_dir/$list"
            _MpvcTest -v
        ;;
        -qa)
            m3uFile="$QUEUE"
            _MpvcTest -a
        ;;
        -qv)
            m3uFile="$QUEUE"
            _MpvcTest -v
        ;;
        -v)
            if [[ -s $VIDEO_URLS ]]; then
                m3uFile="$VIDEO_URLS"
                _MpvcTest -v
            else
                echo " ${critical}No links in the $Type list${nc}"
                sleep 2 && return
            fi
        ;;
    esac
    
    _Menu
}
