#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2044
_LoadPlaylist() {

    cd "$playlists_dir" || exit 1

    local list titlesFile

    for lst in $(find . -type f -name "*_origin"); do
        mv -f "$lst" "${lst//_origin/}"
    done

    clear
    __
    PS3=""$'\n'" ${info}Select a playlist to load, [${mtitle}C${info}]ancel: ${nc}"
    select list in $(find . -type f -not -name "default.m3u" | sort -d | sed 's,.*/,,'); do

        [[ $REPLY =~ [a-zA-Z] ]] && break

        [[ $(_GetLinesList -l) -eq 0 ]] && {
            printf '%s\n' \
            " ${critical}No links found in $list (empty or does not contains #EXTM3U header)." \
            " You can edit and fix it in option 8) Edit a playlist.${nc}"
            sleep 8
            return
        }

        titlesFile="$titles_dir/$list.titles"
        clear
        printf '\n%s\n' \
        " ${info}Choose an option for: ${list%%.*//_/} ${nc}($(grep -c '^https' "$list") urls)"
        __
        read -rsn 1 -p " ${info}[1] Download/Play, [2] View titles, [${mtitle}C${info}]ancel: ${nc}" \
        loadPlaylistOptions
        __
        case "$loadPlaylistOptions" in
            1)
                clear; _LoadPlaylistMenu
            ;;
            2)
                clear

                if [[ $(grep "" -c "$titlesFile") -gt 25 ]]; then
                    _TitlesListCompare -g
                else
                    _TitlesListCompare -l
                fi

                read -rsn 1 \
                -p "${info}"' [1] Download/Play, [2] Back to menu: '"${nc}" loadPlaylistSubmenuOptions
                __
                case "$loadPlaylistSubmenuOptions" in
                    1) clear; _LoadPlaylistMenu ;;
                    2) break ;;
                    *)
                        _WrongOption "$loadPlaylistSubmenuOptions"
                        return
                    ;;
                esac
            ;;
            c|C) break ;;
            *)
                _WrongOption "$loadPlaylistOptions"
                return
            ;;
        esac

    done
}
