#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015,SC2034
_LoadAudioVideo() {

    local m3uFile use_mpvc_online
    use_mpvc_online="yes"

    __LoadAudioVideoAdvice() (
        clear
        __
        printf '%s\n' " ${critical}Tip: You may want to put this in your mpv.conf:" \
        " ${info}term-playing-msg='Tiltle: \${media-title}'"
        echo -e " ${critical}Otherwise press I in mpv for more infos.${nc}\n"
        file="${m3uFile##*/}" file="${file%%.*}"
        printf '%s\n' " ${info}Playing: ${file} playlist.${nc}"
        __
    )

    # change mpv settings in ~/.config/mpm/mpmrc
    __mpvOnlineAudioCommand() (
        if [[ $use_mpvc = yes ]]; then
            mpv \
            --no-terminal \
            "${mpvGenOptions_X[@]}" \
            "${mpvAudioFormatOptions[@]}" "$1" &
            echo "$m3uFile" > "$tmp_dir"/nowPlaying
        else
            __LoadAudioVideoAdvice
            mpv \
            "${mpvGenOptions_X[@]}" \
            "${mpvAudioFormatOptions[@]}" "$1"
            _LoadAudioVideoTmp -a
        fi
    )

    __mpvOnlineVideoCommand() (
        if [[ $use_mpvc = yes ]]; then
            mpv \
            --no-terminal \
            "${mpvGenOptions_X[@]}" \
            "${mpvVideoOptions_X[@]}" \
            "${mpvVideoFormatOptions[@]}" "$1" &
            echo "$m3uFile" > "$tmp_dir"/nowPlaying
        else
            __LoadAudioVideoAdvice
            mpv \
            "${mpvGenOptions_X[@]}" \
            "${mpvVideoOptions_X[@]}" \
            "${mpvVideoFormatOptions[@]}" "$1"
            _LoadAudioVideoTmp -v
        fi
    )

    case "$1" in
        -a)
            if [[ -s $AUDIO_URLS ]]; then
                m3uFile="$AUDIO_URLS"
                __mpvOnlineAudioCommand "$m3uFile"
            else
                echo " ${critical}No links in the $Type list${nc}"
                sleep 2 && return
            fi
        ;;
        -ca)
            m3uFile="$CHOOSE1"
            __mpvOnlineAudioCommand "$m3uFile"
        ;;
        -cv)
            m3uFile="$CHOOSE1"
            __mpvOnlineVideoCommand "$m3uFile"
        ;;
        -la)
            m3uFile="$playlists_dir/$list"
            __mpvOnlineAudioCommand "$m3uFile"
        ;;
        -lv)
            m3uFile="$playlists_dir/$list"
            __mpvOnlineVideoCommand "$m3uFile"
        ;;
        -qa)
            m3uFile="$QUEUE"
            __mpvOnlineAudioCommand "$m3uFile"
        ;;
        -qv)
            m3uFile="$QUEUE"
            __mpvOnlineVideoCommand "$m3uFile"
        ;;
        -v)
            if [[ -s $VIDEO_URLS ]]; then
                m3uFile="$VIDEO_URLS"
                __mpvOnlineVideoCommand "$m3uFile"
            else
                echo " ${critical}No links in the $Type list${nc}"
                sleep 2 && return
            fi
        ;;
    esac
    
    _Menu
}