#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_LoadLocalMenu() {

    local localDir file
    
    file="${m3uFile##*/}" file="${file%%.*}"

    __isFileManagerInstalled() (
        if ! command -v "$FILEMANAGER" >/dev/null; then
            printf '%s\n' " ${critical}$FILEMANAGER is not installed...!${nc}"
            sleep 3
        else
            clear;"$FILEMANAGER" "$localDir"
        fi
    )
    
    while :; do
        _ResizeWindow
        clear
        __
        echo -e "                                                 ${mtitle}::LOAD LOCAL OPTIONS::${nc}"
        echo -e "                                           $(_LittleStars)${nc}"
        echo -e "                                  ┌───────────────────────────────────────────────────┐"
        echo -e "                                  │   1) Single Audio dir     5) Explore Music dir    │"
        echo -e "                                  │   2) Audio files          6) Explore Videos dir   │"
        echo -e "                                  │   3) Single Video dir     7) Load multiple dirs   │"
        echo -e "                                  │   4) Video files          8) Back to main menu    │"
        echo -e "                                  └───────────────────────────────────────────────────┘"
        echo -e "                                                    ${info}${b}Select an item${nb}${nc}"
        __
        read -rsn 1
        case "$REPLY" in
            1|3)
                [[ $REPLY = 1 ]] && localDir="$MUSIC_DIR"
                [[ $REPLY = 3 ]] && localDir="$VIDEO_DIR"
                _ReplaceSpaces -l
                clear;__
                _SelectLocalDir -d
            ;;
            2|4)
                [[ $REPLY = 2 ]] && localDir="$MUSIC_DIR"
                [[ $REPLY = 4 ]] && localDir="$VIDEO_DIR"
                if [[ -n $(command -v fzf) && $use_fzf = yes ]]; then
                    clear;__;_SelectLocalDir -f;_Menu
                else
                    __isFileManagerInstalled
                fi
            ;;
            5|6)
                [[ $REPLY = 5 ]] && localDir="$MUSIC_DIR"
                [[ $REPLY = 6 ]] && localDir="$VIDEO_DIR"
                __isFileManagerInstalled
            ;;
            7)
                read -rsn 1 \
                -p " ${info}Queue multiple [A]udio or [V]ideo directories: ${nc}" \
                diranswer
                case "$diranswer" in
                    a|A) localDir="$MUSIC_DIR" ;;
                    v|V) localDir="$VIDEO_DIR" ;;
                    *) __; _WrongOption "$diranswer"; continue ;;
                esac
                _QueueMultipleDirs
            ;;
            8)  _Menu ;;
            *)
                _WrongOption "$REPLY"
                return
            ;;
        esac
    done

}
