#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_LoadAudioVideoAdvice() {
    clear
    __
    printf '%s\n' " ${critical}Tip: You may want to put this in your mpv.conf:" \
    " ${info}term-playing-msg='[Tiltle]: \${media-title}'"
    echo -e " ${critical}Otherwise press I in mpv for more infos, or Q to quit mpv.${nc}\n"

    if grep -q -e 'm3u' "$NOWPLAYING"; then
        file="${m3uFile##*/}" file="${file%%.*}"
        printf '%s\n' " ${info}Playing: ${file} playlist.${nc}"
        __
    else
        printf '%s\n' " ${info}Playing directory: ${dir}.${nc}"
        __
    fi
}
