#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_LoadPlaylistMenu() {

    cd "$playlists_dir" || exit 1
    while :; do
        _ResizeWindow
        clear
        [[ $direct_download = yes ]] && {
            __
            printf '%s\n' " ${task}Direct download enabled.${nc}"
        }
        __
        echo " ${info}$list: $(grep -c '^https' "$list") url(s).${nc}"
        __
        echo -e "                                                ${mtitle}::DOWNLOAD/PLAY OPTIONS::${nc}"
        echo -e "                                  ┌───────────────────────────────────────────────────┐"
        echo -e "                                  │     1) Choose playlist links & download ${info}audio${nc}     │"
        echo -e "                                  │     2) Choose playlist links & download ${info}video${nc}     │"
        echo -e "                                  │     3) Download whole playlist as ${info}audio${nc} files     │"
        echo -e "                                  │     4) Download whole playlist as ${info}video${nc} files     │"
        echo -e "                                  │     5) Choose playlist links & play ${info}audio/video${nc}   │"
        echo -e "                                  │     6) Back to main menu                          │"
        echo -e "                                  └───────────────────────────────────────────────────┘"
        echo -e "                                                    ${info}${b}Select an item${nb}${nc}"
        __
        read -rsn 1 loadPlaylistMenuOptions
        case "$loadPlaylistMenuOptions" in
            1)
                _ChooseDownloadAudio
            ;;
            2)
                _ChooseDownloadVideo
            ;;
            3)
                _GetAudio -l
            ;;
            4)
                _DownloadVideoList
            ;;
            5)
                _ChooseFromPlay
            ;;
            6)
                _Menu
            ;;
            *)
                printf '%s\n' " ${critical}Wrong option $loadPlaylistMenuOptions..."
                sleep 3s && _Menu
            ;;
        esac
    done

}