#!/bin/bash
## This is a part of main script: mpv-menu.

_LoadAudio() {
    clear
    echo ""
    echo "${red}Tip: You may want to put this in your mpv.conf:"
    printf '%s\n' "term-playing-msg='Tiltle: \${media-title}'"
    echo "Otherwise press I in mpv for more infos.${nocolor}"
    echo ""
    
    case "$1" in
        -a) mpv --no-video "$AUDIO_INFO" 
            [[ -f "$AUDIO_INFO" ]] && {
                read -rsn 1 -p ${red}' Temporary audio list still exist, keep it? [Y/n]:'${nocolor} keep
                case "$keep" in
                    y|Y)    _Menu ;;
                    n|N)    rm "$AUDIO_INFO"
                            _Menu ;;
                esac
            } || _CleanTmpDir; _Menu ;;
        -q) mpv --no-video "$QUEUE" ;;
        -l) mpv --no-video "$list" ;;
    esac
    
}
         
