#!/bin/bash
## This is a part of main script: mpm.

_LoadVideo() {

    clear

    _MpvVideoOptions() (
        # change mpv settings here if needed
        mpv \
        --input-ipc-server='/tmp/mpvsocket' \
        --cache \
        --no-config \
        --term-playing-msg='Title: ${media-title}' \
        --ytdl-format='299+251/298+251/137+251/136+251/best' "$M3UFILE"
    )

    local M3UFILE

    case "$1" in
        -v)
            M3UFILE="$VIDEO_INFO" ;;
        -q)
            M3UFILE="$QUEUE" ;;
        -l)
            M3UFILE="$list" ;;
        -c)
            M3UFILE="$CHOOSE1" ;;
    esac

    __
    echo "${r}Tip: You may want to put this in your mpv.conf:"
    printf '%s\n' "term-playing-msg='Tiltle: \${media-title}'"
    echo -e "Otherwise press I in mpv for more infos.${nc}\n"
    __
    _MpvVideoOptions

    if [[ -f "$VIDEO_INFO" ]]; then
        clear
        __
        echo " ${r}Did you launched video(s) from the default list?"
        echo " or from option 4) Load a playlist?"
        echo " If so, type ${b}${c}Y${nb} ${r}to preserve temporary video list${nc}"
        __

        declare -a TMP=( "$VIDEO_INFO" "$VIDEO_TITLE" "$FFOP" \
                        "$YTOP" "$CHOOSE1" "$tmp_dir/CheckCode" )

        _Prompt " ${g}Temporary video list still exist, KEEP it?:${nc}" || {
            rm -f "${TMP[@]}" 2>/dev/null
            echo " ${r}Temporary video list removed...${nc}"
            sleep 3
        }
        __
    elif [[ -f $CHOOSE1 ]]; then
        rm -f "$CHOOSE1" "$list"_origin 2>/dev/null
    else
        rm -f "${TMP[@]}" 2>/dev/null
    fi
    _Menu
}
