#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_LoadLocalMenu() {

    local AUDIOS VIDEOS localDir file
    # we use -maxdepth 2 in case our directories are in subdirectories.
    # like ~/Documents/Music instead of ~/Music
    AUDIOS=$(find "$HOME" -maxdepth 2 -type d -wholename "$MUSIC_DIR")
    VIDEOS=$(find "$HOME" -maxdepth 2 -type d -wholename "$VIDEO_DIR")
    file="${m3uFile##*/}" file="${file%%.*}"

    __isFileManagerInstalled() (
        if ! command -v "$FILEMANAGER" >/dev/null; then
            printf '%s\n' " ${critical}$FILEMANAGER is not installed...!${nc}"
            sleep 3
        else
            clear;"$FILEMANAGER" "$localDir"
        fi
    )
    
    while :; do
        _ResizeWindow
        clear
        __
        echo -e "                                                 ${mtitle}::LOAD LOCAL OPTIONS::${nc}"
        echo -e "                                  ┌───────────────────────────────────────────────────┐"
        echo -e "                                  │    1) Audio directory     2) Audio files          │"
        echo -e "                                  │    3) Video directory     4) Video files          │"
        echo -e "                                  │    5) Explore Music dir   6) Explore Videos dir   │"
        echo -e "                                  │    7) Cancel                                      │"
        echo -e "                                  └───────────────────────────────────────────────────┘"
        echo -e "                                                    ${info}${b}Select an item${nb}${nc}"
        __
        read -rsn 1
        case "$REPLY" in
            1|3)
                [[ $REPLY = 1 ]] && localDir="$AUDIOS"
                [[ $REPLY = 3 ]] && localDir="$VIDEOS"
                _ReplaceSpaces -l
                clear;__
                _SelectLocalDir -d
            ;;
            2|4)
                [[ $REPLY = 2 ]] && localDir="$AUDIOS"
                [[ $REPLY = 4 ]] && localDir="$VIDEOS"
                if [[ -n $(command -v fzf) && $use_fzf = yes ]]; then
                    clear;__;_SelectLocalDir -f;_Menu
                else
                    __isFileManagerInstalled
                fi
            ;;
            5|6)
                [[ $REPLY = 5 ]] && localDir="$AUDIOS"
                [[ $REPLY = 6 ]] && localDir="$VIDEOS"
                __isFileManagerInstalled
            ;;
            7) 
                if [[ -f "$FZFENQUEUE" ]]; then
                    use_mpvc_locally="yes"
                    mpv --no-terminal "${mpvGenOptions_SK[@]}" \
                    "${mpvGenOptions_ID[@]}" "$FZFENQUEUE" &
                    ln -sfr "$FZFENQUEUE" "$NOWPLAYING"
                    _WhileMpvIsRunning &
                else
                    _Menu
                fi
            ;;
            *)
                _WrongOption "$REPLY"
                return
            ;;
        esac
    done

}
