#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_LoadPlaylistMenu() {

    cd "$playlists_dir" || return
    M3UFILE="$list"
    local playlistMenuOptions

    __testList() {

        [[ $playerTitlesList == "$titles_dir/$list.titles" || -f $tmp_dir/list_tmp ]] && {

            echo -e " ${critical}mpv owns $list playlist...\n"
            read -rsn 1 \
            -p " ${info}[${mtitle}C${info}]ancel download, [Q]uit mpv: ${nc}" testListOptions

            case "$testListOptions" in
                c|C) _Menu ;;
                q|Q)
                    unset playerTitlesList
                    _killMpv
                    _Menu
                ;;
                *)
                    _WrongOption "$testListOptions"
                    return
                ;;
            esac

        }

    }

    _ResizeWindow --main
    clear
    _DownloadMessages --menu

    while :; do
        [[ -f $M3UFILE ]] && \
        echo -e "\n ${info}Options for: ${M3UFILE%%.*//_/} ${nc}($(grep -c '^https' "$M3UFILE") urls)\n\n"
        echo -e "                                                ${mtitle}::DOWNLOAD/PLAY OPTIONS::${nc}"
        echo -e "                                           $(_LittleStars)${nc}"
        echo -e "                                  ┌───────────────────────────────────────────────────┐"
        echo -e "                                  │     1) Choose playlist titles & download ${info}audio${nc}    │"
        echo -e "                                  │     2) Choose playlist titles & download ${info}video${nc}    │"
        echo -e "                                  │     3) Download whole playlist as ${info}audio${nc} files     │"
        echo -e "                                  │     4) Download whole playlist as ${info}video${nc} files     │"
        echo -e "                                  │     5) Choose playlist titles & play ${info}audio/video${nc}  │"
        echo -e "                                  │     6) Back to main menu                          │"
        echo -e "                                  └───────────────────────────────────────────────────┘"
        echo -e "                                                    ${info}${b}Select an item${nb}${nc}\n"

        read -rsn 1 loadPlaylistMenuOptions

        case "$loadPlaylistMenuOptions" in
            1) __testList; _CheckParallelDownloads --before; _ChooseDownloadAudio ;;
            2) __testList; _CheckParallelDownloads --before; _ChooseDownloadVideo ;;
            3) __testList; _CheckParallelDownloads --before; _GetAudio -l ;;
            4) __testList; _CheckParallelDownloads --before; _DownloadVideoList ;;
            5) _MpvOwnsTmpList --collection || _ChooseFromPlay ;;
            6) _Menu ;;
            r|R) continue ;;
            *) _WrongOption "$loadPlaylistMenuOptions" ;;
        esac

    done

}
