#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_LoadLocalMenuActions() {

    local localDir localMediaType

    __isFileManagerInstalled() (
        if ! _Has "$FILEMANAGER"; then
            printf '%s\n' " ${critical}$FILEMANAGER is not installed...!${nc}"
            sleep 3
        else
            clear
            "$FILEMANAGER" "$localDir"
        fi
    )

    __settingLoadLocalVars() {
        if [[ $1 == '-a' ]]; then
            localDir="$MUSIC_DIR"
            [[ -z $use_mpvc ]] && localMediaType=audio
        else
            localDir="$VIDEO_DIR"
            [[ -z $use_mpvc ]] && localMediaType=video
        fi
    }

    case "$1" in
        --explore)
            [[ $loadLocalMenuOptions == 5 ]] && localDir="$MUSIC_DIR"
            [[ $loadLocalMenuOptions == 6 ]] && localDir="$VIDEO_DIR"
            __isFileManagerInstalled
        ;;
        --files)
            _MpvOwnsTmpList --local || {
                if [[ $loadLocalMenuOptions == 2 ]]; then
                    __settingLoadLocalVars -a
                elif [[ $loadLocalMenuOptions == 4 ]]; then
                    __settingLoadLocalVars -v
                fi
                if _TestFzfCommand; then
                    clear; _BlankLine; _SelectLocalDir -f; _Menu
                else
                    clear; _BlankLine; _SelectLocalDir -n; _Menu
                fi
            }
        ;;
        --multiple-dirs)
            _MpvOwnsTmpList --local || {
                _BlankLine
                declare -a multipleDirsOptions=(
                    "${info}[${mtitle}C${info}]ancel,"
                    "Queue multiple [A]udio or"
                    "[V]ideo directories: ${nc}"
                )
                read -rsn 1 -p " ${multipleDirsOptions[*]}" diranswer
                case "$diranswer" in
                    [aA]) __settingLoadLocalVars -a ;;
                    [vV]) __settingLoadLocalVars -v ;;
                    [cC]) return ;;
                    *   ) _BlankLine; _WrongOption "$diranswer"; return ;;
                esac
                _QueueMultipleDirs
            }
        ;;
        --radio-dir)
            _MpvOwnsTmpList --local || {
                if [[ -n $radios_dir ]]; then
                    localDir="$radios_dir"
                    if _TestFzfCommand; then
                        clear; _FzfEnqueue
                    else
                        localMediaType=radio
                        _SelectLocalFiles "$radios_dir"
                    fi
                else
                    printf '%s\n' " ${critical}radios_dir isn't defined in mpmrc.${nc}"
                    sleep 3; __isFileManagerInstalled
                fi
            }
        ;;
        --single-dir)
            _MpvOwnsTmpList --local || {
                if [[ $loadLocalMenuOptions == 1 ]]; then
                    __settingLoadLocalVars -a
                elif [[ $loadLocalMenuOptions == 3 ]]; then
                    __settingLoadLocalVars -v
                fi
                _ReplaceSpaces -l
                clear
                _BlankLine
                _SelectLocalDir -d
            }
        ;;
        --somabox)
            if _Has somabox && [[ $use_somabox == yes ]]; then
                _MpvOwnsTmpList --local || somabox
            else
                _BlankLine
                printf '%s\n' " ${critical}use_somabox is set to 'no' in mpmrc" \
                    " or the somabox script isn't in you \$PATH..." \
                    " unabled to launch the player.${nc}"
                sleep 7; return
            fi
        ;;
    esac

}
