#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_LoadLocal() {

    local AUDIOS VIDEOS MEDIA_DIR file
    # we use -maxdepth 2 in case our directories are in subdirectories.
    # like ~/Documents/Music instead of ~/Music
    AUDIOS=$(find "$HOME" -maxdepth 2 -type d -wholename "$MUSIC_DIR")
    VIDEOS=$(find "$HOME" -maxdepth 2 -type d -wholename "$VIDEO_DIR")
    file="${m3uFile##*/}" file="${file%%.*}"

    read -rsn 1 \
    -p " ${info}[C]ancel, Play: [1] Audio dir, [2] Audio files, [3] Video dir or [4] Video files?: ${nc}"

    case "$REPLY" in
        1|3)
            [[ $REPLY = 1 ]] && MEDIA_DIR="$AUDIOS"
            [[ $REPLY = 3 ]] && MEDIA_DIR="$VIDEOS"
            _ReplaceSpaces -l
            clear;__
            _SelectLocalDir -d
        ;;
        2|4)
            [[ $REPLY = 2 ]] && MEDIA_DIR="$AUDIOS"
            [[ $REPLY = 4 ]] && MEDIA_DIR="$VIDEOS"
            if [[ -n $(command -v fzf) && $use_fzf = yes ]]; then
                clear;__; _SelectLocalDir -f; _Menu
            else
                clear; "$FILEMANAGER" "$MEDIA_DIR"; _Menu
            fi
        ;;
        c|C) return ;;
        *)
            _WrongOption "$REPLY"
            return
        ;;
    esac

}
