#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015
_LoadAudioVideoTmp() {

    declare -a TMP=( "$AUDIO_URLS" "$AUDIO_TITLES" "$VIDEO_URLS" \
                    "$VIDEO_TITLES" "$CHOOSE1" "$FFOP" "$YTOP" )
    
    __loadAudioVideoTmpNotice() (
        clear
        __
        _Prompt " ${info}$tmpFile list still exist, KEEP it?:${nc}" || {
            rm -f "${TMP[@]}" 2>/dev/null
            echo " ${critical}$tmpFile list removed...${nc}"
            sleep 3
        }
    )

    case "$1" in
        -a)
            if [[ -s ${TMP[0]} ]]; then

                if [[ -n $(pidof mpv) && -f $CHOOSE1 ]]; then
                    unset {TMP[2],TMP[3],TMP[4]}
                else
                    unset {TMP[2],TMP[3]}
                fi

                tmpFile=Audio
                __loadAudioVideoTmpNotice
            fi
            return
        ;;
        -v)
            if [[ -s ${TMP[2]} ]]; then
            
                if [[ -n $(pidof mpv) && -f $CHOOSE1 ]]; then
                    unset {TMP[0],TMP[1],TMP[4]}
                else
                    unset {TMP[0],TMP[1]}
                fi

                tmpFile=Video
                __loadAudioVideoTmpNotice
            fi
            return
        ;;
    esac
    
    [[ $quit_after_task = yes ]] && exit || _Menu

}
