#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2034,SC2154,SC2015
_LoadAudio() {
    # change mpv settings in ~/.config/mpmrc
    local M3UFILE

    __AdviceAudio() (
        clear
        __; rm -f "$tmp_dir"/download 2>/dev/null
        echo "${critical}Tip: You may want to put this in your mpv.conf:"
        printf '%s\n' "term-playing-msg='Tiltle: \${media-title}'"
        echo "Otherwise press I in mpv for more infos.${nc}"
        __
    )

    # change mpv settings in ~/.config/mpm/mpmrc
    case "$1" in
        -a)
            if [[ -f $AUDIO_INFO ]]; then
                M3UFILE="$AUDIO_INFO"
                __AdviceAudio
                _MpvAudioOptions
                _Prompt " ${info}Temporary audio list still exist, KEEP it?: ${nc}" || {
                    rm {"$AUDIO_INFO","$AUDIO_TITLE"}
                }
                _Menu
            else
                echo " ${critical}No links in the list${nc}"
                sleep 2 && _CopyAudio
            fi
        ;;
        -c)
            M3UFILE="$CHOOSE1"
            __AdviceAudio
            _MpvAudioOptions
            rm "$CHOOSE1"
            [[ $quit_after_task = yes ]] && exit || _Menu
        ;;
        -l)
            M3UFILE="$list"
            __AdviceAudio
            _MpvAudioOptions
            [[ $quit_after_task = yes ]] && exit || _Menu
        ;;
        -q)
            M3UFILE="$QUEUE"
            __AdviceAudio
            _MpvAudioOptions
            _Menu
        ;;
    esac

}
