#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MakeMpvPlaylistIndexes() {

    cd "$tmp_dir" && {
        local index
        index=0
        while read -r line; do
            echo "$index ${line##*/}" >> playerIndexesList
            ((index++))
        done < "$playerTitlesList"
        unset line index
        echo "Starting NAtive Mpm Player..." > playerSelectedFile
    }

}
