#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MakeMpvPlaylistIndexes() {

    local index
    index=0

    while read -r line; do
        echo "$index ${line##*/}" >> "$tmp_dir"/playerIndexesList
        ((index++))
    done < "$playerTitlesList"

    _RemoveDuplicateLines "$tmp_dir"/playerIndexesList
    unset line index

}
