#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_MakeMpvPlaylist() {
    # change mpv settings in ~/.config/mpm/mpmrc
    makeMpvPlaylistAudiOptions=(
        "${mpvGenOptions_X[@]}"
        "${mpvAudioFormatOptions[@]}"
    )

    makeMpvPlaylistVideOptions=(
        "${mpvGenOptions_X[@]}"
        "${mpvVideoOptions_X[@]}"
        "${mpvVideoFormatOptions[@]}"
    )

    case "$1" in
        --fzf)
            if [[ $localDir == "$radios_dir" ]]; then
                mpv --no-terminal --force-window=no \
                "${mpvGenOptions_X[@]}" "$m3uFile" &
                _WhileMpvIsRunning &
                _Menu
            elif [[ $localMediaType =~ audio|video ]]; then
                # use-mpvc is set to no or is empty
                clear
                _LoadAudioVideoAdvice
                mpv "${mpvGenOptions_X[@]}" "$m3uFile"
            else
                playerTitlesList="$tmp_dir/multipleFilesTitles"
                mpv --no-terminal "${mpvGenOptions_X[@]}" "$m3uFile" &
                _MpvSocketCommands --playlist
                _MakeMpvPlaylistIndexes
                _WhileMpvIsRunning &
                _Menu
            fi
        ;;
        --local-background)
            cd "$localDir"/"$dir" && {
                use_mpvc_locally="yes"
                localPlaylist="yes"
                playerTitlesList="$tmp_dir/singleDirTitles"
                find . -type f | sort | sed 's,.*/,,' \
                | mpv --no-terminal "${mpvGenOptions_X[@]}" --playlist=- &
                _MpvSocketCommands --playlist
                _MakeMpvPlaylistIndexes
                ln -sfr "$playerTitlesList" "$NOWPLAYING"
                _WhileMpvIsRunning &
            }
        ;;
        --local-foreground)
            cd "$localDir"/"$dir" && {
                use_mpvc_locally="no"
                echo "local-foreground" > "$NOWPLAYING"
                _LoadAudioVideoAdvice
                find . -type f | sort | sed 's,.*/,,' \
                | mpv "${mpvGenOptions_X[@]}" --playlist=-
                _RemoveMpvTmp
            }
        ;;
        --local-dirs)
            # used by _QueueMultipleDirs function
            mpv --no-terminal \
            "${mpvGenOptions_X[@]}" \
            "${mpvVideoOptions_FS[@]}" "$m3uFile" &
            _WhileMpvIsRunning &
        ;;
        --online-audio) _MakeMpvPlaylistOnline --audio ;;
        --online-video) _MakeMpvPlaylistOnline --video ;;
        --terminal-audio)
            _LoadAudioVideoAdvice
            mpv "${makeMpvPlaylistAudiOptions[@]}" "$m3uFile"
            _RemoveMpvTmp
        ;;
        --terminal-video)
            _LoadAudioVideoAdvice
            mpv "${makeMpvPlaylistVideOptions[@]}" "$m3uFile"
            _RemoveMpvTmp
        ;;
    esac

}
