#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ManualsMenu() {

    local fzfCmd ytfzfCmd mpvTui

    ! _Has fzf && fzfCmd="${critical}fzf${nc}" \
        || fzfCmd="fzf"
    ! _Has ytfzf && ytfzfCmd="${critical}ytfzf${nc}" \
        || ytfzfCmd="ytfzf"
    [[ -z $mpvc_tui_cheatsheet ]] && mpvTui="${critical}Mpv TUI shortcuts${nc}" \
        || mpvTui="Mpv TUI shortcuts"

    while :; do
        _ResizeWindow --main
        clear
        echo -e "\n                                                ${mtitle}::${B}MANUALS & HELP OPTIONS::${NB}${nc}"
        echo -e "                                           $(_LittleStars)${nc}"
        printf '%s\n' \
        " ${critical}                                   Some of these options might help to configure mpmrc${nc}"
        echo -e "                                    ┌─────────────────────────────────────────────────┐"
        echo -e "                                    │     1) Man ffmpeg      6) $mpvTui     │"
        echo -e "                                    │     2) Man $fzfCmd         7) Man mpm               │"
        echo -e "                                    │     3) Man mpv         8) Mpm shortcuts         │"
        echo -e "                                    │     4) Man yt-dlp      9) Edit mpm configs      │"
        echo -e "                                    │     5) Man $ytfzfCmd       X) Back to main menu     │"
        echo -e "                                    └─────────────────────────────────────────────────┘"
        echo -e "                                                     ${info}${b}Select an option${nb}${nc}\n"

        read -rsn 1 manualsMenuOptions

        case "$manualsMenuOptions" in
            1) man ffmpeg ;;
            2) man fzf ;;
            3) man mpv ;;
            4) man yt-dlp ;;
            5) man ytfzf ;;
            6) less "$mpvc_tui_cheatsheet" ;;
            7) man mpm ;;
            8) _MpmHelp -b ;;
            9) _EditMpmConf -m ;;
            [bBxX]) break ;;
            *) _WrongOption "$manualsMenuOptions" ;;
        esac

    done

}
