#!/bin/bash
## This is a part of main script: mpm.

# shellcheck source=/dev/null
# shellcheck disable=SC2154
_Menu() {
    cd "$main_dir" || exit 1
    _ResizeWindow
    while [[ -e $DEFAULT_LIST ]]; do
        _MenuHeader
        _MenuBoby
        _MenuOptions
    done
}
