#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_Menu() {
    # First copy url then select option 1 or 2,
    # the link will be saved in an m3u file.
    while [[ -e $QUEUE ]]; do
        _ResizeWindow
        clear
        _ListsCount
        __
        echo -e "                                         ${mtitle}::MPV-PLAYLISTS-MANAGER OPTIONS::"
        echo -e "                                           $VERSION ${info}For usage: mpm --help${nc}"
        echo -e "                             ${critical}For a better display consider a terminal size of 1210x735${nc}"
        echo -e "                ┌─────────────────────────────────────────────────────────────────────────────────────┐"
        echo -e "                │  1) Create/Add video playlist   6) View default playlist   │  ${info}Tasks for option 4)${nc}:  │"
        [[ $direct_download = yes ]] && echo -e "                │  2) Create/Add audio playlist   7) Clear all tmp lists     │  direct download: $direct_download  │"
        [[ $direct_download = no ]] && echo -e "                │  2) Create/Add audio playlist   7) Clear all tmp lists     │  direct download:  $direct_download  │"
        [[ $automatic_audio_conversion = yes ]] && echo -e "                │  3) Save as/Delete a playlist   8) Edit a playlist         │  conversion auto: $automatic_audio_conversion  │"
        [[ $automatic_audio_conversion = no ]] && echo -e "                │  3) Save as/Delete a playlist   8) Edit a playlist         │  conversion auto:  $automatic_audio_conversion  │"
        if [[ -z $default_conversion_format ]]; then echo -e "                │  ${info}4)${nc} Play/Download a playlist    9) Edit mpm config (mpmrc) │  audio format:  unset  │"; \
        elif [[ $default_conversion_format != flac ]]; then echo -e "                │  ${info}4)${nc} Play/Download a playlist    9) Edit mpm config (mpmrc) │  audio format:    $default_conversion_format  │"; \
        elif [[ $default_conversion_format = flac ]]; then echo -e "                │  ${info}4)${nc} Play/Download a playlist    9) Edit mpm config (mpmrc) │  audio format:   $default_conversion_format  │"; fi
        [[ $quit_after_task = yes ]] && echo -e "                │  5) Load local folder/files     X) Exit                    │  quit after task: $quit_after_task  │"
        [[ $quit_after_task = no ]] && echo -e "                │  5) Load local folder/files     X) Exit                    │  quit after task:  $quit_after_task  │"
        echo -e "                └─────────────────────────────────────────────────────────────────────────────────────┘"
        [[ -f $tmp_dir/1 ]] \
            && echo -e "                                                   ${info}Select an item${nc}" \
            || echo -e "                                                   ${info}${b}Select an item${nc}${nb}"
        __
        read -rsn 1 action
        case "$action" in
            1)  _CopyVideo
                __ ;;
            2)  _CopyAudio
                __ ;;
            3)  _SaveRemove
                __ ;;
            4)  _LoadPlaylist
                __ ;;
            5)  _LoadLocal
                __ ;;
            6)  _ViewUrlInfo -q
                __ ;;
            7)  _DeleteUrl
                __ ;;
            8)  _EditPlaylist
                __ ;;
            9)  _EditMpmConf
                __ ;;
            x|X)    if [[ -f "$AUDIO_INFO" || -f "$VIDEO_INFO" ]]; then
                        _Prompt -n \
                            " ${critical}Some temporary lists aren't saved, quit anyway?: ${nc}" && {
                            exit
                        }
                        continue
                    else
                        exit
                    fi
                    ;;
        esac
    done

}

