#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_MenuBobySettings() {

    local varConv varDirect varFmt varFzf varMpvc varParallel varQuit

    if [[ -z $use_mpvc ]]; then
        varMpvc="${critical}  !!!${nc}"
    elif [[ $use_mpvc == yes ]]; then
        varMpvc="${task}  $use_mpvc${nc}"
    elif [[ $use_mpvc == no ]]; then
        varMpvc="${critical}   $use_mpvc${nc}"
    else
        varMpvc="${task}unset${nc}"
    fi

    if [[ -z $use_fzf ]]; then
        varFzf="${critical}  !!!${nc}"
    elif [[ $use_fzf == yes ]]; then
        varFzf="${task}  $use_fzf${nc}"
    else
        varFzf="${critical}   $use_fzf${nc}"
    fi

    if [[ -z $use_parallel ]]; then
        varParallel="${critical}  !!!${nc}"
    elif [[ $use_parallel == yes && $use_parallel_downloads == no ]]; then
        varParallel="${critical}  yes${nc}"
    elif [[ $use_parallel == yes ]]; then
        varParallel="${task}  $use_parallel${nc}"
    else
        varParallel="${critical}   $use_parallel${nc}"
    fi

    if [[ -z $direct_download ]]; then
        varDirect="${critical} !!!${nc}"
    elif [[ $direct_download == yes ]]; then
        varDirect="${task} $direct_download${nc}"
    else
        varDirect="${critical}  $direct_download${nc}"
    fi

    if [[ -z $automatic_audio_conversion ]]; then
        varConv="${critical} !!!${nc}"
    elif [[ $automatic_audio_conversion == no && -n $default_conversion_format ]]; then
        varConv="${critical}  $automatic_audio_conversion${nc}"
    elif [[ $automatic_audio_conversion == no && -z $default_conversion_format ]]; then
        varConv="${critical}  $automatic_audio_conversion${nc}"
    elif [[ $automatic_audio_conversion == yes && -z $default_conversion_format ]]; then
        varConv="${critical} $automatic_audio_conversion${nc}"
    else
        varConv="${task} $automatic_audio_conversion${nc}"
    fi

    if [[ -z $default_conversion_format ]]; then
        varFmt="${critical}  unset${nc}"
    elif [[ $default_conversion_format == flac ]]; then
        varFmt="${task}   $default_conversion_format${nc}"
    else
        varFmt="${task}    $default_conversion_format${nc}"
    fi

    if [[ $quit_after_task == yes ]]; then
        varQuit="${task}${critical}$quit_after_task${nc}"
    else
        varQuit="${task} $quit_after_task${nc}"
    fi

    _MenuBoby

}
