#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MenuBoby() {

    echo -e "                   │       ${critical}For usage type U, for keyboard shortcuts type B${nc}      │  use mpvc:      ${varMpvc}  │"
    echo -e "                   │  ────────────────────────────────────────────────────────  │  use fzf:       ${varFzf}  │"
    echo -e "                   │  1)  Create/Add video playlist  6)  View default playlist  │  use parallel:  ${varParallel}  │"
    echo -e "                   │  2)  Create/Add audio playlist  7)  Clear all tmp lists    │  direct download:${varDirect}  │"
    echo -e "                   │  3)  Save as/Delete a playlist  8)  Edit a playlist        │  conversion auto:${varConv}  │"
    echo -e "                   │  4)  Play/Download a playlist   ${mtitle}9)${nc}  Edit mpm config file   │  audio format:${varFmt}  │"
    echo -e "                   │  5)  Load local folder/files    X)  Exit                   │  quit after task: ${varQuit}  │"
    echo -e "                   └─────────────────────────────────────────────────────────────────────────────────────┘"
    _PidOfMpv >/dev/null && _MenuFooter
    test -f "$tmp_dir"/1 \
        && echo -e "                                                      ${info}Select an item${nc}" \
        || echo -e "                                                      ${info}${b}Select an item${nb}${nc}"
    __

}