#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_MenuBobySettings() {

    local varConv varDirect varFmt varFzf varMpvc varParallel varQuit

    if [[ $use_mpvc == yes ]]; then
        varMpvc="${task}  $use_mpvc${nc}"
    elif [[ $use_mpvc == no ]]; then
        varMpvc="${task}   $use_mpvc${nc}"
    else
        varMpvc="${task}unset${nc}"
    fi

    if [[ $use_fzf == yes ]]; then
        varFzf="${task}  $use_fzf${nc}"
    else
        varFzf="${task}   $use_fzf${nc}"
    fi

    if [[ $use_parallel == yes ]]; then
        varParallel="${task}  $use_parallel${nc}"
    else
        varParallel="${task}   $use_parallel${nc}"
    fi

    if [[ $direct_download == yes ]]; then
        varDirect="${task} $direct_download${nc}"
    else
        varDirect="${task}  $direct_download${nc}"
    fi

    if [[ $automatic_audio_conversion == yes ]]; then
        varConv="${task} $automatic_audio_conversion${nc}"
    else
        varConv="${task}  $automatic_audio_conversion${nc}"
    fi

    if [[ -z $default_conversion_format ]]; then
        varFmt="${task}  unset${nc}"
    elif [[ $default_conversion_format != flac ]]; then
        varFmt="${task}    $default_conversion_format${nc}"
    else
        varFmt="${task}   $default_conversion_format${nc}"
    fi

    if [[ $quit_after_task == yes ]]; then
        varQuit="${task}$quit_after_task${nc}"
    else
        varQuit="${task} $quit_after_task${nc}"
    fi

    _MenuBoby
}