#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MenuBoby() {

    printf '%s\n' "                   │       ${critical}For usage type U, for keyboard shortcuts type B${nc}      │  use mpvc:      ${varMpvc}  │" \
    "                   │  ────────────────────────────────────────────────────────  │  use fzf:       ${varFzf}  │" \
    "                   │  1)  Create/Add video playlist  6)  View default playlist  │  use parallel:  ${varParallel}  │" \
    "                   │  2)  Create/Add audio playlist  7)  Clear all tmp lists    │  direct download:${varDirect}  │" \
    "                   │  3)  Save as/Remove a playlist  8)  Edit a playlist        │  conversion auto:${varConv}  │" \
    "                   │  4)  Play/Download playlist(s)  ${mtitle}9)${nc}  Edit mpm config files  │  audio format:${varFmt}  │" \
    "                   │  5)  Load local folder/files    X)  Exit                   │  quit after task: ${varQuit}  │" \
    "                   └─────────────────────────────────────────────────────────────────────────────────────┘"
    _PidOfMpv >/dev/null 2>&1 && _MenuFooter
    test -f "$tmp_dir"/1 \
        && echo -e "                                                     ${info}Select an option${nc}\n" \
        || echo -e "                                                     ${info}${b}Select an option${nb}${nc}\n"

}
