#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MenuOptions() {

    read -rsn 1 mainMenuOptions

    case "$mainMenuOptions" in
        [v1] ) _CreateAddPlaylist -v ;;
        [aA2]) _CreateAddPlaylist -a ;;
        [sS3]) _SaveRemove ;;
        [pP4]) _LoadPlaylist ;;
        [fF5]) _LoadLocalMenu ;;
        [dD6]) _ViewAudioVideoUrlsInfo -d ;;
        [zZ7]) _MpvOwnsTmpList --clear-tmp; _ClearAllTmpLists ;;
        [eE8]) _EditPlaylist ;;
        [cC9]) _EditMpmConf ;;
        [bB] ) _MpmHelp -b ;;
        [hH] ) _MpvControl -h ;;
        [jJ] ) _MpvControl -j ;;
        [kK] ) _MpvControl -k ;;
        [lL] ) _MpvControl -l ;;
        [mM] ) _MpmHelp -m ;;
        [qQ] ) _MpvControl -q ;;
        [rR] ) _MpvControl -r ;;
        [tT] ) _MpvControl -t ;;
        [uU] ) _MpmHelp -u ;;
        V    ) pulsemixer || ncpamixer ;;
        [xX] ) _IfQuitAfterTask -x ;;
        [yY] ) _ViewScheduledList ;;
        [nN] ) _MpvTuiTest ;;
        $'\033')
            read -rsn 2 arrowkeys # Arrow keys are disabled.
            case "$arrowkeys" in "[A|[B|[C|[D") : ;; esac
        ;;
        $'\0d') _MpmrcTasksList ;; # Ctrl+M, space
        $'\02') _ChooseTheme ;; # Ctrl+B
        *) _WrongOption "$mainMenuOptions" ;;
    esac

}
