#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_MenuBobySettings() {

    local varConv varDirect varFmt varFzf varMpvc varParallel varQuit

    if [[ $use_mpvc == yes ]]; then
        varMpvc="${task}  yes${nc}"
    elif [[ $use_mpvc == no ]]; then
        varMpvc="${critical}   no${nc}"
    else
        varMpvc="${critical}unset${nc}"
    fi

    if [[ $use_fzf == yes ]]; then
        varFzf="${task}  yes${nc}"
    elif [[ $use_fzf == no ]]; then
        varFzf="${critical}   no${nc}"
    else
        varFzf="${critical}unset${nc}"
    fi

    if [[ $use_parallel == yes && $use_parallel_downloads == no ]]; then
        varParallel="${critical}  yes${nc}"
    elif [[ $use_parallel == yes ]]; then
        varParallel="${task}  yes${nc}"
    elif [[ $use_parallel == no ]]; then
        varParallel="${task}   no${nc}"
    else
        varParallel="${critical}unset${nc}"
    fi

    if [[ $direct_download == yes ]]; then
        varDirect="${task} yes${nc}"
    elif [[ $direct_download == no ]]; then
        varDirect="${task}  no${nc}"
    else
        varDirect="${critical} !!!${nc}"
    fi

    if [[ $automatic_audio_conversion == no && -n $default_conversion_format ]]; then
        varConv="${critical}  no${nc}"
    elif [[ $automatic_audio_conversion == no && -z $default_conversion_format ]]; then
        varConv="${critical}  no${nc}"
    elif [[ $automatic_audio_conversion == yes && -z $default_conversion_format ]]; then
        varConv="${critical} yes${nc}"
    elif [[ $automatic_audio_conversion == yes && -n $default_conversion_format ]]; then
        varConv="${task} yes${nc}"
    else
        varConv="${critical} !!!${nc}"
    fi

    if [[ -z $default_conversion_format ]]; then
        varFmt="${critical}  unset${nc}"
    elif [[ $default_conversion_format == flac ]]; then
        varFmt="${task}   $default_conversion_format${nc}"
    else
        varFmt="${task}    $default_conversion_format${nc}"
    fi

    if [[ $quit_after_task == yes ]]; then
        varQuit="${critical}yes${nc}"
    elif [[ $quit_after_task == no ]]; then
        varQuit="${task} no${nc}"
    else
        varQuit="${critical}!!!${nc}"
    fi

    _MenuBoby

}
