#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MenuHeader() {

    local sep="${task}*${nc}"

    # we need color for this, so we need to use echo.
    # -1 because we don't want to take into account default.m3u
    __col() (
        p=("$playlists_dir"/*.m3u) pc="${#p[@]}"
        echo "${info}$((pc - 1))${nc}"
    )

    __def() (
        local defCnt
        defCnt=$(_GetLinesList -d)
        if [[ -f $tmp_dir/1 ]]; then
            echo "${critical}${b}$defCnt${nb}${nc}"
        elif [[ $defCnt -gt 0 ]]; then
            echo "${info}$defCnt${nc}"
        else
            echo "0"
        fi
    )

    __aud() (
        test -s "$AUDIO_URLS" && \
        echo "${info}$(_GetLinesList -a)${nc}" || echo "0"
    )

    __vid() (
        test -s "$VIDEO_URLS" && \
        echo "${info}$(_GetLinesList -v)${nc}" || echo "0"

    )

    __sch() (
        test -f "$schedules_dir/schedules.txt" && \
        echo "${info}$(grep '.m3u$' -c "$schedules_dir/schedules.txt")${nc}"
    )

    clear
    echo -e "\n\n                                            ${mtitle}${B}:: MPV-PLAYLISTS-MANAGER $VERSION ::${NB}" "$(_CheckUpdate)"
    echo -e "                                            $(_LittleStars)${nc}"
    [[ -z $THEME ]] && \
    echo -e "                                                  current theme: ${info}${theme}${nc}" || \
    echo -e "                                                  current theme: ${info}${THEME}${nc}"
    if [[ -f $schedules_dir/schedules.txt ]]; then
        printf '%s\n' "                   ┌─────────────────────────────────────────────────────────────────────────────────────┐" \
        "                      Collection: $(__col) ${sep} Default list: $(__def) ${sep} Audio list: $(__aud) ${sep} Video list: $(__vid) ${sep} Scheduled: $(__sch)" \
        "                   └─────────────────────────────────────────────────────────────────────────────────────┘"
    else
        printf '%s\n' "                   ┌─────────────────────────────────────────────────────────────────────────────────────┐" \
        "                             Collection: $(__col) ${sep} Default list: $(__def) ${sep} Audio list: $(__aud) ${sep} Video list: $(__vid)" \
        "                   └─────────────────────────────────────────────────────────────────────────────────────┘"
    fi
    printf '%s\n' "                   ┌─────────────────────────────────────────────────────────────────────────────────────┐" \
    "                   │                      ${info}${B}GENERAL OPTIONS${NB}${nc}                       │     ${mtitle}${B}MPMRC SETTINGS${NB}${nc}     │" \
    "                   │  ────────────────────────────────────────────────────────  │  ────────────────────  │"

}
