#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MenuHeader() {

    local sep
    sep="${task}*${nc}"

    __col() (
        if [[ -z $(find "$playlists_dir" -not -name "default.m3u" -name "*.m3u") ]]; then
            echo "0"
        else
            echo "${info}$(find "$playlists_dir" -not -name "default.m3u" \
            -name "*.m3u" -printf '.' | wc -c)${nc}"
        fi
    )

    __def() (
        if [[ -f $tmp_dir/1 ]]; then
            echo "${critical}${b}$(_GetLinesList -d)${nb}${nc}"
        elif [[ $(_GetLinesList -d) -gt 0 ]]; then
            echo "${info}$(_GetLinesList -d)${nc}"
        else
            echo "0"
        fi
    )
    
    __aud() (
        test -s "$AUDIO_URLS" && \
        echo "${info}$(_GetLinesList -a)${nc}" || echo "0"
    )

    __vid() (
        test -s "$VIDEO_URLS" && \
        echo "${info}$(_GetLinesList -v)${nc}" || echo "0"

    )

    clear
    _BlankLine
    echo -e "                                            ${mtitle}:: MPV-PLAYLISTS-MANAGER $VERSION ::" "$(_CheckUpdate)"
    echo -e "                                            $(_LittleStars)${nc}"
    [[ -z $THEME ]] && \
    echo -e "                                                  current theme: ${info}${theme}${nc}" || \
    echo -e "                                                  current theme: ${info}${THEME}${nc}"
    echo -e "                   ┌─────────────────────────────────────────────────────────────────────────────────────┐"
    echo -e "                             Collection: $(__col) ${sep} Default list: $(__def) ${sep} Audio list: $(__aud) ${sep} Video list: $(__vid)"
    echo -e "                   └─────────────────────────────────────────────────────────────────────────────────────┘"
    echo -e "                   ┌─────────────────────────────────────────────────────────────────────────────────────┐"
    echo -e "                   │                      ${info}GENERAL OPTIONS${nc}                       │     ${mtitle}MPMRC SETTINGS${nc}     │"
    echo -e "                   │  ────────────────────────────────────────────────────────  │  ────────────────────  │"

}
