#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MenuOptions() {
    read -rsn 1 mainMenuOptions
    case "$mainMenuOptions" in
        1|v|V) _CreateAddPlaylist -v ;;
        2|a|A) _CreateAddPlaylist -a ;;
        3|s|S) _SaveRemove ;;
        4|p|P) _LoadPlaylist ;;
        5|f|F) _LoadLocalMenu ;;
        6|d|D) _ViewAudioVideoUrlsInfo -d ;;
        7|z|Z) _MpvOwnsTmpList --default || _MpvOwnsTmpList --list || _ClearAllTmpLists ;;
        8|e|E) _EditPlaylist ;;
        9|c|C) _EditMpmConf ;;
        b|B  ) _MpmHelp -b ;;
        h|H  ) _MpvControl -h ;;
        j|J  ) _MpvControl -j ;;
        k|K  ) _MpvControl -k ;;
        l|L  ) _MpvControl -l ;;
        m|M  ) _MpmHelp -m ;;
        q|Q  ) _MpvControl -q ;;
        r|R  ) _MpvControl -r ;;
        t|T  ) _MpvControl -t ;;
        u|U  ) _MpmHelp -u ;;
        x|X  ) _IfQuitAfterTask -x ;;
        n|N  )
            if _PidOfMpv >/dev/null && [[ $use_mpvc == yes && -n $mpvc_tui ]]; then
                if _Has fzf && [[ $mpvc_tui == native ]]; then
                    echo "starting simple mpm player" > "$tmp_dir"/playerSelectedFile
                    _FzfPlayer
                else
                    _Has "$mpvc_tui" && "$mpvc_tui"
                fi
            else
                printf '%s\n' \
                " ${critical}mpv isn't running or no mpv interface setup in your config..." \
                " use_mpvc must be set to 'yes' or mpvc_tui is empty${nc}"
                sleep 8
            fi
        ;;
        $'\033')
            read -rsn 2 arrowkeys # Arrow keys are disabled.
            case "$arrowkeys" in
                "[A|[B|[C|[D") : ;;
            esac
        ;;
        $'\0d') _MpmrcTasksList ;; # Ctrl+M
        $'\02') _ChooseTheme ;; # Ctrl+B
        *) _WrongOption "$mainMenuOptions" ;;
    esac
}