#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_MpmOptions() {

    _CheckDependencies "${@}"

    local list editoption
    list="$2".m3u

    case "$1" in
        --config |-c) "$MPMEDITOR" "$MPMRC" ;;
        --edit   |-e)
            editoption=yes
            if [[ -f $playlists_dir/$list ]]; then
                _EditPlaylist
            else
                printf '\n%s\n' " ${critical}$list does not exist!${nc}"
                exit 1
            fi
        ;;
        --help   |-h) less "$HELP" ;;
        --local  |-f) _LoadLocalMenu ;;
        --version|-v) echo -e "\n  ${0##*/} $VERSION" ;;
        --load   |-l)
            if [[ -f $playlists_dir/$list ]]; then
                _LoadPlaylistMenu
            else
                _LoadPlaylist
            fi
        ;;
        *)
            if (( $# == 0 )); then
                _StartUp
            else
                printf '\n%s\n' " ${critical}invalid option: ${task}$1${nc}"
                head -n 13 "$HELP"; echo $'\e[0m'
                exit 1
            fi
        ;;
    esac

    _LaunchMpm "${@}"

}
