#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2001
_MpvDisplayTitle() {

    if [[ -n $(pgrep -x mpv) && -z $(command -v socat) ]]; then
        printf '%s\n' \
        " ${critical}Package socat must be installed to display titles.${nc}"
        sleep 4
        return
    elif pgrep -x mpv >/dev/null; then

        echo '{ "command": ["get_property", "media-title"] }' \
        | socat - "${SOCKETPATH}" \
        | awk -F'"' -v green="${info}" -v yellow="${mtitle}" '
            { print green" Now playing: " yellow$4 }
        '
        
        sleep 5
    else
        printf '%s\n' \
        " ${critical}mpv isn't running, nothing to display...${nc}"
        sleep 4
        return
    fi

}