#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MpvOwnsTmpList() {

    [[ -f $NOWPLAYING || -f $tmp_dir/fzfEnqueue ]] && {
        
        pgrep -x mpv >/dev/null && {

            case "$1" in
                --list)
                    action=" if you want to play the current list,"
                ;;
                --local)
                    action=" if you want to queue or parse another directory,"
                ;;
            esac
            __
            printf '%s\n' " ${critical}mpv is already running..." \
            "$action" \
            " just quit mpv first to continue.${nc}"
            __
            read -rsn 1 \
            -p " ${info}[Q]uit mpv, [A]bort: ${nc}" mpvOwnsTmpListOptions
            case "$mpvOwnsTmpListOptions" in
                q|Q)
                    kill -SIGTERM "$(pidof mpv)"
                    rm "$(readlink -f "$tmp_dir"/fzfEnqueue)" 2>/dev/null
                    return
                ;;
                a|A)
                    _Menu
                ;;
                *)
                    _WrongOption "$mpvOwnsTmpListOptions" && _Menu
                ;;
            esac
        }
        rm "$NOWPLAYING"

    }

}