#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MpvOwnsTmpList() {

    [[ -f $NOWPLAYING || -f $m3uFile ]] && {
        pgrep -x mpv >/dev/null && {

            case "$1" in
                --list)
                    action=" if you want to perform any action on it,"
                ;;
                --local)
                    action=" if you want to queue or parse another directory,"
                ;;
            esac
            __
            printf '%s\n' " ${critical}${file} list is owned by mpv..." \
            "$action" \
            " just quit mpv first to continue.${nc}"
            __
            read -rsn 1 \
            -p " ${info}[Q]uit mpv, [A]bort: ${nc}" mpvOwnsTmpListOptions
            case "$mpvOwnsTmpListOptions" in
                q|Q)
                    if [[ $file = "default" ]]; then
                        kill -SIGTERM "$(pidof mpv)"
                        return
                    else
                        kill -SIGTERM "$(pidof mpv)"
                        clear; __
                        return
                    fi
                ;;
                a|A)
                    _Menu
                ;;
                *)
                    _WrongOption "$mpvOwnsTmpListOptions" && _Menu
                ;;
            esac
        }
        rm "$NOWPLAYING"
    }

}