#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2001
_MpvDisplayTitle() {

    local socketPath

    if [[ -n $(pgrep -x mpv) && -z $(command -v socat) ]]; then
        printf '%s\n' \
        " ${critical}Package socat must be installed to display mpv title.${nc}"
        sleep 4
        return
    elif [[ -n $(pgrep -x mpv) ]]; then
        # the mpv socket directory may change in mpmrc definition, so we have to know it.
        socketPath=$(echo "${mpvGenOptions_SK[*]}" | sed 's/--input-ipc-server=//')

        echo '{ "command": ["get_property", "media-title"] }' \
        | socat - "${socketPath}" \
        | awk -F'"' -v I="${info}" -v M="${mtitle}" '{ print I" Now playing: " M$4 }'
        
        sleep 5
    else
        printf '%s\n' \
        " ${critical}mpv isn't running, nothing to display...${nc}"
        sleep 4
        return
    fi

}