#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MpvSocketCommands() {

    case $1 in
        --title)
            echo '{ "command": ["get_property", "media-title"] }' \
            | socat - "${MPVSOCKET}" \
            | jq --raw-output '"\\033[32mNow playing: \\033[33m" + .data' \
            | echo -e "$(cat -)"
        ;;
        --playlist)
            sleep 0.5
            echo '{ "command": ["get_property", "playlist"] }' \
            | socat - "$MPVSOCKET" \
            | jq --raw-output '.data | .[] | .filename' > "$playerTitlesList"
        ;;
    esac

    case $1 in
        --next) echo playlist-next ;;
        --prev) echo playlist-prev ;;
        --forward) echo seek 30 ;;
        --backward) echo seek -30 ;;
        --pause) echo cycle pause ;;
        --begin) echo playlist-play-index 0 ;;
        --stop) echo stop ;;
    esac | socat - "${MPVSOCKET}"

}
# needed for native mpv TUI
export -f _MpvSocketCommands
