#!/usr/bin/env bash
## This is a part of main script: mpm

# shellcheck disable=SC2154
_MpvControl() {

    __uselessPrompt() {
        printf '\n%s\n' \
        " ${critical}mpv isn't running...${task}${key^}${critical} is useless.${nc}"
        sleep 2
    }

    __mpvControlTests() {
        if ! _Has socat; then
            printf '%s\n' \
            " ${critical}the socat package must be installed to control mpv.${nc}"
            sleep 4; return 1
        elif ! _PidOfMpv >/dev/null; then
            case "$key" in
                h|j|k|l|n|q|t)
                    __uselessPrompt
                ;;
                r) _BlankLine ;;
            esac
            return 1
        fi
    }

    case "$1" in
        -h) key=h; __mpvControlTests && _MpvSocketCommands --prev ;;
        -j) key=j; __mpvControlTests && _MpvSocketCommands --stop ;;
        -k) key=k; __mpvControlTests && _MpvSocketCommands --pause ;;
        -l) key=l; __mpvControlTests && _MpvSocketCommands --next ;;
        -n) key=n; __mpvControlTests ;;
        -t) key=t; __mpvControlTests && _MpvSocketCommands --title; sleep 4 ;;
        -q) key=q; __mpvControlTests && _KillMpv; _RemoveMpvTmp ;;
        -r)
            key=r; __mpvControlTests && \
            if _PidOfMpv >/dev/null; then
                __uselessPrompt
            else
                _RemoveMpvTmp
            fi
        ;;
    esac

}
