#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_MpvcTest() {
    case "$1" in
        -a)
            if [[ $use_mpvc == yes || $use_mpvc == no ]]; then
                _MakeMpvPlaylist --online-audio
            else
                # use_mpvc is empty
                _MakeMpvPlaylist --terminal-audio
            fi
        ;;
        -v)
            if [[ $use_mpvc == yes || $use_mpvc == no ]]; then
                _MakeMpvPlaylist --online-video
            else
                _MakeMpvPlaylist --terminal-video
            fi
        ;;
    esac
}
