#!/usr/bin/env bash

## This is a part of main script: mpm.
# shellcheck disable=SC2154
_ParallelXargsCmd() {

    __sedRemoveAll() (
        if [[ $M3UFILE == "$AUDIO_URLS" || $M3UFILE == "$VIDEO_URLS" ]]; then
            sed -i '1,$d' {"$M3UFILE","$TITLES"}
        elif [[ $M3UFILE == "$DEFAULT_LIST" ]]; then
            sed -i '2,$d' "$M3UFILE"
            sed -i '1,$d' "$TITLES"
        elif [[ $M3UFILE == "$SELECTED_URLS1" ]]; then
            sed -i '1,$d' "$SELECTED_TITLES"
        else
            sed -i '1,$d' \
            {"$playlists_dir"/"$list","$titles_dir"/"$list".titles}
        fi
    )

    case "$1" in
        --choose-audio|--get-audio)
            grep '^https' "$M3UFILE" | xargs -I '{}' -P 4 \
            yt-dlp --format bestaudio/best "${ytdlPreset_NC[@]}" {}
            __sedRemoveAll
        ;;
        --choose-video|--get-video)
            grep '^https' "$M3UFILE" | xargs -I '{}' -P 3 \
            yt-dlp --format bestvideo+bestaudio/best "${ytdlPreset_X[@]}" {}
            __sedRemoveAll
        ;;
        --direct-video)
            grep '^https' "$playlists_dir"/"$list" | xargs -I '{}' -P 3 \
            yt-dlp --format bestvideo+bestaudio/best "${ytdlPreset_X[@]}" {}
            __sedRemoveAll
        ;;
    esac

} >/dev/null 2>&1