#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2038,SC1083
_ParallelConversion() {

    __parallelMethod() (
        printf '%s\n' " ${info}Parallel conversion enabled.${nc}"
        parallel --delay 2 --jobs "$parallel_threads" --bar \
        ffmpeg -hide_banner -loglevel error \
        -y -i {} -qscale:a 0 {.}."$1" ::: ./*.webm
        rm -rf "$HOME"/.parallel
    )

    __xargsMethod() (
        printf '%s\n' " ${info}use_parallel is set to no... using xargs.${nc}"
        find . -iname "*.webm" | xargs -I % -P "$parallel_threads" \
        ffmpeg -hide_banner -loglevel error -y -i % %."$1"
    )

    case "$1" in
        --parallel-default) __parallelMethod "$default_conversion_format" ;;
        --parallel-chosen ) __parallelMethod "${formats[${REPLY}]}" ;;
        --xargs-default   ) __xargsMethod "$default_conversion_format" ;;
        --xargs-chosen    ) __xargsMethod "${formats[${REPLY}]}" ;;
    esac

    # removing the primary suffix from our converted files (.webm.{aac,mp3,flac,ogg,wav})
    find . -maxdepth 1 -type f -name "*.webm.*" -exec \
    bash -c '
        for ext in "$@"; do
            n="${ext##*/}"
            mv -n "$ext" "${ext%/*}/${n//.webm/}"
        done >/dev/null 2>&1
    ' {} \;

}
