#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ParallelAnimation() {

    case "$parallel_animation" in
        spinners)
            local spinners
            spinners="|/-\\"
            while [[ -s $animationTitles ]]; do
                local temp=${spinners#?}
                printf " [${task}%c${nc}]  " "$spinners"
                local spinners=$temp${spinners%"$temp"}
                sleep 0.2
                printf "\b\b\b\b\b\b"
            done
            clear
        ;;
        progress)
            local total downloaded percent bar_width
            bar_width=50
            # Calculate total from initial animationTitles
            total=0
            while read -r _; do ((total++)); done < "$animationTitles"
            while [[ -s $animationTitles ]]; do
                downloaded=0
                for file in "$mediaDir"/*; do
                    if [[ -f $file && $file != *.part ]]; then
                        case "${file##*.}" in
                            mp4|webm|mkv) ((downloaded++)) ;;
                        esac
                    fi
                done
                percent=$(( (downloaded * 100) / total ))
                local blocks=$((downloaded * bar_width / total))
                local empty=$((bar_width - blocks))
                local bar=""
                for ((i=0; i<blocks; i++)); do bar+="█"; done
                for ((i=0;i<empty;i++)); do bar+="."; done
                printf "\r [%s] %3d%%" "$bar" "$percent"
                sleep 0.4
            done
        ;;
    esac

}
