#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ParallelAnimation() {

    case "$parallel_animation" in
        spinners)
            local delay spinners

            delay=0.1
            spinners="|/-\\"

            while [[ -s $animationTitles ]]; do
                local temp=${spinners#?}
                printf " [${task}%c${nc}]  " "$spinners"
                local spinners=$temp${spinners%"$temp"}
                sleep "$delay"
                printf "\b\b\b\b\b\b"
            done
            clear
        ;;
        progress)
            printf "["

            while [[ -s $animationTitles ]]; do
                printf  "▓"
                sleep 0.50
            done
            clear
        ;;
    esac

}
