#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ParallelDownloadCmd() {

    declare -a ytfmt=(
        "yt-dlp --format bestaudio\/best"
        "yt-dlp --format bestvideo+bestaudio\/best"
    )

    __sedAudioCmd() ( sed -i "s/^/${ytfmt[0]} ${ytdlPreset_NC[*]} /" "$1"; )
    __sedVideoCmd() ( sed -i "s/^/${ytfmt[1]} ${ytdlPreset_X[*]} /" "$1"; )

    __getM3ufileTest() (
        sed -i '1,$d' {"$M3UFILE","$TITLES"}
        [[ $M3UFILE == "$DEFAULT_LIST" ]] && echo "#EXTM3U" > "$M3UFILE"
        clear
    )

    case "$1" in
        --choose-audio)
            cp "$M3UFILE" "$JOBSLIST"
            __sedAudioCmd "$JOBSLIST"
            {
                parallel --delay 1.75 --jobs 4 < "$JOBSLIST"
                sed -i '1,$d' "$SELECTED_TITLES"
                clear
            } &
        ;;
        --choose-video)
            cp "$M3UFILE" "$JOBSLIST"
            __sedVideoCmd "$JOBSLIST"
            {
                parallel --delay 2.5 --jobs 3 < "$JOBSLIST"
                sed -i '1,$d' "$SELECTED_TITLES"
                clear
            } &
        ;;
        --direct-video)
            sed -i '1d' "$playlists_dir"/"$list"
            __sedVideoCmd "$playlists_dir"/"$list"
            {
                parallel --delay 2.5 --jobs 3 < "$playlists_dir"/"$list"
                sed -i '1,$d' {"$playlists_dir"/"$list","$titles_dir"/"$list".titles}
                clear
            } &
        ;;
        --get-audio)
            [[ $M3UFILE == "$DEFAULT_LIST" || $M3UFILE == "$playlists_dir"/"$list" ]] && \
            sed -i '1d' "$M3UFILE"
            __sedAudioCmd "$M3UFILE"
            {
                parallel --delay 1.75 --jobs 4 < "$M3UFILE"
                __getM3ufileTest
            } &
        ;;
        --get-video)
            [[ $M3UFILE == "$DEFAULT_LIST" ]] && sed -i '1d' "$M3UFILE"
            __sedVideoCmd "$M3UFILE"
            {
                parallel --delay 2.5 --jobs 3 < "$M3UFILE"
                __getM3ufileTest
            } &
        ;;
    esac

    rm -rf {"$HOME"/.parallel,"$JOBSLIST"}

} >/dev/null 2>&1
