#!/usr/bin/env bash
## This is a part of main script: mpm.

_PolybarIpc() {
    _Has polybar && pgrep --full polybar >/dev/null && {
        polybar-msg action "#mpm-ipc.hook.0" >/dev/null 2>&1
    }
}
