#!/bin/bash
## This is a part of main script: mpm.

# stolen from budRich
_Prompt() {
    local screenprompt key default opt status

    default=y
    opt=yn

    [[ $1 =~ -([${opt}]) ]] \
        && default="${BASH_REMATCH[1]}" && shift

    screenprompt="$* [${default^^}/${opt/$default/}]:"

    if [[ -t 2 ]]; then
        >&2 echo "$screenprompt"

        while :; do
            read -rsn 1

            key="${REPLY:-$default}"
            [[ $key =~ [${opt}] ]] || continue
            break
        done
    else
        key="$default"
    fi

    [[ ${key,,} = n ]] && status=1

    return "${status:-0}"
}

