#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_QueueMultipleDirs() {

    clear

    cd "$localDir" || exit 1

    local mpv_list dirlist localPlaylist
    mpv_list="$localDir/dirlist.m3u"
    dirlist="$tmp_dir/dirlist"

    rm "$mpv_list" 2>/dev/null

    find ./ -maxdepth 1 -type d -empty \
    | sed 's,.*/,,' >> "$tmp_dir"/empty.tmp

    if [[ -f $tmp_dir/empty.tmp ]]; then
        # empty dirs will be banned from our list 
        command ls > "$dirlist".tmp
        grep -vF "$(grep '^[[:print:]]' "$tmp_dir"/empty.tmp)" \
        "$dirlist".tmp >> "$dirlist"
        rm "$tmp_dir"/{dirlist,empty}.tmp
    else
        command ls > "$dirlist"
    fi
    __
    printf '%s\n' " ${info}Directories in ${localDir##*/}: ${nc}"
    __; nl "$dirlist"; __

    IFS=", "; read -ra selected_dirs -p "$RANGEPROMPT"
    for range in "${selected_dirs[@]}"; do
        IFS="-"; read -r start end <<< "$range"

        [[ $range =~ [[:alpha:]] ]] && {
            unset IFS range
            rm "$dirlist"
            __
            printf '%s\n' " ${critical}Selection aborted.${nc}"
            sleep 2
            return
        }

        [[ -z $start ]] && continue
        [[ -z $end ]] && end="$start"

        for ((i=start;i<=end;i++)); do
            sed -n "${i}p" "$dirlist" >> "$mpv_list"
        done

    done

    dirPath=$(pwd | sed 's,/,\\/,g')

    unset IFS range
    rm "$dirlist"

    sed -i "s/^/${dirPath}\//;s,$,/," "$mpv_list"
    use_mpvc_locally=yes
    localPlaylist=yes

    mpv --no-terminal "${mpvGenOptions_SK[@]}" \
    "${mpvVideoOptions_FS[@]}" --idle=no "$mpv_list" &

    ln -sfr "$mpv_list" "$NOWPLAYING"
    _WhileMpvIsRunning &
    _Menu

}
