#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2001
_RemoveAudioVideoIds() {

    if [[ $remove_video_ids == "no" ]]; then
        return
    else
        cd "$mediaDir" && \
        printf '%s\n' " ${info}renaming files in ${mediaDir##*/}${nc}"

        mapfile \
            -t downloadedFiles < <(
                find . -maxdepth 1 -type f \
                -regextype egrep -regex '.*(\[|\]).*' \
                | sed 's,./,,'
            )

        for file in "${downloadedFiles[@]}"; do
            mv "$file" \
            "$(echo "$file" | sed -e 's/ \[.*\]//')"
        done 2>/dev/null

        unset file downloadedFiles
        sleep 2; clear
    fi

}
