#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2086,SC2015
_RemoveAudioVideoCommon() {

    test ! -s "$tmpList" && {
        printf '%s\n' " ${critical}No more links in the $Type list${nc}"
        sleep 2
        rm {"$tmpList"{,_origin},"$tmpTitles"{,_origin}}
        _Menu
    }
    
    [[ $(awk -F"/" '{print $NF}' "$NOWPLAYING" 2>/dev/null) =~ $Type ]] && {
        pgrep -x mpv >/dev/null && {
            __
            printf '%s\n' " ${critical}${tmpList##*/} is owned by mpv...retry later.${nc}"
            sleep 3
            _Menu
        }
        rm "$NOWPLAYING"
    }

    __
    read -rsn 1 -p " ${info}Remove [L]inks or the [W]hole $Type list?: ${nc}"
    
    if [[ $REPLY =~ l|L ]]; then

        [[ $(grep -c '^https' "$tmpList") -eq 1 ]] && {
            rm {"$tmpList","$tmpTitles"}
            __
            printf '%s\n' " ${critical}${tmpList##*/} cleared.${nc}"
            sleep 2
        } || {
            _RemoveTmpLinks
            [[ $tmpList = "$AUDIO_URLS" ]] && _ViewUrlInfo -a || _ViewUrlInfo -v
        }
        
    elif [[ $REPLY =~ w|W ]]; then
        rm {"$tmpList","$tmpTitles"}
        __
        printf '%s\n' " ${critical}$Type list removed...${nc}"
        sleep 2
    else
        _WrongOption "$REPLY"
    fi

}
