#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2086
_RemoveDefaultList() {
    __
    read -rsn 1 -p " ${info}Remove [L]inks or the [W]hole default list?: ${nc}"
    [[ $(awk -F"/" '{print $NF}' "$NOWPLAYING" 2>/dev/null) =~ default ]] && {
        pgrep -x mpv >/dev/null && \
        __
        printf '%s\n' " ${critical}${tmpList##*/} is owned by mpv...retry later.${nc}"
        sleep 4
        _ViewUrlInfo $arg
    }
    if [[ $REPLY =~ l|L ]]; then
        [[ $(grep '^https' -c "$tmpList") -eq 1 ]] && {
            sed -i '2d' "$tmpList"
            rm "$DEFAULTITLES"
            __
            printf '%s\n' " ${critical}${tmpList##*/} cleared.${nc}"
            sleep 2
            _Menu
        }
        sed -i '1d' "$tmpList"
        _RemoveTmpLinks
        sed -i '1s/^/#EXTM3U\n/' "$tmpList"
        _ViewUrlInfo -q
        
    elif [[ $REPLY =~ w|W ]]; then
        sed -i '/^[[:alpha:]]/d' "$tmpList"
        rm -f \
        {"$tmpList"_origin,"$DEFAULTITLES"{,_origin},"$DEFAULTM3UTITLES"} 2>/dev/null
        __
        printf '%s\n' " ${critical}${tmpList##*/} cleared.${nc}"
        sleep 2
        _Menu
    else
        _WrongOption "$REPLY"
    fi
}