#!/bin/bash
## This is a part of main script: mpm.

_Remove() {

    case "$1" in
        -a) rm -f $AUDIO_{INFO,TITLE} "$AUDIO_INFO"_origin 2>/dev/null
            __
            echo " ${r}Audio list removed...${nc}"
            sleep 3s
        ;;
        -q) sed -i '/^https/d' "$QUEUE"
            rm {"$QUEUE"_origin,"$tmp_dir"/1} 2>/dev/null
            __
            echo " ${r}Default list cleared...${nc}"
            sleep 3s ;;
        -v) rm -f $VIDEO_{INFO,TITLE} "$VIDEO_INFO"_origin 2>/dev/null
            __
            echo " ${r}Video list removed...${nc}"
            sleep 3s
        ;;
    esac
    _Menu
}
