#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_RemoveTmpLinks() {

    clear
    __
    printf '%s\n' " ${info}Select titles to remove fron ${tmpList##*/}${nc}"
    __
    cat -n "$tmpTitles"
    removeRange=$(
        printf '%s\n' "${info}Enter numbers separeted by commas or a dash for a range," \
        " for example: ${task}1-4,6 8-11 or 1-4,6-8,10 or 2,3,5,6,1 or ${mtitle}C ${info}to cancel: ${nc}"
    )
    __

    IFS=", "; read -ra array -p " ${info}""$removeRange""${nc}"
    for range in "${array[@]}"; do
        IFS="-"; read -r start end <<< "$range"
        [[ $range =~ [a-zA-Z] ]] && {
            [[ $tmpList = "$QUEUE" ]] && sed -i '1s/^/#EXTM3U\n/' "$tmpList"
            __
            printf '%s\n' " ${critical}Deletion aborted...${nc}"
            sleep 2
            unset IFS
            _Menu
        }
        [[ -z $start ]] && continue
        [[ -z $end ]] && end="$start"
        for ((i=start;i <= end;i++)); do
            sed -n "${i}p" "$tmpList" >> "$tmpList"_tmp
            sed -n "${i}p" "$tmpTitles" >> "$tmpTitles"_tmp
        done
    done

    grep -v "$(grep '^https' "$tmpList"_tmp)" "$tmpList" \
    >> "$tmpList"_tmp2 && mv -f "$tmpList"_tmp2 "$tmpList"
    grep -v -F "$(grep '^[[:print:]]' "$tmpTitles"_tmp)" "$tmpTitles" \
    >> "$tmpTitles"_tmp2 && mv -f "$tmpTitles"_tmp2 "$tmpTitles"

    rm {"$tmpList","$tmpTitles"}_tmp
    printf '%s\n' " ${critical}Selected links removed...${nc}"
    unset IFS
    sleep 2
}