#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_Remove() {

    cd "$tmp_dir" || exit 1

    local tmpList tmpTitles

    case "$1" in
        -a)
            tmpList="$AUDIO_URLS"
            tmpTitles="$AUDIO_TITLES"
            _RemoveAudioVideoCommon
        ;;
        -d)
            tmpList="$DEFAULT_LIST"
            tmpTitles="$DEFAULT_TITLES"
            _RemoveDefaultList
        ;;
        -v)
            tmpList="$VIDEO_URLS"
            tmpTitles="$VIDEO_TITLES"
            _RemoveAudioVideoCommon
        ;;
    esac

}
