#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_RemoveMpvTmp() {

    cd "$tmp_dir" || exit 1

    declare -a mpvTmpFiles=(
        "$SELECTED_URLS1" "$SELECTED_TITLES"
        "$FZFENQUEUE" "$mpv_list" "$DEFAULT_TITLES"_
        "$pidofMpv" "$LOCALDIRS_LIST" "$FZFSELTITLES"
        "playerIndexesList" "playerSelectedFile"
        "multipleDirsTitles.m3u" "multipleFilesTitles"
        "radioDirTitles" "singleDirTitles" "list_tmp"
    )

    for file in "${mpvTmpFiles[@]}"; do
        rm "$file"
    done

    if [[ $(readlink -f "$NOWPLAYING") = *.titles ]]; then
        rm "$NOWPLAYING"
    else
        rm "$(readlink -f "$NOWPLAYING")" "$NOWPLAYING"
    fi

    unset m3uFile file playerTitlesList

} 2>/dev/null
