#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_RemoveDefaultList() {

    # the default list, at least contains one line (header #EXTM3U)
    [[ $(grep "" -c "$DEFAULT_LIST") -eq 1 ]] && {
        __
        printf '%s\n' " ${critical}${DEFAULT_LIST##*/} list is empty.${nc}"
        sleep 2
        rm {"$DEFAULT_LIST"_origin,"$DEFAULT_TITLES"{,_origin}}
        _Menu
    }

    [[ $(awk -F"/" '{print $NF}' "$NOWPLAYING" 2>/dev/null) =~ default ]] && {
        _PidOfMpv >/dev/null && {
            __
            printf '%s\n' " ${critical}${DEFAULT_LIST##*/} is owned by mpv...retry later.${nc}"
            sleep 4
            _ViewAudioVideoUrlsInfo -d
        }
        rm "$NOWPLAYING"
    }

    __
    read -rsn 1 \
    -p " ${info}Remove [L]inks or the [W]hole default list?: ${nc}" \
    removeDefaultListOptions

    case "$removeDefaultListOptions" in
        l|L)
            [[ $(grep '^https' -c "$DEFAULT_LIST") -eq 1 ]] && {
                sed -i '2d' "$DEFAULT_LIST"
                rm "$DEFAULT_TITLES"
                __
                printf '%s\n' " ${critical}${DEFAULT_LIST##*/} cleared.${nc}"
                sleep 2
                _Menu
            }
            sed -i '1d' "$DEFAULT_LIST"
            _RemoveTmpLinks
            if [[ ! -f $DEFAULT_LIST ]]; then
                echo "#EXTM3U" > "$DEFAULT_LIST"
                _Menu
            else
                sed -i '1s/^/#EXTM3U\n/' "$DEFAULT_LIST"
                return
            fi
        ;;
        w|W)
            sed -i '/^[[:alpha:]]/d' "$DEFAULT_LIST"
            rm "$DEFAULT_TITLES"
            __
            printf '%s\n' " ${critical}${DEFAULT_LIST##*/} cleared.${nc}"
            sleep 2
            _Menu
        ;;
        *)
            _WrongOption "$removeDefaultListOptions"
        ;;
    esac

}
