#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2001
_RemoveAudioVideoIds() {
    
    cd "$mediaDir" && {
        printf '%s\n' " ${info}renaming files in ${mediaDir##*/}${nc}"
        sleep 2; clear
    }

    mapfile \
        -t downloadedFiles < <(
            find . -maxdepth 1 -type f \
            -regextype egrep -regex '.*(\[|\]).*' \
            | sed 's,./,,'
    )
    
    for file in "${downloadedFiles[@]}"; do
        mv "$file" \
        "$(echo "$file" | sed -e 's/ \[.*\]//')"
    done

    unset file

}
