#!/bin/bash
## This is a part of main script: mpm.

_RemoveCrap() {
    # After some tests it appears that a single link copied from a youtube playlist
    # causes the download of the entire playlist.
    # So with sed & perl we cleanup the link to get the direct link to the desir video.
    # Note that this behavior does not appear during a simple viewing/listening.

    LISTS=( "$QUEUE" "$VIDEO_INFO" "$VIDEO_TITLE" "$AUDIO_INFO" "$AUDIO_TITLE" )

    for file in "${LISTS[@]}"; do
        # removing unwanted parts of links, blank lines & duplicates
        sed -i 's/&list.*//;/^\s*$/d' "$file"
        perl -i -ne 'print if ! $a{$_}++' "$file"
    done 2>/dev/null

}

