#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_RemoveDefaultList() {

    # the default list, at least contains one line (header #EXTM3U)
    [[ $(grep "" -c "$tmpList") -eq 1 ]] && {
        __
        printf '%s\n' " ${critical}$tmpList list is empty.${nc}"
        sleep 2
        rm {"$tmpList"_origin,"$tmpTitles"{,_origin}}
        _Menu
    }

    [[ $(awk -F"/" '{print $NF}' "$NOWPLAYING" 2>/dev/null) =~ default ]] && {
        pgrep -x mpv >/dev/null && {
            __
            printf '%s\n' " ${critical}${tmpList##*/} is owned by mpv...retry later.${nc}"
            sleep 4
            _ViewAudioVideoUrlsInfo -q
        }
        rm "$NOWPLAYING"
    }

    __
    read -rsn 1 -p " ${info}Remove [L]inks or the [W]hole default list?: ${nc}"

    case "$REPLY" in
        l|L)
            [[ $(grep '^https' -c "$tmpList") -eq 1 ]] && {
                sed -i '2d' "$tmpList"
                rm "$tmpTitles"
                __
                printf '%s\n' " ${critical}${tmpList##*/} cleared.${nc}"
                sleep 2
                _Menu
            }
            sed -i '1d' "$tmpList"
            _RemoveTmpLinks
            sed -i '1s/^/#EXTM3U\n/' "$tmpList"
            _ViewAudioVideoUrlsInfo -q
        ;;
        w|W)
            sed -i '/^[[:alpha:]]/d' "$tmpList"
            rm "$tmpTitles"
            __
            printf '%s\n' " ${critical}${tmpList##*/} cleared.${nc}"
            sleep 2
            _Menu
        ;;
        *)
            _WrongOption "$REPLY"
        ;;
    esac

}
