#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2086
_Remove() {

    case "$1" in
        -a) rm -f $AUDIO_{INFO,TITLE} \
            {"$AUDIO_INFO"_origin,"$AUDIO_TITLE"_origin}
            __
            echo " ${critical}Audio list removed...${nc}"
            sleep 3
        ;;
        -q) sed -i '/^https/d' "$QUEUE"
            rm {"$QUEUE"_origin,"$tmp_dir"/1} 2>/dev/null
            rm {"$tmp_dir"/DefaultTitles_origin,"$tmp_dir"/DefaultTitles} 2>/dev/null
            __
            echo " ${critical}Default list cleared...${nc}"
            sleep 3
        ;;
        -v) rm -f $VIDEO_{INFO,TITLE} \
            {"$VIDEO_INFO"_origin,"$VIDEO_TITLE"_origin}
            __
            echo " ${critical}Video list removed...${nc}"
            sleep 3
        ;;
    esac

    _Menu
}

