#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_RemoveAudioVideoCommon() {

    # test ! -s "$tmpList" && {
    #     printf '%s\n' " ${critical}No more links in the $Type list${nc}"
    #     sleep 2
    #     rm {"$tmpList"{,_origin},"$tmpTitles"{,_origin}}
    #     return
    # }

    _BlankLine
    read -rsn 1 -p \
    " ${info}[${mtitle}C${info}]ancel, Remove [L]inks or the [W]hole $Type list?: ${nc}" \
    REPLY

    case "$REPLY" in
        [cC]) return ;;
        [lL])
            mapfile -t audioVideoList < "$current_list"
            if ((${#audioVideoList[@]} == 1)); then
                rm {"$current_list","$current_titles"}
                printf '\n%s\n' " ${critical}${current_list##*/} cleared.${nc}"
                sleep 2
            else
                local action
                if _TestFzfCommand; then
                    action="Remove"
                    _FzfSaveRemoveTmpLinks
                else
                    _RemoveTmpLinks;
                fi
                if [[ -s $TITLES ]]; then
                    _CreateAddPlaylistActions --view
                else
                    _CreateAddPlaylist "$arg"
                fi
            fi
        ;;
        [wW])
            rm {"$tmpList","$tmpTitles"}
            printf '\n%s\n' " ${critical}$Type list removed...${nc}"
            sleep 2
        ;;
        *)
            _WrongOption "$REPLY"
        ;;
    esac

}
