#!/usr/bin/env bash

## This is a part of main script: mpm.

# shellcheck disable=SC2154
_RemoveTmpLinks() {

    __abortDeletionMessage() {
        unset IFS range TmpList array
        printf '\n%s\n' " ${critical}Deletion aborted...${nc}"
        sleep 2
    }

    mapfile -t TmpList < "$current_list"

    IFS=", ";
    if [[ -s $FZFSELTITLES ]]; then
        mapfile -t tmpLinks < "$FZFSELTITLES"
    else
        # use_fzf=no
        _ResizeWindow --main; clear
        printf '\n%s\n' " ${info}Select titles to remove from ${current_list##*/}${nc}"
        _BlankLine
        nl "$current_titles"
        _BlankLine
        read -ra tmpLinks -p "$RANGEPROMPT"
    fi

    declare -a array=()
    for range in "${tmpLinks[@]}"; do
        IFS="-"; read -r start end <<< "$range"

        [[ $range =~ [a-zA-Z] ]] && {

            if [[ $current_list == "$DEFAULT_LIST" ]]; then
                if ((${#TmpList[@]} > 25)); then
                    sed -i '1s/^/#EXTM3U\n/' "$DEFAULT_LIST"
                    __abortDeletionMessage
                    _Menu
                else
                    __abortDeletionMessage
                    rm "$FZFSELTITLES"
                    return
                fi
            else
                if ((${#TmpList[@]} > 25)); then
                    __abortDeletionMessage
                    _CreateAddPlaylist "$arg"
                else
                    __abortDeletionMessage
                    rm "$FZFSELTITLES"
                    return
                fi
            fi

        }

        [[ -z $start ]] && continue
        [[ -z $end ]] && end="$start"

        for ((i=start;i<=end;i++)); do
            sed -n "${i}p" "$current_list" >> "$current_list"_tmp
            sed -n "${i}p" "$current_titles" >> "$current_titles"_tmp
            array+=("$i")
        done

    done

    if (( ${#array[@]} == ${#TmpList[@]} )); then
        rm {"$current_list","$current_titles"}
        printf '\n%s\n' " ${critical}All links selected, ${current_list##*/} removed...${nc}"
    else
        grep -v "$(grep '^https' "$current_list"_tmp)" \
        "$current_list" >> "$current_list"_tmp2
        grep -v -F "$(grep '^[[:print:]]' "$current_titles"_tmp)" \
        "$current_titles" >> "$current_titles"_tmp2
        mv -f "$current_list"_tmp2 "$current_list"
        mv -f "$current_titles"_tmp2 "$current_titles"
        _RemoveDuplicateLines "$current_list" "$current_titles"
        printf '\n%s\n' " ${critical}Selected links removed...${nc}"
    fi

    rm {"$current_list","$current_titles"}_tmp "$FZFSELTITLES" 2>/dev/null

    unset IFS range TmpList array lst
    sleep 2

}