#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_RemoveDuplicateLines() {
    # Some systems may use gawk or perl
    # we use '> 0' and shift, so we can pass multiple arguments
    while (( $# >= 1 )); do
        awk -i inplace '!seen[$0]++' "$1" || \
        perl -i -ne 'print if ! $a{$_}++' "$1"
        shift
    done

}