#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2001
_RemoveAudioVideoIds() {

    if [[ $remove_video_ids == "no" ]]; then
        return
    else
        cd "$mediaDir" && \
        printf '%s\n' " ${info}renaming files in ${mediaDir##*/}${nc}"

        mapfile -t downloadedFiles < <(
            find . \
            -maxdepth 1 \
            -type f \
            -regextype egrep \
            -regex '.*(\[|\]).*' \
            -printf '%f\n'
        )

        for file in "${downloadedFiles[@]}"; do
            local new_name="${file/ \[*\]/}"
            mv --force "$file" "$new_name"
        done 2>/dev/null

        unset file new_name
        sleep 2; clear
    fi

}
