#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_RemoveMpvTmp() {

    cd "$tmp_dir" || exit 1
    mpv_is_running="no"

    declare -a mpvTmpFiles=(
        "$SELECTED_URLS1" "$SELECTED_TITLES"
        "$FZFENQUEUE" "$mpv_list"
        "$pidofMpv" "$LOCALDIRS_LIST"
        "playerIndexesList" "playerSelectedFile"
        "multipleDirsTitles.m3u" "multipleFilesTitles"
        "radioDirTitles" "singleDirTitles"
    )

    for file in "${mpvTmpFiles[@]}"; do
        rm "$file"
    done

    rm "$(readlink -f "$NOWPLAYING")" "$NOWPLAYING"
    unset m3uFile file

} 2>/dev/null
