#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_RenameTmpFiles() {

    declare -a tmpFiles=(
        "$AUDIO_URLS" "$AUDIO_TITLES"
        "$VIDEO_URLS" "$VIDEO_TITLES"
        "$DEFAULT_TITLES" "$DEFAULT_LIST"
    )

    for f in "${tmpFiles[@]}"; do
        mv -f "$f"_origin "$f"
    done 2>/dev/null

}
