#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_RenameTmpFiles() {

    tmpFiles=(
        "$AUDIO_URLS" "$AUDIO_TITLES"
        "$VIDEO_URLS" "$VIDEO_TITLES"
        "$DEFAULTITLES" "$DEFAULT_LIST"
    )

    for f in "${tmpFiles[@]}"; do
        [[ ! -f $f ]] && continue
        mv -f "$f"_origin "$f"
    done 2>/dev/null

}
