#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2086
_ReplaceSpaces() {

    case "$1" in
        -l)
            find {"$AUDIOS","$VIDEOS"} -maxdepth 1 \
            -type d -name "* *" -exec \
            bash -c '
                for f in "$@"; do
                    n="${f##*/}"
                    mv -nv "$f" "${f%/*}/${n// /_}"
                done >/dev/null 2>&1
            ' dummy {} +
        ;;
        -s)
            find {"$playlists_dir","$titles_dir"} -maxdepth 1 \
            -type f -name "* *" -exec \
            bash -c '
                for f in "$@"; do
                    n="${f##*/}"
                    mv -nv "$f" "${f%/*}/${n// /_}"
                done >/dev/null 2>&1
            ' dummy {} +
        ;;
    esac

}
