#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ReplaceSpaces() {
    # the select loop will not parse correctly
    # if we don't replace spaces with underscores
    case "$1" in
        -l)
            find "$MEDIA_DIR" -maxdepth 1 \
            -type d -name "* *" -exec \
            bash -c '
                for d in "$@"; do
                    n="${d##*/}"
                    mv -nv "$d" "${d%/*}/${n// /_}"
                done >/dev/null 2>&1
            ' dummy {} +
        ;;
        -s)
            find {"$playlists_dir","$titles_dir"} -maxdepth 1 \
            -type f -name "* *" -exec \
            bash -c '
                for f in "$@"; do
                    n="${f##*/}"
                    mv -nv "$f" "${f%/*}/${n// /_}"
                done >/dev/null 2>&1
            ' dummy {} +
        ;;
    esac

}
