#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ResizeWindow() {
    # width & height are defined in ~/.config/mpm/mpmrc
    if [[ -n $width && -n $height ]]; then
        wmctrl -r :ACTIVE: -e 5,-1,-1,"$width","$height"
    else
        wmctrl -r :ACTIVE: -e 5,-1,-1,1260,738
    fi
}
