#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_RestoreSchedules() {

    local files
    _Prompt " ${info}Do you want to fix this issue? ${nc}" && {
        case "$1" in
            -n)
                printf '%s\n' " ${info}Moving back m3u files in $playlists_dir."
                mv -f "$schedules_dir"/*.m3u "$playlists_dir"/
                mv -f "$schedules_dir"/*.titles "$titles_dir"/
                sleep 4
            ;;
            -y)
                mapfile -t files < <(sed 's/.*| //g' "$schedulesFile")
                printf '%s\n' " ${info}Restoring m3u files in $schedules_dir${nc}"
                sleep 2
                for file in "${files[@]}"; do
                    mv -f "$playlists_dir/${file}" "$schedules_dir/${file}"
                    mv -f "$titles_dir/${file}".titles "$schedules_dir/${file}".titles
                done
            ;;
        esac
    }
    unset files
    _Menu

}
