#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_RmMpvTmp() {
    mpv_is_running="no"
    rm "$(readlink -f "$NOWPLAYING")" \
    "$SELECTED_URLS1" "$NOWPLAYING" \
    "$FZFENQUEUE" "$pidofMpv" "$LOCALDIRS_LIST" 2>/dev/null
    unset m3uFile
}