#!/bin/bash
## This is a part of main script: mpm.

_Save() {

    cd "$playlists_dir"

    __NestedSave() {
        echo -e " ${g}Available playlists:\n${nc}"
        find . -name "*.m3u" -o -name "*.m3u_origin" \
        | sort -d \
        | sed 's,.*/,,' \
        | cat -n

        __
        read -p ${g}' Save playlist as: '${nc} list
        list="$list.m3u"
        if [[ $(find . -name "${list}") ]]; then
            echo -e " ${r}This playlist already exists!\n Overwrite $list? [y/N]:${nc}"
            read -r overwrite
            case "$overwrite" in
                y|Y)    sed -i '1d' "$QUEUE" # deleting "#EXTM3U"
                        cp -f "$CURRENT" "$list"
                        sed -i '1s/^/#EXTM3U\n/' "$list" "$QUEUE"
                        sed -i '/^https/d' "$CURRENT"
                        echo " ${g}$list saved ${nc}"
                        sleep 3s
                        __ ;;
                N|n)    __ ;;
                *  )    __ ;;
            esac
        else
            cp -f "$CURRENT" "$list"
            sed -i '1s/^/#EXTM3U\n/' "$list"
            sed -i '/^https/d' "$CURRENT"
            echo " ${g}$list saved ${nc}"
            sleep 2s
            __
        fi
    }

    case "$1" in
        -a)
            CURRENT="$AUDIO_INFO"
            __NestedSave
            rm -f $AUDIO_{INFO,TITLE}
            _Menu
        ;;
        -q)
            CURRENT="$QUEUE"
            __NestedSave
            _Menu
        ;;
        -v)
            CURRENT="$VIDEO_INFO"
            __NestedSave
            rm -f $VIDEO_{INFO,TITLE}
            _Menu
        ;;
    esac

}
