#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_SaveList() {
    cd "$playlists_dir" || exit 1
    cp -f "$current_list" "$list"
    cp -f "$current_titles" "$titles_dir"/"$list".titles

    sed -i '1s/^/#EXTM3U\n/' "$list"
    sed -i '/^[[:alpha:]]/d' "$current_list"

    (( $(grep -c -w '#EXTM3U' "$list") > 1 )) \
        && sed -i '1d' "$list"

    if [[ $current_list = "$QUEUE" ]]; then
        rm "$current_titles"
    else
        rm {"$current_list","$current_titles"}
    fi
    __
    printf '%s\n' " ${info}${current_list##*/} saved as $list${nc}"
    sleep 3
}
