#!/bin/bash
## This is a part of main script: mpm.

_Save() {

    cd "$playlists_dir"

    __NestedSave() {
        echo -e " ${g}Available playlists:\n${nc}"
        find . -name "*.m3u" -o -name "*.m3u_origin" \
        | sort -d \
        | sed 's,.*/,,' \
        | cat -n

        __
        read -p ${g}' Save playlist as: '${nc} list
        list="$list.m3u"
        if [[ $(find . -name "${list}") ]]; then
            __
            _Prompt -n " ${r}This playlist already exists! Overwrite $list?: ${nc}" && {
                cp -f "$CURRENT" "$list"
                sed -i '1s/^/#EXTM3U\n/' "$list"
                sed -i '/^https/d' "$CURRENT"
                [[ -f $tmp_dir/1 ]] && rm "$tmp_dir"/1
                if (( $(grep -c -w '#EXTM3U' "$list") > 1 )); then
                    sed -i '1d' "$list"
                fi
                echo " ${g}$list saved.${nc}"
                sleep 3s
            }
            __
        else
            cp -f "$CURRENT" "$list"
            sed -i '1s/^/#EXTM3U\n/' "$list"
            sed -i '/^https/d' "$CURRENT"
            [[ -f $tmp_dir/1 ]] && rm "$tmp_dir"/1
            if (( $(grep -c -w '#EXTM3U' "$list") > 1 )); then
                sed -i '1d' "$list"
            fi
            echo " ${g}$list saved${nc}."
            sleep 2s
            __
        fi
        
    }

    case "$1" in
        -a)
            CURRENT="$AUDIO_INFO"
            __NestedSave
            rm -f $AUDIO_{INFO,TITLE}
        ;;
        -q)
            CURRENT="$QUEUE"
            __NestedSave
        ;;
        -v)
            CURRENT="$VIDEO_INFO"
            __NestedSave
            rm -f $VIDEO_{INFO,TITLE}
        ;;
    esac
    _Menu
}
