#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_SaveList() {
    cd "$playlists_dir" || exit 1
    cp -f "$CURRENT_LIST" "$list"
    cp -f "$CURRENT_TITLES" "$titles_dir"/"$list".titles 2>/dev/null
    
    sed -i '1s/^/#EXTM3U\n/' "$list"
    sed -i '/^[[:alpha:]]/d' "$CURRENT_LIST"
    
    (( $(grep -c -w '#EXTM3U' "$list") > 1 )) \
        && sed -i '1d' "$list"

    if [[ $CURRENT_LIST = "$QUEUE" ]]; then
        __
        printf '%s\n' " ${info}default list saved as $list${nc}"
    else
        rm {"$CURRENT_LIST","$CURRENT_TITLES"}
        __
        printf '%s\n' " ${info}${CURRENT_LIST##*/} saved as $list${nc}"
    fi
    
    sleep 3
}
