#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_SaveLinksAs() {

    local action

    __saveRange() {

        clear
        cp -f "$current_list" "$current_list"_origin
        cp -f "$current_titles" "$current_titles"_origin

        if _TestFzfCommand; then
            action="Save"
            _FzfSaveRemoveTmpLinks
        fi

        IFS=", ";
        if [[ -s $FZFSELTITLES ]]; then
            mapfile -t tmpLinks < "$FZFSELTITLES"
            rm "$FZFSELTITLES"
        else
            # use_fzf=no
            clear
            printf '\n%s\n' " ${info}Select titles to save fron ${current_list##*/}${nc}"
            _BlankLine
            nl "$current_titles"
            _BlankLine
            read -ra tmpLinks -p "$RANGEPROMPT"
        fi

        [[ $current_list == "$DEFAULT_LIST" ]] && sed -i '1d' "$DEFAULT_LIST"

        for range in "${tmpLinks[@]}"; do
            IFS="-"; read -r start end <<< "$range"

            [[ $range =~ [a-zA-Z] ]] && {
                printf '\n%s\n' " ${critical}Addition aborted...${nc}"
                rm {"$current_list","$current_titles"}_origin
                sleep 2; unset IFS range
                if [[ $current_list == "$DEFAULT_LIST" ]]; then
                    sed -i '1s/^/#EXTM3U\n/' "$DEFAULT_LIST"
                    _Menu
                else
                    _CreateAddPlaylist "$arg"
                fi
            }

            [[ -z $start ]] && continue
            [[ -z $end ]] && end="$start"

            for ((i=start;i<=end;i++)); do
                sed -n "${i}p" "$current_list" >> "$current_list"_tmp
                sed -n "${i}p" "$current_titles" >> "$current_titles"_tmp
            done

        done

        unset IFS range
        mv -f "$current_list"_tmp "$current_list"
        mv -f "$current_titles"_tmp "$current_titles"
        _RemoveDuplicateLines "$current_list" "$current_titles"

    }

    _ResizeWindow --main; clear
    _BlankLine
    printf '%s\n' " ${critical}Tip: If you want to add links to an existing playlist," \
    " in the next menu select it and answer NO to the overwrite question," \
    " then you can add your links by typing ${task}'a'${nc}"
    _BlankLine
    read -rsn 1 -p " ${info}[${mtitle}C${info}]ancel, Save [L]inks or the [W]hole list?: ${nc}" \
    saveLinksAsOptions

    case "$saveLinksAsOptions" in
        [cC]) return ;;
        [lL]) __saveRange && touch "$tmp_dir"/saveLinks && _SaveCheck ;;
        [wW]) _SaveCheck ;;
        *)   _WrongOption "$saveLinksAsOptions"; return ;;
    esac

}
