#!/bin/bash
## This is a part of main script: mpm.

_SaveRemove() {

    cd "$playlists_dir"

    prompt=( "[B]ack to menu," "[S]ave default," "Save [A]udio," \
    "Save [V]ideo," "[R]emove a playlist." )

    if [[ -f $AUDIO_INFO ]] && [[ -f $VIDEO_INFO ]]; then
        if (( $(_GetLinesList -q) < 1 )); then
            unset prompt[1]
            echo ${g} "${prompt[*]}" ${nc}
            __
        else
            echo ${g} "${prompt[@]}" ${nc}
            __
        fi
    elif [[ -f $AUDIO_INFO ]]; then
        if (( $(_GetLinesList -q) < 1 )); then
            unset {prompt[1],prompt[3]}
            echo ${g} "${prompt[*]}" ${nc}
        else
            unset prompt[3]
            echo ${g} "${prompt[*]}" ${nc}
            __
        fi
    elif [[ -f $VIDEO_INFO ]]; then
        if (( $(_GetLinesList -q) < 1 )); then
            unset {prompt[1],prompt[2]}
            echo ${g} "${prompt[*]}" ${nc}
        else
            unset prompt[2]
            echo ${g} "${prompt[*]}" ${nc}
            __
        fi
    elif (( $(_GetLinesList -q) < 1 )); then
        echo -e " ${r}Nothing to save, maybe remove something?${nc}\n"
        unset {prompt[1],prompt[2],prompt[3]}
        echo ${g} "${prompt[*]}" ${nc}
        __
    else
        unset {prompt[2],prompt[3]}
        echo ${g} "${prompt[@]}" ${nc}
        __
    fi
    read -rsn 1 opt
    case "$opt" in
        a|A)    _Save -a ;;
        b|B)    _Menu ;;
        s|S)    rm -f "$tmp_dir"/1 2>/dev/null
                _Save -q ;;
        r|R)    PS3=${g}' Choose a playlist to remove: '${nc}
                __
                select list in $(find . -not -name "default.m3u" -name "*.m3u" -o -name "*.m3u_origin" \
                    | sort -d | sed 's,.*/,,'); do
                    __
                    echo -e " ${r}Are you sure you want to remove $list? [y/N]: ${nc}\n"
                    read -sn1  del
                    case "$del" in
                        y|Y)
                            rm "$list"
                            echo " ${r}$list removed.${nc}"
                            sleep 3s
                        ;;
                        N|n)
                            echo " ${g}$list preserved.${nc}"
                            sleep 3s
                        ;;
                    esac
                    break
                done
        ;;
        v|V)    _Save -v ;;
    esac

}
