#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2034,SC2154,SC2086
_Save() {

    cd "$playlists_dir" || exit 1

    case "$1" in
        -a)
            if [[ -f $AUDIO_URLS ]]; then
                CURRENT_LIST="$AUDIO_URLS"
                CURRENT_TITLES="$AUDIO_TITLES"
                _SaveCheck
                _ReplaceSpaces -s
            else
                echo " ${critical}No links in the list${nc}"
                sleep 2
                _CopyAudio
            fi
        ;;
        -q)
            CURRENT_LIST="$QUEUE"
            if [[ -f $DEFAULTITLES ]]; then
                CURRENT_TITLES="$DEFAULTITLES"
            else
                CURRENT_TITLES="$DEFAULTM3UTITLES"
            fi
            _SaveCheck
            _ReplaceSpaces -s
        ;;
        -v)
            if [[ -f $VIDEO_URLS ]]; then
                CURRENT_LIST="$VIDEO_URLS"
                CURRENT_TITLES="$VIDEO_TITLES"
                _SaveCheck
                _ReplaceSpaces -s
            else
                echo " ${critical}No links in the list${nc}"
                sleep 2
                _CopyVideo
            fi
        ;;
    esac
    _Menu
}