#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2086,SC2184
_SaveRemove() {

    cd "$playlists_dir" || exit 1

    prompt=( "[B]ack to menu," "[S]ave default," "Save [A]udio," \
    "Save [V]ideo," "[R]emove a playlist." )

    if [[ -f $AUDIO_INFO ]] && [[ -f $VIDEO_INFO ]]; then
        if (( $(_GetLinesList -q) < 1 )); then
            unset prompt[1]
            echo "${info}" "${prompt[*]}" "${nc}"
            __
        else
            echo "${info}" "${prompt[@]}" "${nc}"
            __
        fi
    elif [[ -f $AUDIO_INFO ]]; then
        if (( $(_GetLinesList -q) < 1 )); then
            unset {prompt[1],prompt[3]}
            echo "${info}" "${prompt[*]}" "${nc}"
        else
            unset prompt[3]
            echo "${info}" "${prompt[*]}" "${nc}"
            __
        fi
    elif [[ -f $VIDEO_INFO ]]; then
        if (( $(_GetLinesList -q) < 1 )); then
            unset {prompt[1],prompt[2]}
            echo "${info}" "${prompt[*]}" "${nc}"
        else
            unset prompt[2]
            echo "${info}" "${prompt[*]}" "${nc}"
            __
        fi
    elif (( $(_GetLinesList -q) < 1 )); then
        echo -e " ${critical}Nothing to save, maybe remove something?${nc}\n"
        unset {prompt[1],prompt[2],prompt[3]}
        echo "${info}" "${prompt[*]}" "${nc}"
        __
    else
        unset {prompt[2],prompt[3]}
        echo "${info}" "${prompt[@]}" "${nc}"
        __
    fi

    read -rsn 1 opt
    case "$opt" in
        a|A) _Save -a ;;
        b|B) _Menu ;;
        s|S)
            rm -f "$tmp_dir"/1 2>/dev/null
            _Save -q
        ;;
        r|R)
            clear; __
            PS3=""$'\n'" ${info}Choose a playlist to remove:${nc} "
            __
            select m3ufile in $(find "$playlists_dir" -not -name "default.m3u" \
                -name "*.m3u" -o -name "*.m3u_origin" \
                | sort -d | sed 's,.*/,,'); do
                __
                _Prompt -n \
                " ${critical}Are you sure you want to remove $m3ufile?: ${nc}" && {
                    rm {"$m3ufile","$titles_dir"/"$m3ufile".titles}
                    __
                    echo " ${critical}$m3ufile removed.${nc}"
                    sleep 3s
                    break
                }
                __
                echo " ${info}$m3ufile preserved"
                sleep 2s
                break
            done
        ;;
        v|V) _Save -v ;;
    esac
    _Menu
}

