#!/bin/bash
## This is a part of main script: mpm.

_SaveList() {
    cp -f "$CURRENT_LIST" "$list"
    cp -f "$CURRENT_TITLE" "$titles_dir"/"$list".titles
    sed -i '1s/^/#EXTM3U\n/' "$list"
    sed -i '/^https/d' "$CURRENT_LIST"
    (( $(grep -c -w '#EXTM3U' "$list") > 1 )) \
        && sed -i '1d' "$list"

    echo " ${info}$list saved.${nc}"
    sleep 2s
}
 
