#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2086
_SaveCheck() {
    clear
    cd "$playlists_dir" || exit 1
    
    local listTotal
    listTotal=$(find . -not -name "default.m3u" -name "*.m3u" \
    -o -name "*.m3u_origin" | sort -d | sed 's,.*/,,' | wc -l)    
    __
    PS3=""$'\n'" ${info}Available playlists (type ${task}$((listTotal + 1)) ${info}to create a new one):${nc} "
    select list in $(find . -not -name "default.m3u" -name "*.m3u" \
    -o -name "*.m3u_origin" | sort -d | sed 's,.*/,,'); do
        [[ $REPLY != $((listTotal + 1)) ]] && {
            if [[ $(find . -name "${list}") ]]; then
                __
                _Prompt -n " ${critical}$list already exists! Overwrite it?: ${nc}" && {
                    _SaveList && break
                }
                __
                read -rp "${info}"' Save playlist as (do not use extension): '"${nc}" list
                list="$list.m3u"
                _SaveList && break
            else
                __
                printf '%s\n' " ${critical}wrong answer $REPLY, try again...${nc}"
                sleep 4
                break
            fi
        }
        __
        read -rp "${info}"' Save the new playlist as (do not use extension): '"${nc}" list
        list="$list.m3u"
        _SaveList && break
    done
}
