#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2086,SC2184
_SaveOnExit() {

    _Prompt -n \
        " ${critical}Some temporary lists aren't saved, quit anyway?: ${nc}" && {
        clear
        nc=$'\e[0m';
        SKULL=(
            "███████████████████████████" \
            "███████▀▀▀░░░░░░░▀▀▀███████" \
            "████▀░░░░░░░░░░░░░░░░░▀████" \
            "███│░░░░░░░░░░░░░░░░░░░│███" \
            "███│░░░░░░░░░░░░░░░░░░░│███" \
            "██▌│░░░░░░░░░░░░░░░░░░░│▐██" \
            "██░└┐░░░░░░░░░░░░░░░░░┌┘░██" \
            "██░░└┐░░░░░░░░░░░░░░░┌┘░░██" \
            "██░░┌┘▄▄▄▄▄░░░░░▄▄▄▄▄└┐░░██" \
            "██▌░│██████▌░░░▐██████│░▐██" \
            "██▌░│██████▌░░░▐██████│░▐██" \
            "███░│▐███▀▀░░▄░░▀▀███▌│░███" \
            "██▀─┘░░░░░░░▐█▌░░░░░░░└─▀██" \
            "██▄░░░▄▄▄▓░░▀█▀░░▓▄▄▄░░░▄██" \
            "████▄─┘██▌░░░░░░░▐██└─▄████" \
            "█████░░▐█─┬┬┬┬┬┬┬─█▌░░█████" \
            "█████▄░░░└┴┴┴┴┴┴┴┘░░░▄█████" \
            "███████▄░░░░░░░░░░░▄███████" \
            "██████████▄▄▄▄▄▄▄██████████" \
        )
        for skullParts in "${SKULL[@]}"; do
            echo -e "$skullParts"
            sleep 0.05
        done

        printf '%s\n' " ${critical}TOO BAD...BYE${nc}"
        exit
    }
    cd "$playlists_dir" || exit 1

    saveOnExitPrompt=( "[B]ack to menu" "Save [A]udio list" "Save [V]ideo list" )

    if [[ -f $AUDIO_URLS && -f $VIDEO_URLS ]]; then
        __
        echo -e " ${info}${saveOnExitPrompt[*]}${nc}"
    elif [[ -f $AUDIO_URLS && ! -f $VIDEO_URLS ]]; then
        unset saveOnExitPrompt[2]
        __
        echo -e " ${info}${saveOnExitPrompt[*]}${nc}"
    elif [[ -f $VIDEO_URLS && ! -f $AUDIO_URLS ]]; then
        unset saveOnExitPrompt[1]
        __
        echo -e " ${info}${saveOnExitPrompt[*]}${nc}"
    fi

    read -rsn 1 saveOnExitOptions
    case "$saveOnExitOptions" in
        a|A) _Save -a ;;
        b|B) _Menu ;;
        v|V) _Save -v ;;
    esac

}
