#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ScheduleDownload() {

    [[ -z $schedules_dir ]] && {
        printf '%s\n' " ${critical}schedule_dir isn't defined..." \
        " Please check your mpmrc file${nc}"
        sleep 4
        _Menu
    }

    local schedules_file schedules_lists schedules_datetime lst_count dash
    schedules_file="$schedules_dir/schedules.txt"
    schedules_lists="$schedules_dir/schedules_lists"
    lst_count=0

    [[ ! -d $schedules_dir ]] && mkdir -p "$schedules_dir"

    __sortSchedulesFile() { sort -t'|' -k1 "$schedules_file" -o "$schedules_file"; }
    __createSchedulesLists() {
        cat "$schedules_file" > "$schedules_lists"
        sed -i 's/.*| //g' "$schedules_lists"
    }
    __removeSchedulesFiles() {
        [[ ! -s "$schedules_file" ]] && rm "$schedules_file"
        rm "$schedules_lists"
    }

    [[ -n $schedule_date ]] && unset schedule_date
    [[ -n $schedule_time ]] && unset schedule_time

    clear
    # Print existing schedules with line numbers if file exists
    if [[ -f "$schedules_file" ]]; then
        __createSchedulesLists
        echo -e "\n ${info}${B}Current schedules:${NB}${nc}\n"
        dash=$(printf "%-72s" "─")
        printf '%s\n' \
        "  ${info}DATE & TIME          | TYPES | PLAYLISTS${nc}"
        echo " ${info}${dash// /─}${nc}"
        __sortSchedulesFile
        nl -w2 -s') ' "$schedules_file"
    fi

    printf '\n%s\n' " ${critical}Ensure that the mpmsw script is in your \$PATH.${nc}"

    _BlankLine
    read -rn 10 \
    -p " ${info}Enter date (YYYY-MM-DD) for playlist '$LIST': ${nc}" schedule_date
    # Validate date format strictly matches YYYY-MM-DD
    if [[ ! "$schedule_date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
        printf '\n%s\n' \
        " ${critical}Invalid date format, try again.${nc}"
        sleep 3
        clear
        return
    else
        _BlankLine
        read -rn 5 \
        -p " ${info}Enter time (HH:MM) for playlist '$LIST': ${nc}" schedule_time
         # Validate time format
        if [[ ! $schedule_time =~ ^[0-2][0-9]:[0-5][0-9]$ ]]; then
            printf '\n%s\n' \
            " ${critical}Invalid time format , try again.${nc}"
            sleep 3
            clear
            return
        else
            schedules_datetime="$schedule_date @ $schedule_time"
            _BlankLine
            read -r -p " ${info}Type of download, [A]udio or [V]ideo?: ${nc}" downloadType
            case "${downloadType}" in
                [aA]) echo "$schedules_datetime | audio | $list" >> "$schedules_file" ;;
                [vV]) echo "$schedules_datetime | video | $list" >> "$schedules_file" ;;
                *)
                    _WrongOption "$downloadType"
                    return
                ;;
            esac

            _RemoveDuplicateLines "$schedules_file"
            __createSchedulesLists

            while read -r line; do
                [[ $line =~ ^$schedule_date && $line =~ $schedule_time ]] && ((lst_count++))
            done < "$schedules_file"
            if ((lst_count > 1)); then
                sed -i '$d' "$schedules_file"
                __removeSchedulesFiles
                printf '\n%s\n' \
                " ${critical}Scheduled downloads time already exists...Schedule cancelled.${nc}"
                sleep 4
                clear
                return
            fi

            _BlankLine
            _Prompt " ${info}Schedule download of $LIST for ${task}$schedule_datetime?${nc}" || {
                sed -i '$d' "$schedules_file"
                __removeSchedulesFiles
                printf '\n%s\n' " ${critical}Schedule cancelled.${nc}"
                sleep 2
                clear
                return
            }
            __sortSchedulesFile
            mv -f "$playlists_dir/$list" "$schedules_dir/$list"
            mv -f "$titles_dir/$list.titles" "$schedules_dir/$list.titles"
            __removeSchedulesFiles
            printf '%s\n' " ${info}Playlist '$LIST' download scheduled.${nc}"
            sleep 2
            _ValidateSchedules
            clear
            _Menu
        fi
    fi

}
