#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_SearchYoutubeWithFzf() {

    local jqSearch jqPreview jqPreviewCmd fzfGrabLinks

    _ResizeWindow --main
    _BlankLine
    read -rp " ${info}Search for ${platform} ${Type} (no quotes): ${nc}" request
    clear
    [[ -z $request ]] && return

    jqSearch='.title + "\u0000", ., "\n"'
    jqPreview='
        "\u001b[0;1m" + .title + "\u001b[0m" + "\n" + "duration: " + if (.duration | isfinite) then
        (.duration_string | tostring) else "?" end + " | views: " + if (.view_count | isfinite) then
        (.view_count | tostring) else "?" end + " | " + .uploader + "\n\n" + .description + "\n\n\n"
    '
    jqPreviewCmd="cat {f2} \
        | jq -jr $(printf '%q' "$jqPreview");[ '{n}' != '{+n}' ] \
        && echo -e '\033[33;1m---   Playlist   ---\033[0m' && \
        cat {+f2} | jq -jr $(printf '%q' "$jqPreview")
    "
    fzfGrabLinks=$(
        yt-dlp ytsearch"${ytdlPreset_NR[0]}":"$request" -j --flat-playlist \
        | jq -r 'select(.title | startswith("#") | not)' \
        | jq -cj "$jqSearch" \
        | fzf \
            --multi \
            --cycle \
            --reverse \
            --scroll-off=5 \
            --pointer '<>' \
            --border rounded \
            --prompt='Search: ' \
            --preview="$jqPreviewCmd" \
            --preview-window="down:2" \
            -n 1 --with-nth=1 -d '\0' --ansi \
            --border-label "| Results for: $request |" \
            --header='Tab: select, Enter: confirm, Escape: cancel' \
        | cut -d '' -f2 \
        | jq --raw-output '(.webpage_url, .title)'
    )

    if [[ -z $fzfGrabLinks ]]; then
        printf '\n%s\n' " ${critical}No ${Type} selected...${nc}"
        sleep 2; clear; return
    else
        while read -r line; do
            if [[ $line =~ ^https ]]; then
                echo "$line" | tee -a "$URLS" >> "$DEFAULT_LIST"
            else
                echo "$line" | tee -a "$TITLES" >> "$DEFAULT_TITLES"
            fi
        done <<< "$fzfGrabLinks"
        unset line
        _RemoveCrap
        _ViewAudioVideoUrlsInfo "$arg"
    fi

}
