#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015
_SearchOnline() {
    __
    command -v ytfzf >/dev/null && {
        read -rsn1 \
        -p " ${info}Search ${Type} with regular [f]zf or [y]tfzf script?: ${nc}" \
        searchOnlineOptions
        
        case "$searchOnlineOptions" in
            f|F)
                _SearchYoutubeWithFzf
            ;;
            y|Y)
                _SearchOnlineWithYtfzf
            ;;
            *)
                _WrongOption "$searchOnlineOptions"
                clear
            ;;
        esac
    } || _SearchYoutubeWithFzf

}