#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_SearchOnline() {

    local pkg platform

    __searchOnlineTips() (
        clear
        _BlankLine
        printf '%s\n' \
        " ${critical}Tip: In the ${pkg} menu press ${task}Tab ${critical}on the desired ${Type} titles," \
        " then press ${task}Enter ${critical}to confirm, ${task}Escape ${critical}to cancel." \
        " (note that multi-selection is supported)${nc}"
    )

    __isPkgInstalled() {

        ! _Has "$pkg" && {
            printf '%s\n' " ${critical}$pkg isn't installed...${nc}"
            sleep 2
            _CreateAddPlaylist "$arg"
        }

    }

    _ResizeWindow --main; clear

    while true; do
        test -s "$URLS"  && \
        echo -e "\n ${info}${Type} list: $(_GetLinesList "$arg") url(s)${nc}\n"
        _BlankLine
        printf '%s\n' "                                            ${mtitle}::SEARCH ONLINE $menuTitleType OPTIONS::${nc}" \
        "                                          $(_LittleStars)${nc}" \
        "                                  ┌─────────────────────────────────────────────────┐" \
        "                                  │   1) Fzf Youtube only   4) Ytfzf PeerTube       │" \
        "                                  │   2) ${critical}Ytfzf Youtube${nc}      5) Back to ${Type} menu   │" \
        "                                  │   3) Ytfzf Odysee       6) Back to Main menu    │" \
        "                                  └─────────────────────────────────────────────────┘" \
        "                                                  ${info}Select an option${nc}"

        read -rsn 1 searchOnlineOptions

        case "$searchOnlineOptions" in
            [fF1])
                pkg=fzf
                __isPkgInstalled
                platform=YouTube
                __searchOnlineTips
                _SearchYoutubeWithFzf
            ;;
            [yY2])
                pkg=ytfzf
                __isPkgInstalled
                platform=YouTube
                __searchOnlineTips
                _SearchOnlineWithYtfzf -y
            ;;
            [oO3])
                pkg=ytfzf
                __isPkgInstalled
                platform=Odysee
                __searchOnlineTips
                _SearchOnlineWithYtfzf -o
            ;;
            [pP4])
                pkg=ytfzf
                __isPkgInstalled
                platform=Peertube
                __searchOnlineTips
                _SearchOnlineWithYtfzf -p
            ;;
            [aAvV5])  return ;;
            [bBmM6])  _Menu ;;
            *)
                _WrongOption "$searchOnlineOptions"
                clear
            ;;
        esac

    done

}
