#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015
_SearchOnline() {

    local pkg

    __searchOnlineTips() (
        clear
        __
        printf '%s\n' \
        " ${critical}Tip: In the ${pkg} menu press ${task}Tab ${critical}on the desired ${Type} titles," \
            " then press ${task}Enter ${critical}to confirm. Press ${task}Escape ${critical}to cancel." \
            " (note that multi selection is supported)${nc}"
    )

    if [[ -n $(command -v fzf) && -n $(command -v ytfzf) ]]; then
        __
        read -rsn1 \
        -p " ${info}Search ${Type} with regular [F]zf or [Y]tfzf script?: ${nc}" \
        searchOnlineOptions
        
        case "$searchOnlineOptions" in
            f|F)
                pkg="fzf"
                __searchOnlineTips
                _SearchYoutubeWithFzf
            ;;
            y|Y)
                pkg="ytfzf"
                __searchOnlineTips
                _SearchOnlineWithYtfzf
            ;;
            *)
                _WrongOption "$searchOnlineOptions"
                clear
            ;;
        esac

    elif command -v fzf >/dev/null; then
        pkg="fzf"
        __searchOnlineTips
        _SearchYoutubeWithFzf
    elif command -v ytfzf >/dev/null; then
        pkg="ytfzf"
        __searchOnlineTips
        _SearchOnlineWithYtfzf
    else
        printf '%s\n' " ${critical}neither fzf nor ytfzf are installed...${nc}"
        sleep 3
        return
    fi

}