#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015
_SearchYoutube() {
    __
    command -v ytfzf >/dev/null && {
        read -rsn1 -p " ${info}Search ${Type} with regular [f]zf or [y]tfzf script?: ${nc}" searchTool
        
        case "$searchTool" in
            f|F)
                _SearchYoutubeWithFzf
            ;;
            y|Y)
                _SearchYoutubeWithYtfzf
            ;;
            *)
                __; printf '%s\n' " ${critical}Wrong option $searchTool...${nc}"
                sleep 3
                clear
            ;;
        esac
    } || _SearchYoutubeWithFzf

}
