#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2076
_SearchOnlineWithYtfzf() {

    _ResizeWindow --main
    echo -e "${info} Your ytfzf options:${task}${ytfzfOptions_X[*]}${nc}\n" \
    | sed 's/keep-cache//;s/--//g'

    read -rp \
    " ${info}Search ${platform} for ${Type} links (Use \"quotes\" for multiple search terms): ${nc}" \
    request

    [[ -z $request ]] && clear && return

    local ytpl lbry

    case "$1" in
        -o)
            ytfzf --show-thumbnails \
            -I VJ -c odysee "${ytfzfOptions_X[@]}" "$request$*" >> "$YTFZFJSON"
        ;;
        -p)
            ytfzf --show-thumbnails \
            -I VJ -c peertube "${ytfzfOptions_X[@]}" "$request$*" >> "$YTFZFJSON"
        ;;
        -y)
            invidious_instance="https://vid.puffyan.us" ytfzf --show-thumbnails \
            -I VJ -c youtube "${ytfzfOptions_X[@]}" "$request$*" >> "$YTFZFJSON"
        ;;
    esac

    clear
    test ! -s "$YTFZFJSON" && {
        rm "$YTFZFJSON"
        printf '%s\n' \
        " ${critical}Nothing was scraped, back in SEARCH ONLINE ${Type^^} OPTIONS${nc}"
        sleep 3; clear
        return
    }

    jq --raw-output '.[].url' "$YTFZFJSON" | tee -a "$DEFAULT_LIST" >> "$URLS"
    jq --raw-output '.[].title' "$YTFZFJSON" | tee -a "$DEFAULT_TITLES" >> "$TITLES"

    cat "$DEFAULT_LIST" "$URLS" > "$tmp_dir"/ytfzf_playlists

    ytpl="playlist?list="
    lbry="odysee.com/$/playlist/"

    while read -r line; do
        [[ $line =~ "$ytpl"|"$lbry" ]] && \
            echo "$line" >> "$YTSEARCH"
    done < "$tmp_dir"/ytfzf_playlists

    [[ -s $YTSEARCH ]] && _RemoveDuplicateLines "$YTSEARCH"
    _RemoveCrap
    rm {"$YTFZFJSON","$tmp_dir"/ytfzf_playlists}
    printf '\n%s\n' " ${info}Links added to $Type list${nc}"
    sleep 2; clear

}
