#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_SearchOnlineWithYtfzf() {
    __
    printf '%s\n' " ${critical}Tip: To select mutiple links in the ytfzf menu press ${task}Tab" \
    " ${critical}on the desired ${Type} titles, ${task}Ctrl P${critical} to view next page...etc" \
    " then ${task}Enter ${critical}to confirm and go back in $menuTitleType OPTIONS menu.${nc}"
    __
    read -rp " ${info}Search for online ${Type} links: ${nc}" request

    if [[ -n $request ]]; then
        # ytfzf_options are defined in ~/.config/mpm/mpmrc
        # those flags will display thumbnails and whrite a json file
        ytfzf -tI VJ "${ytfzfOptions_X[@]}" "$request$*" >> "$tmp_dir"/ytfzf.json
        
        clear
        test ! -s "$tmp_dir"/ytfzf.json && return

        jq '.[].url' "$tmp_dir"/ytfzf.json | sed 's/"//g' \
        | tee -a "$QUEUE" >> "$URLS"
        jq '.[].title' "$tmp_dir"/ytfzf.json | sed 's/"//g' \
        | tee -a "$DEFAULTITLES" >> "$TITLES"
        _RemoveCrap

        for file in {"$QUEUE","$URLS"}; do
            while read -r line; do
                [[ $line =~ 'playlist?list=' ]] && \
                    echo "$line" >> "$YTSEARCH"
            done < "${file}"
        done

        perl -i -ne 'print if ! $a{$_}++' "$YTSEARCH" 2>/dev/null
        sed -i '/playlist/d' {"$QUEUE","$URLS"}
        __; printf '%s\n' " ${info}Links added to $Type list${nc}"
        sleep 2
        rm "$tmp_dir"/ytfzf.json

    else
        return
    fi
    
}