#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_SelectLocalDir() {
        
    cd "$MEDIA_DIR" || exit 1

    echo -e " ${info}Directories in ${MEDIA_DIR##*/}: ${nc}\n"

    PS3=""$'\n'" ${info}Select a directory number: ${nc}"

    select dir in $(find -L "$MEDIA_DIR" -maxdepth 1 -type d -not -name \
        "$(echo "$MEDIA_DIR" | awk -F"/" '{print $NF}')" | sort | sed 's,.*/,,'); do
        
        if [[ $(find "$MEDIA_DIR"/"$dir" -type d -name "$dir" -empty) ]]; then
            __
            printf '%s\n' " ${critical}$dir is empty. Wait and try again...${nc}"
            sleep 3
            continue
        else
            find "$MEDIA_DIR"/"$dir" -maxdepth 1 -type d -empty -exec rmdir {} \;
            # checking if the content of directory is audio/video.
            __
            printf '%s\n' " ${info}Scanning $dir for supported formats by mpv${nc}"
            sleep 1
            ! find "$MEDIA_DIR"/"$dir" -maxdepth 1 -type f \
            -exec file -N -i -- {} + | grep -q -E '[aA]udio|[vV]ideo' && {
                __
                printf '%s\n' " ${critical}$dir does not contain supported formats by mpv" \
                " or some files aren't audio/video stuff," \
                " they may be in subdirectories...${nc}"; __
                _Prompt " ${info}Do you want to open $dir and try again? ${nc}" || {
                    continue
                }
                "$FILEMANAGER" "$dir"
            }
            
            clear

            if [[ $use_mpvc = yes ]]; then
                _MakeMpvPlaylist --local-background
            elif [[ $use_mpvc = no ]]; then
                _MakeMpvPlaylist --local-background
            else
                _MakeMpvPlaylist --local-foreground
            fi
            break
        fi
        
    done

}