#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2034
_SelectLocalDir() {

    cd "$localDir" || exit 1
    
    echo -e " ${info}Directories in ${localDir##*/}: ${nc}\n"

    PS3=""$'\n'" ${info}Select a directory number to queue/parse, [${mtitle}C${info}]ancel: ${nc}"

    select dir in $(find -L "$localDir" -maxdepth 1 -type d -not -empty \
        -not -wholename "$localDir" | sort | sed 's,.*/,,'); do

            case "$REPLY" in
                [a-zA-Z])
                    if [[ -f $FZFENQUEUE ]]; then
                        __
                        _Prompt " ${critical}Play existing playlist?${nc}" || {
                            rm "$FZFENQUEUE"; return
                        }
                        if [[ $localMediaType == audio ]]; then
                            _LoadAudioVideo -fa
                        elif [[ $localMediaType == video ]]; then
                            _LoadAudioVideo -fv
                        else
                            m3uFile="$FZFENQUEUE"
                            ln -sfr "$m3uFile" "$NOWPLAYING"
                            _MakeMpvPlaylist --fzf
                        fi
                    fi
                    return
                ;;
            esac

        printf '\n%s\n' " ${info}Scanning $dir for supported formats...${nc}"
        sleep 1

        ! find -L ./"$dir" -maxdepth 1 -type f -exec file --mime-type {} + \
        | grep -qE '[aA]udio|[vV]ideo' && {
            printf '\n%s\n' " ${critical}$dir doesn't contain supported formats by mpv" \
            " or audio/video files may be in a subdirectories.${nc}"
            __
            _Prompt " ${info}Do you want to open $dir to fix this issue?${nc}" || {
                continue
            }
            "$FILEMANAGER" "$dir"
        }

        clear

        case "$1" in
            -d)
                if [[ $use_mpvc == yes || $use_mpvc == no ]]; then
                    _MakeMpvPlaylist --local-background
                else
                    _MakeMpvPlaylist --local-foreground
                fi
                _Menu
            ;;
            -f)
                _FzfEnqueue
                clear; break
            ;;
        esac

    done

}
