#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_StartUp() {
    # we have to warn the user when the default list isn' t empty,
    (($(_GetLinesList -q) >= 1)) && {
        touch "$tmp_dir"/1
        cp -f "$DEFAULTM3UTITLES" "$DEFAULTITLES"
        rm "$DEFAULTM3UTITLES"
    }

    [[ -f $CHOOSE1 ]] && rm "$CHOOSE1"

    _Theme "$THEME"
    _Menu
}