#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2207
_StartUp() {

    local MPM pids
    # avoids running multiple instances
    MPM=$(basename "$0")
    pids=($(pidof -x "$MPM"))

    [[ ! -e $NOWPLAYING && ${#pids[@]} -gt 1 ]] && {
        printf '%s\n' 'mpm_test is already running...'
        notify-send -t 0 -u critical "mpm_test is already running..."
        exit 1
    }
    
    [[ -s $DEFAULTM3UTITLES && -s $QUEUE ]] && {
        touch "$tmp_dir"/1
        cp -f "$DEFAULTM3UTITLES" "$DEFAULTITLES"
        rm "$DEFAULTM3UTITLES"
    }

    ! pgrep -x mpv >/dev/null && \
    rm "$NOWPLAYING" "$tmp_dir"/temporary* 2>/dev/null
    
    _Menu
}
