#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_TestParallelCommand() {
    [[ -n $(command -v parallel) \
        && $use_parallel = yes \
        && $use_parallel_downloads = yes ]]
}