#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_TestIfPlaylistsHaveTitles() {

    clear
    local tls pls pl
    tls=("$titles_dir"/*.titles)
    pls=("$playlists_dir"/*.m3u)

    ((${#tls[@]} != (${#pls[@]} - 1))) && {
        for pl in "${pls[@]}"; do
            if [[ $pl =~ default.m3u ]]; then
                continue
            elif [[ ! -f "$titles_dir"/${pl##*/}.titles ]]; then
                _BlankLine
                printf '%s\n' " ${critical}${pl##*/}.titles does not exist...${nc}" \
                " ${task}${b}Updating titles...please wait.${nb}${nc}"
                _GetMediaTitle --pls
            fi
        done
        unset pl
    }

    clear

}
