#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_TestIfPlaylistsHaveTitltes() {

	clear
    local tls numtls pls numpls
    tls=(*.titles) numtls="${#tls[@]}"
    pls=("$playlists_dir"/*.m3u) numpls=$((${#pls[@]} -1))

    (( numtls != numpls )) && {
        local pl
        for pl in "${pls[@]}"; do
            if [[ $pl =~ default.m3u ]]; then
                continue
            elif [[ ! -f ${pl##*/}.titles ]]; then
                _BlankLine
                printf '%s\n' " ${critical}${pl##*/}.titles does not exist...${nc}" \
                " ${task}${b}Updating titles...please wait.${nb}${nc}"
                _GetMediaTitle --fzf
            fi
        done
    }
	unset tls pls numpls nuntls

}