#!/bin/bash
## This is a part of main script: mpm.

_TitlesListCompare() {
    # first test if $list.titles exist.
    if [[ -f $titles_dir/$list.titles ]]; then
        if (( $(grep "" -c "$titles_dir/$list.titles") \
            != $(_GetLinesList -l) )); then
            __
            echo -e " ${c}${b}Updating titles...please wait.${nb}${nc}\n"
            _GetMediaTitle -l > "$titles_dir"/"$list".titles
        fi
        __
        echo -e " ${g}Titles for $list.${nc}\n"
        cat -n "$titles_dir"/"$list".titles
        __
    else
        echo -e " ${c}${b}Getting titles...please wait.${nb}${nc}\n"
        _GetMediaTitle -l > "$titles_dir"/"$list".titles
        cat -n "$titles_dir"/"$list".titles
        __
    fi
}

