#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_TitlesListCompare() {

    cd "$titles_dir" || return

    local titles
    titles="$titles_dir/$list.titles"
    titles="${titles##*/}"

    # first test if "myplaylist".titles exist.
    if [[ -s $titles ]]; then

        if [[ $(grep "" -c "$titles") -ne $(_GetLinesList -l) ]]; then
            __
            printf '%s\n' " ${critical}${titles} is out of date...${nc}" \
            " ${task}${b}Updating titles...please wait.${nb}${nc}"
            _GetMediaTitle -l > "$titles_dir"/"$list".titles
            clear
        fi

        case "$1" in
            -g)
                echo -e " ${info}Titles for $list.${nc}\n"
                sed -n '1,25p' "$titles" | cat -n
                __
                read -rsn 1 -p " ${info}Press 'n' for next page${nc} " nextpage
                case "$nextpage" in
                    n|N)
                        clear; __
                        sed -n '26,$p' "$titles" | cat -n
                        __
                    ;;
                    *)
                        __
                        printf '%s\n' " ${critical}Wrong option $nextpage...${nc}"
                        sleep 3s
                        _Menu
                    ;;
                esac
            ;;
            -l)
                __
                echo -e " ${info}Titles for $list ( ${mtitle}Enter C to cancel${nc} )\n"
                cat -n "$titles"
                __
            ;;
        esac
        
    else
        printf '%s\n' " ${critical}${titles} does not exist...${nc}" \
        " ${task}${b}Getting titles...please wait.${nb}${nc}"
        _GetMediaTitle -l > "$titles_dir"/"$list".titles
        clear
        __
        echo -e " ${info}Titles for $list.${nc}\n"
        cat -n "$titles"
        __

    fi

}