#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_TitlesListCompare() {

    cd "$titles_dir" || return

    local titlesFile
    titlesFile="$titles_dir/$list.titles" 
    titlesFile="${titlesFile##*/}"

    if [[ -s $titlesFile ]]; then

        [[ $(grep "" -c "$titlesFile") -ne $(_GetLinesList -l) ]] && {
            _BlankLine
            printf '%s\n' " ${critical}${titlesFile} is out of date...${nc}" \
            " ${task}${b}Updating $(_GetLinesList -l) titles...please wait.${nb}${nc}"
            _GetMediaTitle -l
            clear
        }

        case "$1" in
            -g)
                echo -e "\n ${info}Titles for $list.${nc}\n"
                # sed -n '1,25p' "$titlesFile" | nl
                awk 'NR>=1&&NR<=25' "$titlesFile" | nl
                _BlankLine
                read -rsn 1 -p " ${info}[N]ext page, [B]ack to menu.${nc}" nextpage
                case "$nextpage" in
                    b|B) _Menu ;;
                    n|N)
                        clear; _BlankLine
                        # sed -n '26,50' "$titlesFile" | nl
                        awk 'NR>=26&&NR<=50' "$titlesFile" | nl
                        _BlankLine
                    ;;
                    *)
                        _WrongOption "$nextpage"
                        _Menu
                    ;;
                esac
            ;;
            -l)
                echo -e "\n ${info}Titles for $list${nc}\n"
                nl "$titlesFile"; _BlankLine
            ;;
        esac

    else
        printf '%s\n' " ${critical}${titlesFile} does not exist or empty...${nc}" \
        " ${task}${b}Getting $(_GetLinesList -l) titles...please wait.${nb}${nc}"
        touch "$titlesFile"; sleep 2; _GetMediaTitle -l; clear
        echo -e "\n ${info}Titles for $list.${nc}\n"
        nl "$titlesFile"
        _BlankLine
    fi

}
