#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2013,SC2154
_UpdateSelected() {
    cd "$playlists_dir" || exit 1
    
    # let's remove downloaded links from the original file
    # and sending the other ones in a second temporary file...
    grep -v "$(grep '^https' "$CHOOSE1")" "$list" >> "$CHOOSE2"
    perl -i -ne 'print if ! $a{$_}++' "$CHOOSE2"
    
    # ...that we now rename with the original file name.
    mv -f "$CHOOSE2" "$list"
    rm "$CHOOSE1"
    
    cd "$titles_dir" || exit 1

    case "$1" in
        -e)
            grep -v -F "$(grep '^[[:print:]]' "$SELECTEDTITLES")" \
            "$titles_dir"/"$list".titles >> "$SELECTEDTITLES"_tmp
            perl -i -ne 'print if ! $a{$_}++' "$SELECTEDTITLES"_tmp
            mv -f "$SELECTEDTITLES"_tmp "$titles_dir"/"$list".titles
            rm "$SELECTEDTITLES"
            __
            printf '%s\n' " ${info}Changes applied in $list.${nc}"
            sleep 3
        ;;
        -u)
            grep -v -F "$(grep '^[[:print:]]' "$SELECTEDTITLES"_orgin)" \
            "$titles_dir"/"$list".titles >> "$SELECTEDTITLES"
            perl -i -ne 'print if ! $a{$_}++' "$SELECTEDTITLES"
            mv -f "$SELECTEDTITLES" "$titles_dir"/"$list".titles
            rm "$SELECTEDTITLES"_orgin
        ;;
    esac
    
    clear
}
