#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2013,SC2154
_UpdateSelected() {

    cd "$playlists_dir" || exit 1
    # let's remove downloaded links from the original file
    # and sending the other ones in a second temporary file...
    grep -v "$(grep '^https' "$CHOOSE1")" "$list" >> "$CHOOSE2"
    # removing possible duplicates.
    perl -i -ne 'print if ! $a{$_}++' "$CHOOSE2"

    # ...that we now rename with the original file name.
    mv -f "$CHOOSE2" "$list"
    rm "$CHOOSE1"

    cd "$titles_dir" || exit 1
    __
    echo -e " ${task}${b}Refreshing titles...please wait.${nb}${nc}\n"
    _GetMediaTitle -l > "$titles_dir"/"$list".titles
    rm "$SELECTEDTITLES"
    clear

}
