#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_UpdateSelected() {

    cd "$playlists_dir" || exit 1
    # testing if we removed all titles in the list when we chose the edit playlist option.
    if (( $(grep -c '^https' "$list") == $(grep "" -c "$SELECTED_URLS1") )); then
        rm {"$list","$SELECTED_URLS1","$titles_dir"/"$list".titles,"$SELECTED_TITLES"}
        printf '\n%s\n' " ${critical}All links selected, ${list##*/} removed...${nc}"
        sleep 2; clear
    else
        # let's remove downloaded links from the original file
        # and sending the other ones in a second temporary file...
        grep -v "$(grep '^https' "$SELECTED_URLS1")" "$list" >> "$SELECTED_URLS2"
        _RemoveDuplicateLines "$SELECTED_URLS2"

        # ...that we now rename with the original file name.
        mv -f "$SELECTED_URLS2" "$list"
        
        cd "$titles_dir" || exit 1
        # same operation for the titles.
        case "$1" in
            -e)
                grep -v -F "$(grep '^[[:print:]]' "$SELECTED_TITLES")" \
                "$list".titles >> "$SELECTED_TITLES"_tmp
                _RemoveDuplicateLines "$SELECTED_TITLES"_tmp
                mv -f "$SELECTED_TITLES"_tmp "$list".titles
                printf '\n%s\n' " ${info}Changes applied in ${list##*/}.${nc}"
                sleep 3
            ;;
            -u)
                grep -v -F "$(grep '^[[:print:]]' "$SELECTED_TITLES"_orgin)" \
                "$list".titles >> "$SELECTED_TITLES"_tmp
                _RemoveDuplicateLines "$SELECTED_TITLES"_tmp
                mv -f "$SELECTED_TITLES"_tmp "$list".titles
            ;;
        esac

        clear
        
    fi
    
}
