#!/usr/bin/env bash

## This is a part of main script: mpm.
# shellcheck disable=SC2154
_ValidateSchedules() {

    declare -a localVars=(
        crdt crsc crtm
        schd schs scht
        datetime list tmpf
    )

    for lv in "${localVars[@]}"; do
        local "$lv"
    done

    crdt=$(date '+%Y-%m-%d')
    crtm=$(date '+%H:%M')
    tmpf=$(mktemp)
    cp "$schedulesFile" "$tmpf"

    # Update past schedules and check conflicts
    declare -A scheduleTimes
    while IFS='|' read -r datetime _ list; do
        # Extract date and time from datetime field
        schd=${datetime%@*} schd=${schd## } schd=${schd%% }
        scht=${datetime#*@} scht=${scht## } scht=${scht%% }

        # Check for past schedules
        crsc=$(date -d "${crdt} ${crtm}" +%s)
        schs=$(date -d "${schd} ${scht}" +%s)

        if ((schs < crsc)); then
            new_date=$(date -d "tomorrow" '+%Y-%m-%d')
            printf '%s\n' " ${critical}Schedule for playlist $list is in the past." \
            " ${info}Updating schedule to ${new_date}...${nc}"
            sed -i "s/${schd} @ ${scht}/${new_date} @ ${scht}/" "$tmpf"
            schd="$new_date"
            sleep 3
        fi

        # Check for conflicts using date and time, variable $schedule_delay is set in mpmrc.
        if [[ -n "${scheduleTimes[$schd $scht]}" ]]; then
            printf '\n%s\n' \
            " ${critical}Conflict detected: Multiple playlists scheduled for ${schd} at ${scht}${nc}"
            printf '%s\n' " ${info}Resolving conflict...${nc}"
            new_time=$(date -d "${schd} ${scht} ${schedule_delay} minutes" '+%H:%M')
            awk -v old="${schd} @ ${scht}" -v new="${schd} @ ${new_time} " -v list="$list" '
                BEGIN { FS=OFS="|" }
                $3 ~ list { $1 = new }
                { print }
            ' "$tmpf" > "${tmpf}.new" && mv "${tmpf}.new" "$tmpf"
            scht="$new_time"
            sleep 3
        fi
        scheduleTimes["$schd $scht"]="$list"
    done < "$schedulesFile"

    mv "$tmpf" "$schedulesFile"
    sort -t'|' -k1 "$schedulesFile" -o "$schedulesFile"

    pgrep --full mpmsw >/dev/null && {
        kill -SIGRTMIN+15 $(pgrep --full mpmsw)
        _BlankLine
        printf '%s\n' " ${info}Notifying mpmsw of new schedule...${nc}"
        sleep 2
    }

    _PolybarIpc
    _Menu

}
