#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ViewAudioVideoUrlsInfo() {

    local stars

    viewUrlInfoPrompt=(
        "${info}[${mtitle}M${info}]aim menu,"
        "[A]dd links," "[D]ownload," "[E]dit,"
        "[P]lay," "[R]emove," "[S]ave:"
    )

    mpvOwnsInfoPrompt=(
        "[M]aim menu," "[D]ownload (this list will be preserved after download)"
    )

    stars=$(printf "%-55s" "*")
    __tmpListCount() ( grep -c '^https' "$menuTitleType_$URLS"; )

    __listHeader() {
        clear
        _BlankLine
        if (($(__tmpListCount) > 12)); then
            if (($(__tmpListCount) > 25)); then
                stars=$(printf "%-42s" "*")
                printf '%s\n' \
                " ${info}ORDER | $menuTitleType PLAYLIST TITLES ${b}(page 1/2)${nb}${nc}"
                echo -e " ${info}${stars// /*}${nc}\n"
                awk 'NR>=1&&NR<=25' "$TITLES" | nl
                _BlankLine
                read -rsn 1 -p " ${viewUrlInfoPrompt[0]} [N]ext page: ${nc}" nextpage
                case "$nextpage" in
                    m|M) _Menu ;;
                    n|N)
                        clear
                        printf '\n%s\n' \
                        " ${info}ORDER | $menuTitleType PLAYLIST TITLES ( page 2 )${nc}"
                        echo -e " ${info}${stars// /*}${nc}\n"
                        awk 'NR>=26&&NR<=50' "$TITLES" | nl
                        _BlankLine
                    ;;
                    *)
                        _WrongOption "$nextpage"
                        _Menu
                    ;;
                esac
            else
                stars=$(printf "%-56s" "*")
                printf '%s\n' \
                " ${info}ORDER | $menuTitleType PLAYLIST TITLES (too many urls to show).${nc}"
                echo -e " ${info}${stars// /*}${nc}\n"
                nl "$menuTitleType_$TITLES"
                _BlankLine
            fi
        else
            printf '%s\n' " ${info}ORDER |  $menuTitleType PLAYLIST LINKS & TITLES.${nc}"
            echo -e " ${info}${stars// /*}${nc}\n"
            awk '$0 ~ /^https/{print $0}' "$menuTitleType_$URLS" \
            | nl && {
                _BlankLine
                nl "$menuTitleType_$TITLES"
                _BlankLine
            }
        fi

        if [[ $URLS == "$DEFAULT_LIST" ]]; then
            if [[ $downloadTmpList == default ]]; then
                echo " ${info}${mpvOwnsInfoPrompt[*]}${nc}"
            else
                unset 'viewUrlInfoPrompt[1]'
                echo " ${info}${viewUrlInfoPrompt[*]}${nc}"
            fi
        else
            if [[ $downloadTmpList == list ]]; then
                echo " ${info} ${mpvOwnsInfoPrompt[*]}${nc}"
            else
                echo " ${info}${viewUrlInfoPrompt[*]}${nc}"
            fi
        fi

    }

    __audioVideoCommon() {

        if [[ -s $URLS ]]; then
            _ResizeWindow --main
            __listHeader

            read -rsn 1 audioVideoCommonOptions

            case "$audioVideoCommonOptions" in
                a|A) _CreateAddPlaylist "$arg" ;;
                d|D) _CreateAddPlaylistActions --download ;;
                e|E) _MpvOwnsTmpList --list || _EditTmpListTitles ;;
                m|M) _Menu ;;
                p|P) _CreateAddPlaylistActions --play ;;
                r|R) _CreateAddPlaylistActions --remove ;;
                s|S) _CreateAddPlaylistActions --save ;;
                *)
                    _WrongOption "$audioVideoCommonOptions"
                    return
                ;;
            esac
        else
            _ResizeWindow --copy
            printf '%s\n' " ${critical}No links in the $Type list${nc}"
            sleep 2 && return
        fi

    }

    case "$1" in
        -a|-v) __audioVideoCommon ;;
        -d) _ViewDefaultUrlsInfo ;;
    esac

}
