#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154,SC2015,SC2034
_ViewUrlInfoDefault() {
        
    if (($(_GetLinesList -q) > 0)); then
        rm "$tmp_dir"/1 2>/dev/null
        
        [[ $(grep "" -c "$DEFAULTITLES") -ne $(_GetLinesList -q) ]] && {
            printf '%s\n' " ${critical}Default list as been modified," \
            " ${task}${b}Updating Default list titles...${nb}${nc}"
            _GetMediaTitle -q > "$DEFAULTITLES"
        }
        clear
        
        while [[ -f $QUEUE ]]; do
            menuTitleType=DEFAULT
            URLS="$QUEUE"
            TITLES="$DEFAULTITLES"
            [[ $(awk -F"/" '{print $NF}' "$NOWPLAYING" 2>/dev/null) =~ default ]] && {
                pgrep -x mpv >/dev/null && {
                    __
                    printf '%s\n' " ${critical}default list is owned by mpv..." \
                                    " if you want to perform any action on it," \
                                    " just quit mpv first to continue.${nc}"
                    __
                    read -rsn 1 -p " ${info}[Q]uit mpv, [A]bort: ${nc}" quitMpv
                    case "$quitMpv" in
                        q|Q)
                            kill -SIGTERM "$(pidof mpv)" && continue
                        ;;
                        a|A)
                            return
                        ;;
                        *)
                            _WrongOption "$quitMpv" && return
                        ;;
                    esac
                }
                rm "$NOWPLAYING"
            }
            __
            __listHeader
            read -rsn 1 queueOptions
            case "$queueOptions" in
                d|D)
                    __
                    read -rsn 1 -p "${info}"' Download [A]udio, [V]ideo:'"${nc}" get
                    case "$get" in
                        a|A) __; _GetAudio -q ;;
                        v|V) __; _GetVideo -q ;;
                        *)
                            __
                            _WrongOption "$get"
                            return
                        ;;
                    esac
                ;;
                m|M)
                    _Menu
                ;;
                p|P)
                    __
                    read -rsn 1 -p "${info}"' Play [A]udio, [V]ideo?: '"${nc}" play
                    case "$play" in
                        a|A) _LoadAudioVideo -qa ;;
                        v|V) _LoadAudioVideo -qv ;;
                        *)
                            _WrongOption "$play"
                            return
                        ;;
                    esac
                ;;
                r|R) _Remove -q ;;
                s|S)
                    if [[ -f $DEFAULTM3UTITLES \
                        || -f  $DEFAULTITLES ]]; then
                        _Save -q
                    else
                        printf '%s\n' " ${task}${b}Updating Default list titles...${nb}${nc}"
                        _GetMediaTitle -q \
                        | tee -a "$DEFAULTITLES" \
                        | cat -n >/dev/null 2>&1
                        _Save -q
                    fi
                ;;
                *)
                    _WrongOption "$queueOptions"
                    return
                ;;
            esac
        done
    else
        echo " ${critical}There is nothing to do, Default playlist is empty...${nc}"
        sleep 3
    fi
}