#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ViewUrlInfo() {
    # Normaly in Bash nested functions use parentheses instead of curly braces,
    # but here it won't work because of the case statment right parenthese...
    # They will close the block before it finishes.

    local defaultTitles stars

    viewUrlInfoPrompt=( "[M]aim menu" "[B]ack to audio options" \
                        "[B]ack to video options" "[D]ownload" \
                        "[P]lay" "[S]ave as" "[R]emove list: " )

    # let's play...
    stars=$(printf "%-54s" "*")

    __audio() {
        if [[ -s $AUDIO_URLS ]]; then
            clear
            __
            echo " ${info}ORDER |  AUDIO PLAYLIST LINKS & TITLES.${nc}"
            echo -e " ${info}${stars// /*}${nc}\n"
            awk '$0 ~ /^https/{print $0}' "$AUDIO_URLS" \
            | cat -n && {
                __
                cat -n "$AUDIO_TITLES"
            __
            }
            unset {viewUrlInfoPrompt[2],viewUrlInfoPrompt[7]}
            __
            echo "${info}" "${viewUrlInfoPrompt[*]}" "${nc}"
            read -rsn 1 opt
            case "$opt" in
                b|B) __; _CopyUrl -a ;;
                m|M) _Menu ;;
                d|D) _GetAudio -a ;;
                p|P) _LoadAudioVideo -a ;;
                r|R) _Remove -a ;;
                s|S) _Save -a ;;
            esac
        else
            echo " ${critical}No links in the list${nc}"
            sleep 2 && return
        fi
    }

    __video() {
        if [[ -s $VIDEO_URLS ]]; then
            clear
            __
            echo " ${info}ORDER |  VIDEO PLAYLIST LINKS & TITLES.${nc}"
            echo -e " ${info}${stars// /*}${nc}\n"
            awk '$0 ~ /^https/{print $0}' "$VIDEO_URLS" \
            | cat -n && {
                __
                cat -n "$VIDEO_TITLES"
            __
            }
            unset {viewUrlInfoPrompt[1],viewUrlInfoPrompt[7]}
            __
            echo "${info}" "${viewUrlInfoPrompt[*]}" "${nc}"
            read -rsn 1 opt
            case "$opt" in
                b|B) __; _CopyUrl -v ;;
                m|M) _Menu ;;
                d|D) _GetVideo -v ;;
                p|P) _LoadAudioVideo -v ;;
                r|R) _Remove -v ;;
                s|S) _Save -v ;;
            esac
        else
            echo " ${critical}No links in the list${nc}"
            sleep 2 && return
        fi
    }

    __queue() {
        if (($(_GetLinesList -q) > 0)); then
            [[ -f $tmp_dir/1 ]] && rm "$tmp_dir"/1

            if [[ -f $DEFAULTM3UTITLES ]]; then
                defaultTitles="$DEFAULTM3UTITLES"
            else
                defaultTitles="$DEFAULTITLES"
            fi

            (( $(grep "" -c "$defaultTitles") != $(_GetLinesList -q) )) && {
                printf '%s\n' " ${critical}Default list as been modified," \
                " ${task}${b}Updating Default list titles...${nb}${nc}"
                _GetMediaTitle -q > "$defaultTitles"
            }
            clear
            __
            echo " ${info}ORDER |  DEFAULT PLAYLIST LINKS & TITLES.${nc}"
            echo -e " ${info}${stars// /*}${nc}\n"
            awk '$0 ~ /^https/{print $0}' "$QUEUE" \
            | cat -n && {
            __
            cat -n "$defaultTitles"
            __
            }

            while [[ -f $QUEUE ]]; do
                unset {viewUrlInfoPrompt[1],viewUrlInfoPrompt[2],viewUrlInfoPrompt[7]}
                echo "${info}" "${viewUrlInfoPrompt[*]}" "${nc}"
                read -rsn 1 opt
                case "$opt" in
                    d|D)
                        __
                        read -rsn 1 -p "${info}"' Download [A]udio, [V]ideo:'"${nc}" get
                        case "$get" in
                            a|A) __; _GetAudio -q ;;
                            v|V) __; _GetVideo -q ;;
                        esac
                    ;;
                    m|M)
                        _Menu
                    ;;
                    p|P)
                        __
                        read -rsn 1 -p "${info}"' Play [A]udio, [V]ideo?: '"${nc}" play
                        case "$play" in
                            a|A) _LoadAudioVideo -qa ;;
                            v|V) _LoadAudioVideo -qv ;;
                        esac
                    ;;
                    r|R) _Remove -q ;;
                    s|S)
                        if [[ -f $DEFAULTM3UTITLES \
                            || -f  $DEFAULTITLES ]]; then
                            _Save -q
                        else
                            echo " ${task}${b}Updating Default list titles...${nb}${nc}"
                            _GetMediaTitle -q \
                            | tee -a "$DEFAULTITLES" \
                            | cat -n >/dev/null 2>&1
                            _Save -q
                        fi
                    ;;
                esac
            done
        else
            echo " ${critical}There is nothing to do, Default playlist is empty...${nc}"
            sleep 3
        fi
    }

    case "$1" in
        -a) __audio ;;
        -v) __video ;;
        -q) __queue ;;
    esac
}
