#!/usr/bin/env bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ViewScheduledList() {

    local schedules_file dash plst
    schedules_file="$schedules_dir/schedules.txt"

    if [[ ! -f "$schedules_file" ]]; then
        printf '%s\n' " ${critical}No schedule file found.${nc}"
        sleep 2
        return
    fi

    clear
    echo -e "\n ${info}${B}Scheduled downloads list:${NB}${nc}\n"
    sort -t'|' -k1 "$schedules_file" -o "$schedules_file"
    dash=$(printf "%-72s" "─")
    printf '%s\n' \
        "  ${info}DATE & TIME          | TYPES | PLAYLISTS${nc}"
    echo " ${info}${dash// /─}${nc}"
    nl -w2 -s') ' "$schedules_file"

    _BlankLine
    declare -a viewSchedulesPrompt=(
        "${info} [E]dit or"
        "to remove a schedule hit its number"
        "or [${mtitle}C${info}]ancel: ${nc}"
    )
    read -rp "${viewSchedulesPrompt[*]}" viewSchedulesOptions

    case "$viewSchedulesOptions" in
        [0-9])
            plst=$(sed 's/.*|\s//g' < <(sed -n "${viewSchedulesOptions}p" "$schedules_file"))
            sed -i "${viewSchedulesOptions}d" "$schedules_file"
            if [[ ! -s $schedules_file ]]; then
                rm "$schedules_file"
                pgrep --full mpmsw >/dev/null && {
                    kill -SIGTERM $(pgrep --full mpmsw)
                    sed -i '1s/^/#EXTM3U\n/' "$schedules_dir"/"$plst"
                    _BlankLine
                    printf '%s\n' " ${info}Stopping mpmsw...${nc}"
                    sleep 2
                }
            elif [[ -s $schedules_file ]]; then
                pgrep --full mpmsw >/dev/null && {
                    kill -SIGRTMIN+15 $(pgrep --full mpmsw)
                    _BlankLine
                    printf '%s\n' " ${info}Reloading mpmsw...${nc}"
                }
            fi
            printf '\n%s\n' " ${critical}schedule $viewSchedulesOptions ($plst) removed.${nc}"
            sleep 3
            mv "$schedules_dir"/"$plst" "$playlists_dir"
            mv "$schedules_dir"/"$plst.titles" "$titles_dir"
            unset plst
            ;;
        [eE])
            "$MPMEDITOR" "$schedules_file"
            _ValidateSchedules
            clear
            printf '\n%s\n' " ${info}Schedule file edited.${nc}"
            sleep 2
            ;;
        *) _Menu ;;
    esac

}
