#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_ViewDefaultAudioVideoTitles() {

    stars=$(printf "%-41s" "*")

    printf '%s\n' " ${info}ORDER | $menuTitleType PLAYLIST TITLES (page 1).${nc}"
    echo -e " ${info}${stars// /*}${nc}\n"
    awk 'NR>=1&&NR<=25' "$TITLES" | nl
    __
    read -rsn 1 -p " ${info}[M]ain menu, [N]ext page.${nc}" nextpage
    case "$nextpage" in
        m|M) _Menu ;;
        n|N)
            clear; __
            printf '%s\n' " ${info}ORDER | $menuTitleType PLAYLIST TITLES (page 2).${nc}"
            echo -e " ${info}${stars// /*}${nc}\n"
            awk 'NR>=26&&50' "$TITLES" | nl
            __
        ;;
        *)
            _WrongOption "$nextpage"
            _Menu
        ;;
    esac

}