#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2034,SC2154
_WhileMpvIsRunning() {

    local mpv_is_running
    mpv_is_running="yes"
    touch "$tmp_dir"/playerSelectedFile

    while _PidOfMpv >/dev/null; do
        sleep 1
    done

    localPlaylist="no"
    mpv_is_running="no"

    if [[ $mpvc_tui == native ]]; then
        _RemoveMpvTmp
        kill -SIGTERM "$(pidof -x fzf)" 2>/dev/null
    else
        _RemoveMpvTmp
        kill -SIGTERM "$(pidof -x "$mpvc_tui")" 2>/dev/null
    fi

    _MenuFooter

}
