#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2034
_WhileMpvIsRunning() {
    mpv_is_running="yes"
    while [[ -n $(pidof mpv) && -e $NOWPLAYING ]]; do
        sleep 1
    done
    _IfMpvc
}