#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_WrongOption() {
    # appears 25 times in 20 files
    __
    printf '%s\n' " ${critical}Wrong option $1 ${nc}"
    sleep 3
}