#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_WrongOption() {

    # appears 31 times in 26 files
    printf '\n%s\n' " ${critical}Wrong option $1 ${nc}"
    sleep 3

}
