#!/bin/bash
## This is a part of main script: mpm.

# shellcheck disable=SC2154
_YtdlGetTitle() {
    yt-dlp \
    --skip-download \
    --get-title \
    --flat-playlist \
    "${ytdlPreset_DW[@]}" "$1"
}